### ISSUE TITLE
support multi-line image urls

### ISSUE THREAD

**Issue by richardwthompson** [vsch/idea-multimarkdown#103]
I have been using Gravizo (http://gravizo.com/) in my markdown documents to allow me to incorporate diagrams.

This works great when I actually generate the html files from my markdown docs.

The only down side is that the multimarkdown preview doesn't support this ... which I assume is down to the image url being split over multiple lines.

Is there any way that the multimarkdown preview functionality could be updated to support / render multi-line image urls?

E.g. the following works when I generate the full html file ... but it **doesn't** work with multimarkdown preview

     ![Alt text](http://g.gravizo.com/g?
      digraph G {
        aize ="4,4";
        main [shape=box];
        main -> parse [weight=8];
        parse -> execute;
        main -> init [style=dotted];
        main -> cleanup;
        execute -> { make_string; printf}
        init -> make_string;
        edge [color=red];
        main -> printf [style=bold,label="100 times"];
        make_string [label="make a string"];
        node [shape=box,style=filled,color=".7 .3 1.0"];
        execute -> compare;
      }
    )

![Alt text](http://g.gravizo.com/g?
  digraph G {
    aize ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf}
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
)

**Comment by vsch** [comment]
@richardwthompson, yes pegdown does not handle multi-line urls. I am planning to address this but it goes into the guts of its processing and I did not plan on doing this until later.

The only workaround is to use the HTML img tag, but then GitHub will not process it so it will only work for in-plugin viewing. 

```markdown
<img src='http://g.gravizo.com/g?
  digraph G {
    aize ="4,4";
    main [shape=box];
    main -> parse [weight=8];
    parse -> execute;
    main -> init [style=dotted];
    main -> cleanup;
    execute -> { make_string; printf}
    init -> make_string;
    edge [color=red];
    main -> printf [style=bold,label="100 times"];
    make_string [label="make a string"];
    node [shape=box,style=filled,color=".7 .3 1.0"];
    execute -> compare;
  }
'>
```

I will put this on a higher priority and try to get it into the plugin for next release, milestone Version 1.4.0 slated for Jan 25th release. 

It is something that was asked by another user in #4  and I thought that using `img` html tag was a workaround but when checked it against GitHub realized it does not work.

**Comment by vsch** [comment]
@richardwthompson, I have some good news for you and some great news!

I hacked multi-line URL images into pegdown and added a cherry on top by adding language injections into the multi-line content. 

![gravizo](https://cloud.githubusercontent.com/assets/10299086/12077689/0664aa3c-b1c0-11e5-9d97-72cf08cee971.gif)

![gravizo2](https://cloud.githubusercontent.com/assets/10299086/12077737/a17e303c-b1c1-11e5-9afa-26bea182f2bf.gif)

I will be finalizing the release tomorrow, so this feature will be in it. 

Customizations for how the text-fragment is converted during fragment editing will be added in the next version. For now removing and adding ; at end of line is hardcoded if the URL starts with "http://g.gravizo.com/g?". 

You can even preview with "PlantUML integration" plugin.

![gravizo3](https://cloud.githubusercontent.com/assets/10299086/12077767/e52368b0-b1c2-11e5-8d28-a364cb36b48d.gif)

Hope you like it.
