### ISSUE TITLE
Opening a Markdown file causes NoClassDefFoundError

### ISSUE THREAD

**Issue by Cakasim** [vsch/idea-multimarkdown#104]
If I try to open a Markdown file I get the error line: __NoClassDefFoundError: com/vladsch/idea/multimarkdown/editor/split/UIUtils__.

I am using CLion 1.2.4 on Windows 10.

**Comment by vsch** [comment]
@Cakasim, thank you for reporting this. There is a fixed version that addresses this issue: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.1.2.zip>

Please download it and install from disk. I will be making and updated release soon but you can get the fix now.

**Comment by vsch** [comment]
@Cakasim, the fix posted is confirmed to solve the problem for CLion.
