### ISSUE TITLE
Formatting and Editing Enhancements

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#124]
- [x] Live templating on typing .
    - [x] task list items: after a bullet list marker should insert `[ ]` on space or `[x]` on x
          or X.
    - [x] wiki links: should insert `[[]]`, leave the cursor inside and open completions.
    - [x] explicit links: should insert `[]()` leave cursor inside `()`, then move between `[]`
    - [x] **NOT NEEDED**. explicit links: whose target starts with `#` should offer link
          completion based on the text in `[]` and the available anchor links in the file.
    - [x] explicit image links, same as above but insert `![]()`
    - [x] references: insert `[]:`, move cursor after `:`, then inside `()`.
    - [x] abbreviations: insert `*[]:`, leave cursor inside brackets, then move cursor after
          `:`.
- [x] document tree structure display
- [x] code completion of tables (insert table of x columns by y rows with blank header and body
      columns)
- [ ] code formatting
    - [ ] format fix indentations (to multiples of 4 or align with parent where possible)
    - [x] format tables to expand/contract all columns to reflect the column sizes and alignment
    - [x] renumber ordered list items to reflect position 
    - [ ] group/move references to top/bottom of file
- [ ] code refactoring
    - [ ] convert HTML table to/from MultiMarkdown table

**Comment by jonaswouters** [comment]
will this fix links like?:

```markdown
[![License][License-Image]][License-URL] 

[License-URL]: https://github.com/jonaswouters/goclerk/blob/master/LICENSE
[License-Image]: https://img.shields.io/github/license/jonaswouters/goclerk.svg
```

**Comment by vsch** [comment]
@jonaswouters, thank you for bringing this to my attention. This is actually a bug in the lexer/parser.

I opened a new issue #196 and will post a patch release as soon as it is fixed.

**Comment by vsch** [comment]
@jonaswouters, parsing and highlighting fixed for compound links.

Please download and install from disk. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.10.5.zip>

Completions don't work in nested links. I still have to figure out why the IDE shows "No Suggestions" when I pass it all the same suggestions.
