### ISSUE TITLE
cursor problem after enter and live template

### ISSUE THREAD

**Issue by linux-china** [vsch/idea-multimarkdown#129]
I have following code, and if my cursor in [caret] and press enter, the position of cursor will move to the starter of code, not next line.  Another problem is live template, I input "psvm" and press tab, the position of cursor is incorrect. 

```java
        @Component
        public class Demo {
            @Autowired
            DataSource datasource;
            @Autowired
            JdbcTemplate jdbcTemplate;  [caret]
        }
```

**Comment by vsch** [comment]
@linux-china, thank you for reporting the issue. Can you please provide the Markdown context for the code fence. The best would be the actual markdown file if it is not proprietary or a small sample that has the issue. In the extreme case I would need at least the surrounding markdown elements, especially the ones that require prefix or indentation of the code fence. 

**I am assuming you are editing it as a Java Fragment and not as part of the main Markdown editor text.** Let me know if this assumptions is correct.

As you describe it, I cannot reproduce the issue. Which only means that I am missing critical information to be able to duplicate it.

For example, if the code fence is part of a list item, like this:

    1.  Some text
    
        ```java
        class Demo {
        
        }
        ```
    
that renders as:
    
1.  Some text

    ```java
    class Demo {
    
    }
    ```
    
or if it is part of a block quote:    

    > 1.  Some text
    > 
    >     ```java
    >     class Demo {
    >     
    >     }
    >     ```

would render as:

> 1.  Some text
> 
>     ```java
>     class Demo {
>     
>     }
>     ```

**Comment by vsch** [comment]
@linux-china, I found a bug report in IntelliJ that seems to be similar to the issue you are having [IDEA-115454 Can't edit fragments from several files](https://youtrack.jetbrains.com/issue/IDEA-115454)

I also reported another bug that may cause similar symptoms: [IDEA-150174 Edit language fragment fails to open editor but works if first fragment editor is first moved to opposite group. Then replaces fragment editor with another editor on edit operation in fragment.](https://youtrack.jetbrains.com/issue/IDEA-150174)

These are not plugin but IDEA Language Injection issues.
