### ISSUE TITLE
HTML Preview in every scratch file

### ISSUE THREAD

**Issue by natros** [vsch/idea-multimarkdown#14]
HTML Preview in every scratch file

![scratch_2_-_online_ipb_-____projects_ipb_online_ipb__-_intellij_idea__minerva__iu-142_4245_2](https://cloud.githubusercontent.com/assets/4996289/9632660/67f82634-5180-11e5-974e-a26a5822bfee.png)

IntelliJ IDEA (Minerva) IU-142.4245.2
Build #IU-142.4245, built on August 25, 2015
JRE: 1.8.0_60-b27 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by vsch** [comment]
Thanks for bringing it to my attention. 

The fix for this is in the next release that will be out shortly.

**Comment by vsch** [comment]
@natros, New version up on the official Site. Thank you again for reporting this. It was my simple approach and IDEA complexity that bit me on this one.
