### ISSUE TITLE
Bug: URL encode

### ISSUE THREAD

**Issue by VijitCoder** [vsch/idea-multimarkdown#153]
Plugin encodes an URLs, that is wrong. For example:

\[link\] (http ://site.com/home?r=west-2#Instances:sort=instanceId) 

become 
http ://site.com/home?r=west-2%23Instances%3Asort=instanceId 
but must be, as typed
http ://site.com/home?r=west-2#Instances:sort=instanceId

There shouldn't be any encoding, because link is already prepared for using.

**Comment by vsch** [comment]
@VijitCoder, thank you for the report. I'll post a link to download a fixed version so you don't have to wait for the official release.

**Comment by vsch** [comment]
@VijitCoder, fixed. Please download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.3.1.zip>

**Comment by VijitCoder** [comment]
It is working. Thanks.
