### ISSUE TITLE
Automatically hard wrap lines

### ISSUE THREAD

**Issue by ncuillery** [vsch/idea-multimarkdown#157]
The plugin have an "Hard wraps" option for the preview tab but unless I miss something, there is no option to hard wrap the lines automatically.

It exists for other editor : 
Sublime : https://github.com/randy3k/AutoWrap
Atom: https://discuss.atom.io/t/automatically-hard-wrap-lines/8986

**Comment by vsch** [comment]
@ncuillery, the wrapping option in the editor is part of formatting features that I am in the process of implementing now.

Markdown being different from other languages supported by IDE requires quite a bit of implementation to have these features working. I originally thought it would be a few settings and some extensions but once got into the code realized it is more effort than that. All existing formatting infrastructure in IntelliJ OpenApi is geared towards structured syntax languages which markdown does not fit.

Formatting is slated for next release, that I had to bump it over by two weeks to account for original under estimation of effort.

**Comment by ncuillery** [comment]
Ok, courage and good luck with that ! :sweat_smile:

**Comment by asrinivasan** [comment]
+1

**Comment by vsch** [comment]
@ncuillery, @asrinivasan , version 1.4.5 has been released. It has wrap on typing and table formatting on typing.
