### ISSUE TITLE
Needs a multimarkdown preference pane

### ISSUE THREAD

**Issue by btipling** [vsch/idea-multimarkdown#161]
I'm interested in paying for the enhanced version but I have no idea what state I'm in or see any way to add a license. This project needs to add a dedicated preference pane or window to manage the preferences and state for this plugin. Even a cmd+shift+a for multimarkdown doesn't show anything.

**Comment by vsch** [comment]
@btipling,  the current version does not have per project settings. All settings are either application shared or non-shared local settings which only include license, notification state and other non-parser/renderer type settings.

Project based parser/renderer configuration is on a short to do list. I will address this after completing the auto formatting functionality. Auto formatting is scheduled to be released within a week. Formatting settings are be project based.

Application preferences/settings for idea-multimarkdown are under "Languages & Frameworks" in preferences (Mac) / settings (Windows).

<img width="1006" alt="screen shot 2016-02-12 at 3 08 44 pm" src="https://cloud.githubusercontent.com/assets/10299086/13018946/8b8efd1c-d19a-11e5-9810-6210babe3a83.png">

**Comment by btipling** [comment]
Thank you. I'm not sure why I wasn't able to find that preference pane. That's exactly what I was looking for. Thank you.
