### ISSUE TITLE
Switch off an autocomplete

### ISSUE THREAD

**Issue by VijitCoder** [vsch/idea-multimarkdown#172]
Hi. 
Phpstorm + this plugin v.1.4.6
How to switch off an autocomplete of markup symbols? It is really annoying. I didn't find a setting or information about it.
E.g. when I typed "*", I got one star more. I don't need it by default.

**Comment by vsch** [comment]
@VijitCoder, it is in Code Style under MultiMarkdown:

![screen shot 2016-02-28 at 10 25 42 am](https://cloud.githubusercontent.com/assets/10299086/13380047/0d11205a-de06-11e5-9f29-b0522156e96b.png)

**Comment by VijitCoder** [comment]
Great. Thanks :)
