### ISSUE TITLE
Suggestion: URL-to-filename transformation rules for image previews

### ISSUE THREAD

**Issue by drdaeman** [vsch/idea-multimarkdown#174]
Just tried this plugin for some Django-based website project that renders Markdown files, and encountered a small inconvenience. I was writing a few documents that had code like this:

```
![Some image]({{ static_root }}/img/file.png)
```

(With `{{ static_root }}` being substituted at runtime) Obviously, I wasn't able to see the images in the preview, so I had to temporarily write

```
![Some image](../../../static/img/file.png)
```

(With number of `../` varying depending on document depth) and replace those after the documents were completed.

So, I think it would be nice if one could specify one or more URI-to-file-path transformation rules like `^{{\s*static_root\s*}}/` -> `$project_root/static/`, so the previews would work even if images are kept separate from the documents. I guess, such transformations should only apply to the schema-less URLs, e.g. `^` -> `/static/` shouldn't add prefix to, say, `https://example.org/acme.png` - although with powerful enough PCREs, this can be also done using negative look-ahead assertions as well.

Does this sounds like a good idea?

**Comment by vsch** [comment]
@drdaeman, yes it is a good idea. I am looking into creating a project based mapping for images and documents to allow link mapping for links for a non-GitHub based link resolution.

**Comment by vsch** [comment]
@drdaeman, EAP plugin update channel has a version that allows you to define replacement mapping from markdown link ref text to GitHub equivalent link ref text that will be used to resolve the target.

This is the Link Text to Link Ref table which is the first table of the `Link Map` config pane. The second table allows you do apply reverse mapping for completions, intentions and other areas of the plugin which generates the link text from a target file reference. That way you can have auto complete generate link text with a prefix.

You can use prefix strings or regular expressions.

For your case make the following config:

Link Text to Link Ref to allow resolving images and other links:

`{{ static_root }}/` --> `/static/`

Link Ref To Link Text for completions:

`/static/` --> `{{ static_root }}/`

This version also has per project rendering configuration and scope based configuration allowing you to tweak plugin config by scope defined in the IDE. Granularity can go down to file.

Very early wiki for functionality: https://github.com/vsch/idea-multimarkdown/wiki/Modifying-Link-Processing

![](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_LinkMap_Settings.png)
