### ISSUE TITLE
Chinese character display problem

### ISSUE THREAD

**Issue by Choate** [vsch/idea-multimarkdown#178]
If the first line is the chinese title, can't display.

```
#这是中文标题
这是中文内容
```

**Comment by vsch** [comment]
@Choate, can you please include a screenshot of the results you are getting.

Try including a space after the `#`. In Languages & Frameworks > MultiMarkdown > Parser there is an option for requiring a space after `#` for it to be considered a title header.

Here is what I tried and the result:

```markdown
# 这是中文标题
这是中文内容
```

<img width="553" alt="screen shot 2016-03-22 at 11 36 08 am" src="https://cloud.githubusercontent.com/assets/10299086/13957283/4a4eef32-f022-11e5-8be4-30ec03beeb09.png">

Turning off "ATX Header Space" option allows having a header without a space:

<img width="887" alt="screen shot 2016-03-22 at 11 37 45 am" src="https://cloud.githubusercontent.com/assets/10299086/13957363/979707a2-f022-11e5-97aa-2707ab2195d0.png">
<img width="552" alt="screen shot 2016-03-22 at 11 37 12 am" src="https://cloud.githubusercontent.com/assets/10299086/13957364/97a8aff2-f022-11e5-8f17-a513eea6e12a.png">

```markdown
#这是中文标题
这是中文内容
```

<img width="552" alt="screen shot 2016-03-22 at 11 37 12 am" src="https://cloud.githubusercontent.com/assets/10299086/13957430/d754a1c4-f022-11e5-893c-4bfdbedb6ceb.png">

**Comment by Choate** [comment]
![8d2c4244-8b38-4065-b514-4bb3d13ff88f](https://cloud.githubusercontent.com/assets/8521151/14010881/6ad2e764-f1d4-11e5-8e87-85d47eb60ec0.png)
![b8d90028-e1c8-4615-aed5-2036e92a8ded](https://cloud.githubusercontent.com/assets/8521151/14010882/6c829154-f1d4-11e5-9af1-b6b313efbead.png)

**Comment by Choate** [comment]
PhpStorm Version 10.0.3

**Comment by vsch** [comment]
@Choate, thank you for the information. I was testing WebView preview while the bug occurs in the Swing based preview.

I have replicated and fixed the issue and will post a fix here shortly.

**Comment by vsch** [comment]
@Choate, please download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.7.9.zip>

The issue is fixed. Previous versions of Swing preview would not display any characters in a heading if all characters were non-ascii alphanumerics.
