### ISSUE TITLE
Tabs to work with standard OSX keyboard shortcuts

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#179]
currently the tabs for Markdown, and HTML preview only with the keyboard shocuts Shift+Ctrl + Left/Right.  Can you also add the ability to use the standard OSX tab shortcuts as used in all the other tool windows ie Cmd+Shift+Left/Right.   This should help make the plugin feel better integrated.

**Comment by vsch** [comment]
The tab switching and associated short cuts are controlled by the IDE. To have OSX tab shortcuts you need to add them to the Keymap in IDE preferences/settings.
