### ISSUE TITLE
code syntax highlighting

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#180]
I initially thought the syntax highlighting feature was code syntax highlighting not highlighting of markdown. Would it be possible to syntax highlight code snippets using the built in intellij tools with the use of a flag to set the lanuguage?

**Comment by yunti** [comment]
the plugin does already support this ```java ``` or ```python ```

**Comment by vsch** [comment]
@yunti, syntax highlighting of markdown is done automatically. If I understand your question correctly you want to syntax highlight fenced code and verbatim blocks.

Fenced code is highlighted when the language specified matches the language recognized by the IDE. Code completion for fenced code language will show you all the languages recognized. Press Ctrl+Space with the caret located after the opening ```:

<img width="394" alt="screen shot 2016-03-22 at 11 56 04 am" src="https://cloud.githubusercontent.com/assets/10299086/13958068/19d28794-f025-11e5-8b9f-493d20e3b942.png">

For verbatim blocks you need to use the `Inject Language` option to select the language to be injected.

<img width="430" alt="screen shot 2016-03-22 at 11 48 46 am" src="https://cloud.githubusercontent.com/assets/10299086/13957769/0f5b8f6e-f024-11e5-95da-550e94c01be5.png">

You can also use `Edit Fragment` to edit the injected language fragment in a separate editor instance to make syntax highlighting completely controlled by the settings for the injected language.

<img width="422" alt="screen shot 2016-03-22 at 11 50 58 am" src="https://cloud.githubusercontent.com/assets/10299086/13957875/65776544-f024-11e5-9229-0b57dfee986a.png">

<img width="874" alt="screen shot 2016-03-22 at 11 51 08 am" src="https://cloud.githubusercontent.com/assets/10299086/13957878/69376fd0-f024-11e5-9789-0deb2e889e19.png">

**Comment by yunti** [comment]
thanks and I presume the preview output can't be highlighted because markdown doesn't support this?

**Comment by vsch** [comment]
HTML output is highlighted automatically by each processor that supports this. GitHub does this automatically.

idea-multimarkdown will use Hightlight JS JavaScript if this option is enabled in options:

<img width="992" alt="screen shot 2016-03-22 at 12 21 29 pm" src="https://cloud.githubusercontent.com/assets/10299086/13959031/b2f888f8-f028-11e5-8a93-9f8266b7193d.png">

<img width="993" alt="screen shot 2016-03-22 at 12 21 51 pm" src="https://cloud.githubusercontent.com/assets/10299086/13959036/b567ca86-f028-11e5-9c1a-696a34d3159d.png">

The colors and syntax elements are controlled through HLJS stylesheet customizations.

**Comment by yunti** [comment]
Thanks that is superb, very glad I paid.  Note the code output box has a border in a dark theme (Darcula) which isn't present in a light theme. 

![screen shot 2016-03-22 at 16 39 51](https://cloud.githubusercontent.com/assets/1826271/13959617/bb298ce2-f04c-11e5-8fc0-138c91d218f9.png)

**Comment by vsch** [comment]
@yunti, thanks for bringing it to my attention. I will fix the `darcula-fx.css` style sheet.

The default style sheet has a border but it is so close to the background color that it is hardly noticeable:

```css
.highlight pre,
pre {
    background-color: #f7f7f7;
    border: 1px solid #f8f8f8;
}
```

while the darcula one has a greater difference:

```css
.highlight pre,
pre {
    background-color: rgba(255,255,255,0.04);
    border: 1px solid #999999;
}
```

As a workaround you can add the following corrections to the customized stylesheet to get the same effect.

```css
.highlight pre,
pre {
    background-color: rgba(255,255,255,0.04);
    border: 1px solid rgba(255,255,255,0.05);
}
```

<img width="990" alt="screen shot 2016-03-22 at 12 44 43 pm" src="https://cloud.githubusercontent.com/assets/10299086/13959947/96684ce2-f02c-11e5-93a1-fd9f98e066a5.png">


<img width="992" alt="screen shot 2016-03-22 at 12 45 07 pm" src="https://cloud.githubusercontent.com/assets/10299086/13959932/7f742ef2-f02c-11e5-9fab-af4586e364ca.png">

**Comment by yunti** [comment]
Thanks that workaround fixes it perfectly.  The only other thing with dark theme that doesn't work well is the scroll bar for the preview (sorry I probably should have created a separate issue for each topic - would you prefer me to do that?)  
![screen shot 2016-03-22 at 18 38 18](https://cloud.githubusercontent.com/assets/1826271/13963764/98abcc22-f05e-11e5-845a-9ef24dcf592f.png)

**Comment by vsch** [comment]
Separate issue is not a problem in this case. If the topic warrants then I would open a new issue.

The scroll bars are drawn by JavaFX and WebView. I don't know much about the internal workings of that framework so have no idea how to go about changing its color scheme.

I am sure it is possible so if anyone has information and can point me in the right direction I will look into it.
