### ISSUE TITLE
Selecting readme.md when autoscroll to source is active hang idea 2016.1

### ISSUE THREAD

**Issue by au78** [vsch/idea-multimarkdown#181]
When I select the readme.md in my project and `Autoscroll to Source` is selected, then Idea 2016.1 hangs. I have to force shutdown. This happens only when MultiMarkdown plugin is enabled. Once the plugin is disabled readme.md opens Markdown plugin even if `Autoscroll to Source` is enabled.

`
IntelliJ IDEA 2016.1
Build #IU-145.258, built on March 17, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
`
Let me know what other information is needed to help reproduce and fix the issue.

**Comment by vsch** [comment]
@au78, it appears that the bug is activated by the contents of the readme.md file and not by enabling the Autoscroll to source function which simply causes the file to be opened automatically. 

The parser currently used by the plugin is pegdown which has a few stability issues with some combination of markdown constructs. Unfortunately due to the implementation of this library, even a stack trace that causes the problem does not help isolate the problem in the pegdown parser.

Would it be possible for you to make this file available to me for debugging purposes?

**Comment by au78** [comment]
@vsch Surprisingly, I am now unable to reproduce this issue. I do not know what state was my IDE in that this occurred. And it has occurred multiple times. But this time I am not able to reproduce it. If I am able to then I will share the file with you. 

Meanwhile, if you deem OK then please go ahead and close this bug or I can do it. Let me know what you want to do.

**Comment by vsch** [comment]
@au78, thank you for letting me know. I will mark the issue as cannot reproduce and leave it open.

Has the file been edited since the bug occurred? If this is the case maybe you have a previous version under VCS that will replicate the bug.

**Comment by au78** [comment]
I believe yes... and I have multiple of those. I am going through the history of the changes but it will take some time. Once I locate it, I will share it with you.

**Comment by vsch** [comment]
@au78, thank you. It will be much appreciated.

**Comment by au78** [comment]
I ran into the issue again... Did not modify any readme.md. Had to force shutdown idea. After restart the issue is no longer reproducible. So, the same file failed previously and upon restart works just fine.

I have attached the file. Please rename to .md instead of .txt.

[readme.txt](https://github.com/vsch/idea-multimarkdown/files/186958/readme.txt)

**Comment by vsch** [comment]
@au78, thank you for sticking with it. I'll play with the file to see under what conditions it fails so I can fix it.

**Comment by au78** [comment]
Were you able to reproduce it?

**Comment by vsch** [comment]
@au78, no but I fixed another pegdown parsing bug that would cause hanging during parsing.

I suspect that now this bug is not reproducible. However, I do have this file as part of my sanity test so if it shows up again I will see it.
