### ISSUE TITLE
Add List Item handling on ENTER and BACKSPACE

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#192]
list item handling on <kbd>ENTER</kbd> and <kbd>BACKSPACE</kbd>. <kbd>ENTER</kbd> will add unordered item or 
  ordered item depending on what is preceding caret location. <kbd>ENTER</kbd> and <kbd>BACKSPACE</kbd> will remove empty list 
  items. 

Configuration to enable/disable in Editor > Code Style > MultiMarkdown under `List Items` 

<img width="694" alt="screen shot 2016-04-04 at 11 01 19 pm" src="https://cloud.githubusercontent.com/assets/10299086/14270155/49792108-fab9-11e5-93a0-a0bdfd8d7df6.png">

**Comment by vsch** [comment]
Download and install from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.9.1.zip>

If you have suggestions on improving this feature, please let me know.

**Comment by resure** [comment]
Maybe I'm doing something wrong, but it doesn't work for me.

Settings: http://s3.resure.net/scr/github-issues/idea-multimarkdown-192-settings.png
Version: http://s3.resure.net/scr/github-issues/idea-multimarkdown-192-version.png
Attempt to use feature: http://s3.resure.net/scr/github-issues/idea-multimarkdown-192-usage.gif

**Comment by resure** [comment]
I'm believe it should not create new list after pressing `enter` three times (first for next item, second for removing list marker, third for inserting newline after that).

http://s3.resure.net/scr/github-issues/idea-multimarkdown-192-triple-enter.gif

**Comment by vsch** [comment]
@resure, I will add an configuration option to control creating loose list items via the ENTER key. I will make it disabled by default.

The reason I added it is to be able to create loose list items (spaced by blank lines) via the ENTER key.

**Comment by vsch** [comment]
@resure, download and install from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.9.2.zip>

<img width="692" alt="screen shot 2016-04-05 at 12 23 00 pm" src="https://cloud.githubusercontent.com/assets/10299086/14289524/2af13944-fb29-11e5-9302-90beebd8fd4c.png">

**Comment by resure** [comment]
Now it works like expected, thanks.
