### ISSUE TITLE
Provide option to update MultiMarkdown manually

### ISSUE THREAD

**Issue by petrosp** [vsch/idea-multimarkdown#193]
Hi Vladimir,

The purchase of this plugin was the smartest thing to do; it does exactly what it suposses to do plus many features I would never thought of.

The fact that it is very actively maintained and so often enhanced with further features is not really met from the other plugins out there.

However, it does end up being annoying mostly because we need to have Rubymine restarted.

Is there any plan for a feature to allow us only update when a `minor` version is released rather than a `patch` version? 

Thank you for enriching the `RubyMine` ecosystem with this plugin.

-- Petros

**Comment by vsch** [comment]
Hi Petros,

Thank you for your support and encouraging words.

Yes, I have plans to add a separate update channels for patch and early access preview versions. I will bump the priority for this todo item.

Best regards,


Vladimir.

**Comment by vsch** [comment]
Hi Petros,

Your request motivated me to get this item off my to do list. Separate update is now implemented.

After the next release there will be a separate update channel for patch releases. The default will be minor version updates which I will keep to a monthly or bi-monthly release schedule.

Anyone who wants to have automatic patch releases will be able to do so in Settings/Preferences.

Best regards,


Vladimir.
