### ISSUE TITLE
Reformat paragraphs

### ISSUE THREAD

**Issue by binkley** [vsch/idea-multimarkdown#194]
My muscle memory is trained to use the "Reformat Code" action to fill paragraphs, ala lining up braces & indents in Java (or the `fill-paragraph` function in Emacs).

This happens to a small extent now as my typing overflows the line width and MM wraps to the next line, but this is incomplete when I edit in the middle of lines.  The line I am on will wrap, but other previously wrapped lines in the paragraph do not refill.  I'll get something like:

```
This is a line which will wrap HERE.
This is partially
wrapped left over from earlier wrapping.
```

It would be nice for MultiMarkdown to refill paragraphs on "Reformat Code" action, and when wrapping lines in the middle of paragraphs.

**Comment by vsch** [comment]
@binkley, can you please send me the actual text of the paragraph above. I want to verify that the middle line above does not have 2 or more trailing spaces which Markdown interprets as a HARD BREAK in the line. In this case paragraph wrapping will preserve the break. The 2 spaces before the end of line should also be highlighted to show that these are hard break spaces.

I tried the text above by setting right margin at 40 and deleting the word `which` in the first line:

<img width="392" alt="screen shot 2016-04-12 at 12 18 59 pm" src="https://cloud.githubusercontent.com/assets/10299086/14467315/c365c738-00a8-11e6-8da0-f3b6cf08617e.png">

Typing `which ` in the top line results in:

<img width="376" alt="screen shot 2016-04-12 at 12 19 45 pm" src="https://cloud.githubusercontent.com/assets/10299086/14467337/ddf76660-00a8-11e6-8e0c-0e130b3f66b9.png">

Splitting the line after `partially` and adding another space before the end of line will result in reflowing with a line break after the hard break spaces:

<img width="407" alt="screen shot 2016-04-12 at 12 18 04 pm" src="https://cloud.githubusercontent.com/assets/10299086/14467382/157d24d0-00a9-11e6-924f-c683fc8964aa.png">

Note the highlighting of these hard spaces to that they are visible.

If this is not the case can you please give the procedure to duplicate what happens on your system.

**Comment by binkley** [comment]
Apologies for slow reply.  Overwhelmed at work.

Original:
`This is a long line, long enough that it will wrap when I reach the end at
78 characters.  This is more of the paragraph.  This will also wrap when I
run out of line.`

Edited:
`This is a long line, long enough that it will wrap when I reach the end at
78 characters.  This will also wrap when I
run out of line.`

I've used the IntelliJ "Reformat Code" (reflow) command, but nothing happens.  What I'd like to end up with is this after reformatting:

Proposed:
`This is a long line, long enough that it will wrap when I reach the end at
78 characters.  This will also wrap when I run out of line.`

**Comment by vsch** [comment]
@binkley, I tried the lines you gave and it works in the new patch release 1.4.10.30. Last official release (1.4.10) had a few bugs that are now fixed.

Before formatting:

```markdown
This is a long line, long enough that it will wrap when I reach the end at
78 characters. This will also wrap when I
run out of line.
```

After formatting:

```markdown
This is a long line, long enough that it will wrap when I reach the end at 78
characters. This will also wrap when I run out of line.
```

I spent the last week completely reworking the table and paragraph formatting to improve performance and allow for typing to get ahead of the screen updates as handled by the IDE. This also includes using the PSI to find start and end of paragraphs. The latter is harder than it sounds because the PSI tree elements' offsets into the file get out of sync while 'fast editing' so I had to figure out and debug a correction scheme and gracefully give up auto-formatting if typing gets too far ahead.

https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.10.30.zip See: [Enhanced Features](../wiki/Enhanced-Features) for toolbar buttons and auto formatting descriptions. Full version notes here: [Version](../blob/master/resources/META-INF/VERSION.md)

1. This release gets a lot of bug fixes and comfort features including toolbar buttons to control `wrap on typing` <img width="35" alt="screen shot 2016-04-25 at 12 11 33 am" src="https://cloud.githubusercontent.com/assets/10299086/14773631/59036716-0a7a-11e6-9fd3-e248aa2b9666.png">
    - list item indent/de-indent toolbar buttons <img width="53" alt="screen shot 2016-04-25 at 12 18 16 am" src="https://cloud.githubusercontent.com/assets/10299086/14773685/3ade80da-0a7b-11e6-916a-c90aaa985090.png">
    - options in Code Style to keep image and explicit links at the start of a line for: no files, all files or just ones with Jekyll front matter in the file.
    - file inspection to detect when Jekyll front matter is present and parser option is not turned on.

2. Tables and table formatting got a make over. 
    - Toolbar buttons: <img width="158" alt="screen shot 2016-04-25 at 12 11 40 am" src="https://cloud.githubusercontent.com/assets/10299086/14773632/6a05af9c-0a7a-11e6-8844-b6c9e8daa941.png">
        - toggle `auto-format table` on typing
        - Insert 1x3 table
        - Insert/delete column/row
    - on edit: ENTER inserts an empty row and BACKSPACE deletes empty column/row
    - automatic column insertion if you type after the last column of a table or before the first
    - detection when editing has messed up the table to turn off `auto-format table` and `wrap on typing`

    ![](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/TableAddMissing.gif)

3. Live templates added starting with `.` 

    | Element       | Abbreviation    | Expansion                                               |
    |---------------|-----------------|---------------------------------------------------------|
    | Abbreviation  | `.abbreviation` | `*[]: `                                                 |
    | Code fence    | `.codefence`    | \`\`\` ... \`\`\`                                       |
    | Explicit link | `.link`         | `[]()`                                                  |
    | Footnote      | `.footnote`     | `[^]: `                                                 |
    | Footnote Ref  | `.rfootnote`    | `[^]`                                                   |
    | Image         | `.image`        | `![]()`                                                 |
    | Ref image     | `.rimage`       | `![][]`                                                 |
    | Ref link      | `.rlink`        | `[][]`                                                  |
    | Reference     | `.reference`    | `[]: `                                                  |
    | Table         | `.table`        | <pre><code>`|   |`&#10;`|---|`&#10;`|   |`</code></pre> |
    | Task          | `.task`         | `- [ ] `                                                |
    | Wiki link     | `.wikilink`     | `[[]]`                                                  |

Let me know how what you think of this version and the new features.

**Comment by binkley** [comment]
Wow!  I'm looking forward to trying this out.  Thanks.
