### ISSUE TITLE
Incorrect parsing of compound reference links

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#196]
```markdown
[![License][License-Image]][License-URL] 

[License-URL]: https://github.com/jonaswouters/goclerk/blob/master/LICENSE
[License-Image]: https://img.shields.io/github/license/jonaswouters/goclerk.svg
```

**Comment by vsch** [comment]
@jonaswouters, new issue for tracking this bug. Patch release will be posted here.

**Comment by vsch** [comment]
@jonaswouters, parsing and highlighting fixed for compound links.

Please download and install from disk. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.10.5.zip>

**Comment by jonaswouters** [comment]
Hey @vsch,

Seems like it is working now.

I'll open a new ticket for another bug
