### ISSUE TITLE
Image links that don't end with an extension don't get recognized

### ISSUE THREAD

**Issue by jonaswouters** [vsch/idea-multimarkdown#198]
Image links that don't end with an image extension don't get recognized.

Example

```markdown
[![ReportCard][ReportCard-Image]][ReportCard-URL] 
[![Build][Build-Status-Image]][Build-Status-URL] 

[ReportCard-URL]: https://goreportcard.com/report/jonaswouters/goclerk
[ReportCard-Image]: https://goreportcard.com/badge/jonaswouters/goclerk
[Build-Status-URL]: https://travis-ci.org/jonaswouters/goclerk
[Build-Status-Image]: https://travis-ci.org/jonaswouters/goclerk.svg?branch=master
```

The build image from travis to specify a branch https://travis-ci.org/jonaswouters/goclerk.svg?branch=master
An image link that redirects to the actual image: https://goreportcard.com/badge/jonaswouters/goclerk

Thanks

**Comment by vsch** [comment]
@jonaswouters, issue fixed. 

1. Now image links without extension are assumed to be correct. No error or warning is generated for these links. 

2. Query strings are now stripped from the link address before looking for an extension.

Download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.10.6.zip>
