### ISSUE TITLE
can't support chinese characters

### ISSUE THREAD

**Issue by xuyiyu** [vsch/idea-multimarkdown#203]
I try the title with chinese characters,it cann't be display in the "HTML Preview".

**Comment by vsch** [comment]
@xuyiyu, can you please provide a bit more information.

1. JetBrains Product & Version
2. OS
3. The markdown text for which you are getting wrong results
4. Screenshot of the preview that you are getting, please include the tabs of the editor window so I can see whether it is the split preview or preview tab.

I tried it in IDEA on OS X and Windows. It seems to work:

## OS X - Swing:

<img width="712" alt="screen shot 2016-04-14 at 2 41 09 pm" src="https://cloud.githubusercontent.com/assets/10299086/14539996/047453da-0251-11e6-91b3-3e9ebc5c2870.png">

<img width="708" alt="screen shot 2016-04-14 at 2 41 26 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540010/0e2ee0c0-0251-11e6-9434-c856d6c1dcd4.png">

## OS X - JavaFX:

<img width="711" alt="screen shot 2016-04-14 at 2 41 58 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540019/1921d4b0-0251-11e6-9d3f-6898eec9ce7f.png">

<img width="709" alt="screen shot 2016-04-14 at 2 42 05 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540023/1be067e8-0251-11e6-9f72-5396da1dfcba.png">

## Windows - Swing:

<img width="650" alt="screen shot 2016-04-14 at 2 51 34 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540089/5ba7ba02-0251-11e6-9f34-8069e340a566.png">

<img width="648" alt="screen shot 2016-04-14 at 2 51 44 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540094/5f586ef8-0251-11e6-847c-9d2f9aacb3e1.png">

## Windows - JavaFX:

<img width="651" alt="screen shot 2016-04-14 at 2 46 14 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540067/43a38d14-0251-11e6-807e-18c9edb4bea4.png">

<img width="645" alt="screen shot 2016-04-14 at 2 47 00 pm" src="https://cloud.githubusercontent.com/assets/10299086/14540071/4a06a42a-0251-11e6-9eb9-2aefa8670955.png">
