### ISSUE TITLE
Partial editing of tables can cause Wrap on typing and Auto-format on typing to produce unexpected results.

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#219]
Some partial editing can cause the interpretation of markdown to change. If this happens when auto-format or wrap on typing is enabled it may cause the formatting or wrapping to process more text than is expected.

Solution to detect partial edits that can cause these modes to cause unexpected results and to disable these modes.

**Comment by vsch** [comment]
* Add: logic to disable `wrap on typing` when modifying a table causes it to no longer be a
  valid markdown table
* Add: logic to disable `auto-format table on typing` when modifying a table causes it to no 
  longer have the same number of columns on all rows for editing actions that may be partial 
  modifications and if `Add missing columns` is enable. ie. backspacing or typing back ticks,
  backslash or pipe characters. 
* Add: tooltip when `wrap on typing` or `auto-format table on typing` is automatically disabled.
* Add: logic to disable `wrap on typing` when a block is not terminated by a blank line and the
  following block can be potentially merged into the paragraph.

**Comment by whizark** [comment]
Table formatting produces unexpected results when typing multibytes.
Would you have any plans to fix it?
In case it is difficult to handle multibyes, it would be nice if we could disable auto formatting feature for table.

**Environment:**
* IntelliJ IDEA 2016.1
* Build #IU-145.970, built on April 18, 2016
* JRE: 1.8.0_76-release-b47 amd64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Multimarkdown: 1.4.10 (Enhanced edition)

**Expected result:**
```
| マルチバイト |
|:-----------|
| Cell       |
```

```
| Alphabet   |
|:-----------|
| マルチバイト |
```

**Actual result:**
```
| マルチバイト |
|:-------|
| Cell   |
```

```
| Alphabet |
|:---------|
| マルチバイト   |
```

**Comment by vsch** [comment]
@whizark, thank you for bringing this to my attention. 

The reply is two parts.

1. To disable the auto-formatting of tables go to Editors > Code Style > MultiMarkdown and uncheck the auto-format on typing in the Tables section. Next release has a toolbar button for this and for 'wrap on typing' so you can toggle these without going to preferences/settings.

2. Fixing it would be a harder problem.The complication is that it is font dependent and there is no way to assume that each character is twice as wide as the latin character set. If I assume that they are 2x wide as latin the result would be:

<img width="204" alt="screen shot 2016-04-27 at 12 52 33 am" src="https://cloud.githubusercontent.com/assets/10299086/14842126/6a29ab56-0c12-11e6-9e64-a23d5b0e4026.png">

Which is still not ideal. Taking the actual character width and compensating with spaces to the nearest alignment might be a compromise. I will have to see how difficult it would be or if I can just get the information from the IDE since it already knows the character widths.

It would still create misalignments if there are many columns because errors from each cell on a row would add up unless I go more complex and keep track of character widths instead of just numbers. I will look into it and let you know how I progress.

**Comment by whizark** [comment]
@vsch
> To disable the auto-formatting of tables go to Editors > Code Style > MultiMarkdown and uncheck the auto-format on typing in the Tables section. 

I have missed the settings and I noticed I can also configure other options! :open_mouth: 
After disabling the auto-formatting, I don't have to struggle to edit tables anymore. That's good enough for me.
Thank you for your quick reply :smiley:

**Comment by vsch** [comment]
@whizark, I opened a separate issue for a feature enhancement to use actual character width when doing wrap on typing and table formatting: #223. I will be posting updates there. If you want GitHub to automatically send you update e-mails, just add a comment in that issue so you are added to the participant list.

**Comment by vsch** [comment]
@whizark, pre-releas EAP version with proper wrapping and table alignment based on character widths is now available: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.92.zip

Please provide feedback in issue #223 

Table column width matching is done +/- 1/2 space width of the display font, cumulative for the line. 

Please let me know if you encounter any issues.

Here is the result of wrapping and formatting tables for source given below:

<img width="799" alt="screen shot 2016-05-25 at 11 44 01 am" src="https://cloud.githubusercontent.com/assets/10299086/15546565/5cc7f022-226e-11e6-9e8c-04c6d18fb2ae.png">

Source:

    | マルチバイト |
    |:-----------|
    | Cell       |
    
    | Alphabet   |
    |:-----------|
    | マルチバイト |
    
    マルチバイト マルチバイト マルチバイト マルチバイト tests マルチバイト マルチバイト マルチバイト マルチバイト
    マルチバイト マルチバイト
    
    | 字段名   | 说明                         | 是否必须 | 备注    |
    |---------|-----------------------------|---------|--------|
    | status  | 状态码                       | 是       | String |
    | result  | 内容主体                      | 否       | Object |
    | message | 异常情况的错误信息，供显示给用户 | 否       | String |
    
    异常情况的错误信息, mixed chars width wrapping mode test 供显示给用户 异常情况的错误信息 供显示给用户
    异常情况的错误信息，供显示给用户 异常情况的错误信息，供显示给用户 异常情况的错误信息，供显示给用户
    异常情况的错误信息，供显示给用户

**Comment by vsch** [comment]
Please use update dist 1.6.3.94.zip
