### ISSUE TITLE
Enhanced table editing features

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#220]
New features to make working with markdown tables easier:

Add Toolbar buttons:
* Insert 1x3 table
* Insert row (after current caret line)
* Insert column (before current caret column)
* Delete row (current caret line)
* Delete column (current caret column)
* Toggle ‘auto-format table on typing’
* Add missing columns option in Code Style > MultiMarkdown to add columns so that all rows have the same number of columns. This will result in inserting column by typing after the last column of the table.
* Insert row on ENTER
* Delete empty row or column on BACKSPACE

**Comment by opt123-mm** [comment]
![image](https://cloud.githubusercontent.com/assets/12032777/14764521/1a6f2db8-09fe-11e6-8661-83331ea8a13d.png)
