### ISSUE TITLE
code highlight line number

### ISSUE THREAD

**Issue by aliceinwire** [vsch/idea-multimarkdown#225]
would be nice to can have a option for add line numbers to code blocks

**Comment by vsch** [comment]
@aliceinwire, the plugin uses highlight.js for preview syntax highlighting. 

I will check if highlight.js has this option. If it does then it is already there.

**Comment by vsch** [comment]
@aliceinwire, no it does not support line numbers. http://highlightjs.readthedocs.io/en/latest/line-numbers.html

I will look into having another JavaScript syntax highlighter as an option. If you know of one that you could recommend, please let me know.

**Comment by vsch** [comment]
@aliceinwire, I added [Prism.js](http://prismjs.com/index.html) as a highlighter option, it supports line numbers. Patch release available through EAP update channel or download and install plugin from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.1.2.zip

Make sure you select prism.js as the highlighter and turn off the highlightjs:

<img width="1077" alt="screen shot 2016-10-07 at 10 46 09 am" src="https://cloud.githubusercontent.com/assets/10299086/19194528/da09e564-8c7b-11e6-906f-93a38ea0e11a.png">

<img width="614" alt="screen shot 2016-10-07 at 10 51 38 am" src="https://cloud.githubusercontent.com/assets/10299086/19194595/1afd8fd0-8c7c-11e6-8d6a-f9d46add3028.png">

**Comment by aliceinwire** [comment]
looks so nice 👍
