### ISSUE TITLE
Github-flavored table not rendered properly

### ISSUE THREAD

**Issue by lolmaus** [vsch/idea-multimarkdown#228]
## Source

```
option        | type    | default | security                                             | description
------------- | ------- | ------- | ---------------------------------------------------- | -----------
`text`        | string  |         |                                                      | Markdown content to render
`typographer` | boolean | `false` |                                                      | Whether to enable Remarkable's [typographer](https://github.com/jonschlinkert/remarkable#constructor) option
`linkify`     | boolean | `false` |                                                      | Whether to enable Remarkable's [linkify](https://github.com/jonschlinkert/remarkable#constructor) option
`html`        | boolean | `false` | :warning: [insecure](#warning-security-implications) | Whether to enable Remarkable's [html](https://github.com/jonschlinkert/remarkable#constructor) option
`extensions`  | boolean | `true`  |                                                      | Whether to enable Remarkable's [syntax extensions](https://github.com/jonschlinkert/remarkable#constructor)
`dynamic`     | boolean | `false` | :warning: [insecure](#warning-security-implications) | Whether to enable dynamic template rendering ([see below](#dynamic-template-rendering))
```

## Rendered by GitHub

This is actual rendered content:

option        | type    | default | security                                             | description
------------- | ------- | ------- | ---------------------------------------------------- | -----------
`text`        | string  |         |                                                      | Markdown content to render
`typographer` | boolean | `false` |                                                      | Whether to enable Remarkable's [typographer](https://github.com/jonschlinkert/remarkable#constructor) option
`linkify`     | boolean | `false` |                                                      | Whether to enable Remarkable's [linkify](https://github.com/jonschlinkert/remarkable#constructor) option
`html`        | boolean | `false` | :warning: [insecure](#warning-security-implications) | Whether to enable Remarkable's [html](https://github.com/jonschlinkert/remarkable#constructor) option
`extensions`  | boolean | `true`  |                                                      | Whether to enable Remarkable's [syntax extensions](https://github.com/jonschlinkert/remarkable#constructor)
`dynamic`     | boolean | `false` | :warning: [insecure](#warning-security-implications) | Whether to enable dynamic template rendering ([see below](#dynamic-template-rendering))

## Rendered by MultiMarkdown 

This is a screenshot:

![image](https://cloud.githubusercontent.com/assets/200884/14956397/2f23a082-1088-11e6-8288-3fa439994bb4.png)

**Comment by lolmaus** [comment]
MultiMarkdown version 1.5.0 paid.

**Comment by vsch** [comment]
@lolmaus, The preview does not look like MultiMarkdown. Here is the preview 

<img width="1776" alt="screen shot 2016-05-02 at 10 13 53 am" src="https://cloud.githubusercontent.com/assets/10299086/14956838/c83f275c-104f-11e6-8ed0-7789668e950f.png">

1. If you have other markdown plugins enabled please disable them. Only one markdown plugin can be enabled at a time with the exception of GFM which only provides a preview.

2. Can you please send me a screen shot that includes the editor and split preview in one image. It will be easier to figure out what is conflicting.

3. Make sure table extension is enabled in the parser, if not then tables are parsed as text. However, the preview would still show the `|` pipe characters which your preview is missing.

<img width="879" alt="screen shot 2016-05-02 at 10 28 38 am" src="https://cloud.githubusercontent.com/assets/10299086/14956985/c02f1918-1050-11e6-8d3c-74e93e441410.png">

**Comment by lolmaus** [comment]
Indeed, another IDEA plugin was overriding.
