### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by lolmaus** [vsch/idea-multimarkdown#230]
I'm heavily relying on emoji to format my roadmaps:

![image](https://cloud.githubusercontent.com/assets/200884/14967878/640371b2-10c2-11e6-983d-a011ba92886b.png)

I've paid for MultiMarkdown hoping they would start rendering, but they didn't. :sob:

Please implement emoji support!

PS Useful resource: http://www.emoji-cheat-sheet.com/

**Comment by vsch** [comment]
@lolmaus, it is being worked on right now. I only noticed the lack of emoji translation for the preview in your previous issue. I am finalizing the configurable settings for this option. You will have two options: local image files and GitHub URL. The latter will give exact icons that GitHub uses but is slower and requires an internet connection. The former is using the emoji-cheat-sheet graphics.

I will post a patch release here that you will need to download and install from disk. 

The next official release in about a month. Some users have asked for no more than 1 release a month, some have complained about frequent releases so it is now the official policy.

If you want more frequent updates you will need to select either the "Patch Releases" channel which will have no more than weekly and usually bi-weekly releases. The other is the bleeding edge "Early Access Program", this one I will update with bug fixes and features as they are implemented, which can be updated more than once a week.

<img width="822" alt="screen shot 2016-05-02 at 5 14 40 pm" src="https://cloud.githubusercontent.com/assets/10299086/14968145/681501c8-1089-11e6-8b0b-e1f37fdab624.png">

**Comment by lolmaus** [comment]
Thank you! :beers:

**Comment by vsch** [comment]
@lolmaus, my pleasure and thank you for your support.

**Comment by vsch** [comment]
@lolmaus, patch is ready. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.5.0.2.zip>

No completions, syntax highlighting or error validation for emoji mnemonics for now. It will be added later.

Here is the preview of all of them in one page:

![screenshot_emoji](https://cloud.githubusercontent.com/assets/10299086/14974284/3c2a74a2-10c1-11e6-8fc3-8f9dd6f3dd75.png)

**Comment by vsch** [comment]
Settings also added. Defaults are shown below:

![screenshot_parser_emoji](https://cloud.githubusercontent.com/assets/10299086/14974365/fa6d7914-10c1-11e6-956f-9f7e629179b0.png)

**Comment by lolmaus** [comment]
Using 1.5.0.2, license is active, emoji are enabled -- but they still appears as `:sob:`.

**Comment by vsch** [comment]
@lolmaus, can you give me your example markdown that is not showing up with a screen shot of both the split editor text and the preview so I can try and spot other issues.

Could be a markdown context issue that is missed in the parser. If it was an image URL issue you would not see `:sob:` but a missing image box.

**Comment by lolmaus** [comment]
I'm trying `:sob:` :sob: in a blank file, and it's rendered as `:sob:`.

![image](https://cloud.githubusercontent.com/assets/200884/15033273/9bc55c90-1271-11e6-9918-affc4f4a78ef.png)

![image](https://cloud.githubusercontent.com/assets/200884/15033282/ab79e8ae-1271-11e6-9d4c-0ff2ffd48745.png)

![image](https://cloud.githubusercontent.com/assets/200884/15033299/dcb118d4-1271-11e6-9af5-38bc65abe6ab.png)

**Comment by vsch** [comment]
@lolmaus, I see that you are using the Swing preview. I tested the emoji in Swing but before I added the options in configuration. Looks like I messed up the settings for Swing preview.

Just curious, is there a technical reason you are Swing instead of JavaFX preview? JavaFx gives much better results.

I'll fix the Swing preview for emoji and post a fixed patch.

**Comment by vsch** [comment]
@lolmaus, my bad. The emoji option settings were not passed to Swing preview.

Fixed in patch release 1.5.0.4: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.5.0.4.zip>

<img width="1096" alt="screen shot 2016-05-04 at 10 17 18 pm" src="https://cloud.githubusercontent.com/assets/10299086/15034739/cb9d628a-1246-11e6-8cb3-5a997948d607.png">

**Comment by lolmaus** [comment]
Thank you for emoji support!

Leaving this open for completions, syntax highlighting and error validation for emoji mnemonics.

**Comment by vsch** [comment]
@lolmaus emoji completions, line markers and annotations are done.

New option added in main plugin config: "Show emoji icons as line markers" disabled by default to avoid editor left gutter clutter.

<img width="952" alt="screen shot 2016-05-12 at 9 28 59 am" src="https://cloud.githubusercontent.com/assets/10299086/15216184/2139d5ba-1824-11e6-9f4b-0c8f25a95759.png">


Available as an EAP release <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.5.0.10.zip>

<img width="577" alt="screen shot 2016-05-11 at 10 19 18 am" src="https://cloud.githubusercontent.com/assets/10299086/15184082/d90666c2-1761-11e6-918e-0e5898ad438f.png">

**Comment by lolmaus** [comment]
:bow:
