### ISSUE TITLE
Disable live templates starting with .

### ISSUE THREAD

**Issue by Demurgos** [vsch/idea-multimarkdown#231]
Hi,
I just downloaded the latest version of your plugin which adds support for "live templates starting with `.`".

Is there a way to disable this feature ?

I don't really need this feature, but it is rather intrusive: it often displays suggestions when I'd prefer to press enter to add a newline:
 - When I am just typing some ellipsis `...`
 - When I just want to finish my sentence with a dot `after some code`.

**Comment by vsch** [comment]
@Demurgos, LiveTemplates are a standard IDE feature and can be configured under Live Templates

1. Change the default key to expand all templates. You have this configured to be a space.

2. Enable disable individual templates or groups.

3. Change the expand key on an item basis.

![screenshot_livetemplates](https://cloud.githubusercontent.com/assets/10299086/14997846/c5c4d8f0-114e-11e6-83ac-67d7cd7bc961.png)

**Comment by Demurgos** [comment]
Thank you!
