### ISSUE TITLE
How can I get my preview pane to render my README.md document like it would look on GitHub?

### ISSUE THREAD

**Issue by edgr-sanchez** [vsch/idea-multimarkdown#232]
This is what I'm seeing:

![screenshot](http://i.imgur.com/nOocnU8.png)

**Comment by vsch** [comment]
@edgr-sanchez, it looks like you have the Swing preview option selected. Standard instructions are added below. Please let me know if these don't help you resolve the problem.

To enable JavaFX preview go to Languages & Settings \> MultiMarkdown:

![Screen Shot Settings Preview Browser] 

General installation and configuration instructions to the wiki. See:
[Installation: Configuring The Plugin]

You need to have your environment running on JDK 1.8.0u40 or later for this preview browser to
be available and working correctly. If you have an earlier release IDE for OS X, before build
143, you may need to perform additional steps to get this preview working.
[Troubleshooting Common Problems: JavaFX WebView HTML Preview Not Working]

[Troubleshooting Common Problems: JavaFX WebView HTML Preview Not Working]: https://github.com/vsch/idea-multimarkdown/wiki/Troubleshooting-Common-Problems#javafx-webview-html-preview-not-working
[Screen Shot Settings Preview Browser]: https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_PreviewBrowser.png
[Installation: Configuring The Plugin]: https://github.com/vsch/idea-multimarkdown/wiki/Installation#configuring-the-plugin

**Comment by edgr-sanchez** [comment]
Got it.

Thank you so much for the detailed response!

Thank you,
Edgar Sanchez

_____________________________
