### ISSUE TITLE
Usages of files are not found if the link url encoding did not equal the original file name.

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#233]
Usages of any file's requiring URL encoding would not be found.

**Comment by johnlindquist** [comment]
@vsch I have a file path like

`[import, lang-typescript](../../src/app/+home/home.component.ts)`

and which is red (apparently due to the `+`). So this would be fixed because a `+` would need to be encoded, correct?

**Comment by vsch** [comment]
@johnlindquist, thanks for the head up on this one. It is caused by double url decoding of the file. So the + turns into a space and is not resolved.

I will make a fix and post a patch release here.

**Comment by vsch** [comment]
@johnlindquist, patch release available: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.2.zip>

The link has to be URL encoded. Link completions will do it automatically. 

<img width="985" alt="screen shot 2016-05-18 at 7 51 15 pm" src="https://cloud.githubusercontent.com/assets/10299086/15378588/c1dda0ce-1d32-11e6-9dbf-c7f24b7cdb13.png">

**Comment by johnlindquist** [comment]
@vsch thank you, but unfortunately, I'm using gitbook and it won't compile with the encoded `%2B` instead of a `+`.

**Comment by vsch** [comment]
@johnlindquist, I will add a parser option to not url encode/decode `+` in links. 

I could not find anything about `+` in links or file names with a quick look through the gitbook docs. 

Does the `+` have special meaning in gitbook and are there any other characters that should be excluded from url encode/decode?

**Comment by vsch** [comment]
@johnlindquist, patch release available: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.zip>

This has an option under Languages & Frameworks > Markdown > Parser for GitBook URL encoding which excludes `+` from URL encoding/decoding. With this option turned on encoded and unencoded `+` in the file name will resolve.

It also has a quick fix to create file and directories for unresolved links where directories in the path are also missing.

<img width="961" alt="screen shot 2016-05-19 at 6 12 59 am" src="https://cloud.githubusercontent.com/assets/10299086/15390505/1a1d95d0-1d8a-11e6-9cff-6b619c557c67.png">

**Comment by johnlindquist** [comment]
Wow, amazing! Thank you so much!!!!
Both features confirmed working. :+1:

**Comment by vsch** [comment]
@johnlindquist thank you for bringing it to my attention.
