### ISSUE TITLE
Blurry text in preview mode

### ISSUE THREAD

**Issue by muv** [vsch/idea-multimarkdown#234]
I'm getting blurry text in preview mode.

I [found](http://stackoverflow.com/a/24419312) that I can fix it by adding `-Dprism.lcdtext=false` to `idea.exe.vmoptions`.

Take a close look at screenshots. Click to open them without scaling and then switch between them. First one is how it looks by default, second is with lcdtext set to false.

![multimarkdown-preview-lcdext-true](https://cloud.githubusercontent.com/assets/1251724/15042939/ebb91e58-12d0-11e6-9e20-58cc9c4c2fff.png)
![multimarkdown-preview-lcdext-false](https://cloud.githubusercontent.com/assets/1251724/15042938/ebb11474-12d0-11e6-9bd1-25d3deae2d2a.png)

I also tried the [gfm](https://plugins.jetbrains.com/plugin/7701) plugin which is also based on JavaFx WebView and it had no issue (rendering like on second screenshot).

I'm not sure, maybe my setup is to blame. But if this is reproducible on other machines, perhaps the defaults can be improved. Note this is Windows, Linux may be veery different.

### Environment
MultiMarkdown 1.5.0
Windows 7
IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_60-b27 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

**Comment by vsch** [comment]
@muv, thanks for the heads up. 

Have you tried setting the 'Gray scale rendering' in the preview settings? 

![screenshot_main_licensed](https://cloud.githubusercontent.com/assets/10299086/15046716/39d1e4ca-12af-11e6-85b4-6349acc02c72.png)


I think it does the same thing, it turns off LCD Text font smoothing which does not look good on retina resolution displays. 

I should probably change it to a drop down list box with the two options written out for clarity.

**Comment by muv** [comment]
@vsch I haven't tried 'Gray scale rendering' because it's a *-feature and I'm not willing to register at the moment.

Sorry I forgot to specify my display -- its [Dell P2214Hb](http://accessories.us.dell.com/sna/productdetail.aspx?c=us&l=en&cs=19&sku=320-9791), about 100 PPI so I would not call it 'Retina'.

A drop down list might be a good idea for consistency with IDEA's own settings.

![idea-settings-aa](https://cloud.githubusercontent.com/assets/1251724/15068758/2ba4c45c-1382-11e6-8331-0c7d2a18342c.png)

**Comment by vsch** [comment]
@muv, I will change the configuration to use the IDE setting by default. That would make the most sense for everyone. 

Thank you for bringing this to my attention. I will address this shortly.

**Comment by vsch** [comment]
Next release has the grey font smoothing enable for basic version and the default value is taken from the IDE setting if it is available.
