### ISSUE TITLE
toolbar enhancement

### ISSUE THREAD

**Issue by youyanghuang** [vsch/idea-multimarkdown#236]
could you add more tool buttons(like gitbook editor toolbar) to the toolbar on the top of  the IDEA editor in next version? thanks!

**Comment by vsch** [comment]
@youyanghuang, I will look into it and add the buttons to help edit.

However, if you can send me a screenshot of the toolbar buttons and a list of buttons that you want added, it would make it much faster for me to implement them.

**Comment by youyanghuang** [comment]
@vsch I am glad to see the latest version 1.5.0, much of the [Enhanced Features ](https://github.com/vsch/idea-multimarkdown/wiki/Enhanced-Features) are really what i need!
It is the time to upgrade the plugin, thanks!
