### ISSUE TITLE
Strikethrough in list preview is broken

### ISSUE THREAD

**Issue by atomicpages** [vsch/idea-multimarkdown#237]
The strikethrough feature in 1.5.0 is broken in preview when using the feature inside of an unordered list or an ordered list. In Github we would see:

* sample
* ~~sample~~ 

1. sample
2. ~~sample~~

But in the preview I see this 
<img width="113" alt="screen shot 2016-05-14 at 12 19 39 pm" src="https://cloud.githubusercontent.com/assets/1824291/15270271/67aee0de-19ce-11e6-8713-453ea439e5c0.png">

**Comment by vsch** [comment]
@atomicpages, you are using the Swing preview browser. Swing preview browser has limitations in what aspects of HTML/CSS it implements and strikethrough is one of the unimplemented features. 

JavaFX WebView is a much better option if your JRE allows for it (need 1.8.0u51 or later). Please see [Installation](../wiki/Installation) for selecting

Here is JavaFX

<img width="781" alt="screen shot 2016-05-14 at 4 06 47 pm" src="https://cloud.githubusercontent.com/assets/10299086/15270451/4d29de9c-19ee-11e6-8524-57114eb8caec.png">
 
and Swing:

<img width="782" alt="screen shot 2016-05-14 at 4 08 03 pm" src="https://cloud.githubusercontent.com/assets/10299086/15270454/53a477fa-19ee-11e6-8f30-2cdfcf1bbe77.png">

**Comment by atomicpages** [comment]
Wow! Duly noted. I noticed there was difference between my IntelliJ CE and IntelliJ IDEA which is why I thought this was a bug. Thanks for letting me know though. Cheers!
