### ISSUE TITLE
Insert Link Deletes Text

### ISSUE THREAD

**Issue by opticyclic** [vsch/idea-multimarkdown#238]
Select some text then click Insert Text.

I expect the text to be put in `[]` and `(url)` added after like the GitHub editor does.
Or if you want to be fancy, add a pop up asking for the url like the StackOverflow editor does.

Actual behaviour: `[]()` is inserted overwriting the highlighted text. 

Deleting the text is bad.
Just inserting `[]()` doesn't help people unfamiliar with markdown know where to put the url and where to put the text. See above for GitHub and StackOverflow options.

**Comment by vsch** [comment]
@opticyclic, that is a good idea. I will add it to the to do list.
