### ISSUE TITLE
Add Option For Reference Links

### ISSUE THREAD

**Issue by opticyclic** [vsch/idea-multimarkdown#239]
Markdown supports two style of links: inline and [reference][1].

Can you add the option of creating reference links via the Insert Link button.

Further examples of links
http://stackoverflow.com/editing-help#links
https://daringfireball.net/projects/markdown/syntax#link

[1]: http://markdown-guide.readthedocs.io/en/latest/basics.html#links-reference

**Comment by vsch** [comment]
@opticyclic, you can use LiveTemplates to insert various markdown elements. [Live Templates](https://github.com/vsch/idea-multimarkdown/wiki/Enhanced-Features#live-templates)

Reference links by themselves are just `[]` which the IDE can insert if matching brackets are enabled. A button to insert a pair of brackets will be a significant waste of toolbar real-estate. 

The enhanced version of the plugin provided completions for all elements and conversion between reference and inline links. Allowing you to easily go back and forth between link types.
