### ISSUE TITLE
Incorrect coloring of completed task lists when using capital X.

### ISSUE THREAD

**Issue by Morgul** [vsch/idea-multimarkdown#24]
When writing a task list, I typically complete it with:

`- [X] Some Task`

However, that highlights as a link. However, this highlights correctly:

`- [x] Some Task`

See the following screenshot:

![taskhighlightingbug](https://cloud.githubusercontent.com/assets/770655/9777843/844117a2-572e-11e5-8455-4ba3e560d209.png)

This is obviously a minor issue, but it would be nice if it works, since it does on GitHub.

**Comment by vsch** [comment]
@Morgul, you caught me at a good time. I am prepping a new release which works with 1.8.0u60, older versions of IDEA, etc. And saw a new issue. I'll fix it for the next release. Didn't occur to me to try capital letters for the X.

**Comment by Morgul** [comment]
Awesome! That's great. :)

**Comment by Morgul** [comment]
@vsch Hey, you should put up some sort of a donate button, so I can buy you a beer/pizza/something else. You're doing a phenomenal job with this plugin!

**Comment by vsch** [comment]
Thank you @Morgul. I genuinely welcome any suggestions you may have on what you think would be a good approach. This plugin has really become more than a full-time job and I haven't gotten to the fun part of adding parser enabled functionality, see #12.

**Comment by vsch** [comment]
@Morgul thank you for the encouragement. 

I added a "tipping jar" to the read me page. Nothing ventured, nothing gained. Thought about it and decided to give it a try. I am curious to see how it will work.

**Comment by Morgul** [comment]
@vsch Welp, I threw some $ into the jar; we'll see if anyone else joins in. :)

**Comment by vsch** [comment]
Thank you @Morgul. You are a scholar and a gentleman.
