### ISSUE TITLE
Feature Request: Create Directories and File Intention

### ISSUE THREAD

**Issue by johnlindquist** [vsch/idea-multimarkdown#241]
My scenario:

I'm using your awesome plugin primarily with gitbook.

Gitbook has a `SUMMARY.md` where you layout your chapters/sections that contain `README.md`.

Example:
```md
* [00. New Project](new-project/README.md)
* [01. Hello World](hello-world/README.md)
* [02. First Component](first-component/README.md)
* [03. Events and Refs](events-and-refs/README.md)
```

Instead of manually creating each directory, I'd love to be able to generate the directory *and* the `README.md` from the intention.

**Comment by vsch** [comment]
@johnlindquist, I will add an intention to create the path and file name.

**Comment by vsch** [comment]
@johnlindquist, patch release available: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.6.3.zip>

This has an option under Languages & Frameworks > Markdown > Parser for GitBook URL encoding which excludes `+` from URL encoding/decoding. With this option turned on encoded and unencoded `+` in the file name will resolve.

It also has a quick fix to create file and directories for unresolved links where directories in the path are also missing.

<img width="961" alt="screen shot 2016-05-19 at 6 12 59 am" src="https://cloud.githubusercontent.com/assets/10299086/15390505/1a1d95d0-1d8a-11e6-9cff-6b619c557c67.png">
