### ISSUE TITLE
Github Flavour Support wanted

### ISSUE THREAD

**Issue by xsh6528** [vsch/idea-multimarkdown#259]
Since I want to bold word in in-line code in Github README

I wrote this

```markdown
please add  `add_gtest(`**`your_unittest`**` `**`your_unittest_unittest.cc`**` )`
```

It looks like:

please add  `add_gtest(`**`your_unittest`**` `**`your_unittest_unittest.cc`**` )`
But your plugin do not support yet.

**Comment by vsch** [comment]
@xsh6528, it will be part of the next major release with a new parser. There is no way to add it to pegdown without risking breaking a lot of other parsing rules.

I tried it in the new parser and it works out of the box. I added a test to make sure I don't break it in some future optimization or mod.

### GFM Emphasis Tests

Emphasis around inline code spans

```md
please add  `add_gtest(`**`your_unittest`**` `**`your_unittest_unittest.cc`**` )`
```

```html
<p>please add  <code>add_gtest(</code><strong><code>your_unittest</code></strong><code></code><strong><code>your_unittest_unittest.cc</code></strong><code>)</code></p>
```

Rendered HTML: <p>please add  <code>add_gtest(</code><strong><code>your_unittest</code></strong><code></code><strong><code>your_unittest_unittest.cc</code></strong><code>)</code></p>
