### ISSUE TITLE
Compiler Error in Code Snippet?

### ISSUE THREAD

**Issue by dayFun** [vsch/idea-multimarkdown#264]
Hi All,

My apologies if I'm missing something obvious, but I've went through just about every setting related to the MultiMarkdown plugin and done quite a bit of Googling, but thus far I've come up empty.

I have a Java codefence that the compiler will not stop complaining about. It's a snippet and I'm getting a compiler error saying, "class or interface expected."  The HTML looks great, but I really don't like seeing the  "_x_ errors found" in the editor.

Any suggestions on how I might get around this?

**Comment by vsch** [comment]
@dayFun, you can turn off automatic language injections based on the code fence language. This will disable the syntax errors in fenced code blocks. When auto injection is disable you can use the IDE inject language or reference intention to manually select the injected language.

![screenshot_settings_verbatiminjection](https://cloud.githubusercontent.com/assets/10299086/16540176/bfab7eac-4028-11e6-870d-ff89a4b045d8.png)

**Comment by dayFun** [comment]
Gah, sorry I missed that.

Thanks for the quick response. 

Cheers.
