### ISSUE TITLE
Table of Contents element

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#265]
An updating table of contents element that will render correctly on all markdown parsers.

Basic element:

```markdown
[TOC levels=4]: # "Contents"
```

After the plugin updates the element the resulting element and generated TOC will look like:

```markdown
[TOC levels=4]: # "Contents"
### Contents
- [Release Road Map](#release-road-map)
- [Recent Version History](#recent-version-history)
    - [Latest release is 1.8.0](#latest-release-is-180)
    - [Version is 1.7.1 additions](#version-is-171-additions)
    - [Version 1.7.0 additions](#version-170-additions)
    - [Future feature development](#future-feature-development)
```

Which will render on any parser as:

[TOC levels=4]: # "Contents"
### Contents
- [Release Road Map](#release-road-map)
- [Recent Version History](#recent-version-history)
    - [Latest release is 1.8.0](#latest-release-is-180)
    - [Version is 1.7.1 additions](#version-is-171-additions)
    - [Version 1.7.0 additions](#version-170-additions)
    - [Future feature development](#future-feature-development)

**Comment by blowsie** [comment]
For me, the parser does not render a TOC
![image](https://cloud.githubusercontent.com/assets/308572/24601242/0ecbc4ba-1850-11e7-86d8-61a26c25f93f.png)

**Comment by vsch** [comment]
@blowsie. the table of contents needs to be updated to generate the contents for the tag.

You can either use the update table of contents intention 

![image](https://cloud.githubusercontent.com/assets/10299086/24624893/3a806ec8-187b-11e7-8fe6-573e8eb06544.png)

Or set the Code Style > Markdown options for TOC to update generated text on format and also to format on save so that the TOC will be updated on save.

![image](https://cloud.githubusercontent.com/assets/10299086/24624620/70289e02-187a-11e7-94d4-024359af8fa3.png)

**Comment by blowsie** [comment]
Thank you 😃
