### ISSUE TITLE
4k monitor support

### ISSUE THREAD

**Issue by sbonnick** [vsch/idea-multimarkdown#27]
the "HTML Preview" window does not scale based on resolution or window size. Could this be resolved by using relative sizes instead of hard-coded "px" sizes? my assumption is its being powered by CSS. alternatively, use the font size specified in the IDE for the code window?

**Comment by vsch** [comment]
@sbonnick, I appreciate your feedback and hope you will help me understand what you mean in greater detail.  You are the first one to report an issue having to do with resolution and sizes so your input is invaluable. 

1. Can you please be more specific about how you would expect it to scale? Do you want the fonts bigger/smaller or do you want to control page zoom that affects the whole page?

2. I am running on an iMac Retina 5k and where I could, I added retina support. Most of the time the preview rendering engine handles the resolution differences, so this was not necessary, especially in the new JavaFx WebView based preview.

3. The font sizes and colours are hard coded in the CSS but I have been entertaining the though to bring some of these out into the settings dialog or using the IDE settings. The CSS is customizable, but I know most users don't want to go "flea hunting" and tweak their own CSS. Would you want the font family and size that you use for the IDE UI to be used for rendering HTML preview?

4. Is it the old preview or the new JavaFx preview window? You can see which one is being used in <kbd>Settings > Other Settings > MultiMarkdown</kbd> if it is the old swing preview you will have the `Use Old Preview` checkbox selected.

I do hope you have the time to help me get this resolved to your satisfaction.

Vladimir.

**Comment by sbonnick** [comment]
Hi Vladimir, 

1. right now, the display is unreadable, as the whole rendering looks about the size of a playing card (on a 19 inch monitor). So i would expect the whole page to zoom - which would increase font size, width of div container, etc... I know when I first installed intellij i had to adjust the IDE UI font to be able to read any code as it was super tiny. 

2. I am using a windows 8.1 based PC with 3840 x 2160 resolution.

3. I think pulling from the IDE UI would be a good idea. reuse is generally a good thing for usability. The alternative is some sort of auto-scale based on rendering window width. but perhaps not the greatest

4. this is not checked.so i should be using javaFX

**Comment by sbonnick** [comment]
i did take a quick look at the Css override. and my thoughts was to change the font form "px" to "em" OR to a larger size. but then the container width would also need to be increased.. not sure if there are sub divs that may require a width change too...

**Comment by vsch** [comment]
Thanks for the quick reply. I suspected that it is a Windows issue and I suspect the old preview would be hell to make work with retina on Windows. Windows support for retina is still iffy in Windows 10.

I am sure IntelliJ goes through hoops to support retina on windows.

Yes, you should be using the new preview if you are able to have your IDE boot JDK configured for non-Jetbrains JDK 1.8 preferrably 1.8.0u40 or newer. instructions on doing this are in the wiki <https://github.com/vsch/idea-multimarkdown/wiki/Installation> even if the WebView in the current implementation still does not look right it is not a problem. It has a zoom setting and I will fire-off a new release for you which will let you tweak that value to your liking.

**Comment by vsch** [comment]
I would have to make a new CSS for the old preview that doubles all pixel sizes. This is the only sure way to take care of it. I will probably still do this, even if the new preview works for you because there may be others who don't have the option of running on JDK 1.8 and need retina resolution supported.

I'll get on both of these issues right away so either way you will have it solved.

**Comment by sbonnick** [comment]
OK perfect. I will try this out and let you know.

**Comment by vsch** [comment]
Thanks. I will give you a link for a new download as soon as I have it ready with page zoom for the new preview.

**Comment by vsch** [comment]
@sbonnick, page zoom implemented for the JavaFx WebView based preview tab. Set Zoom 0.3 - 3.0 in 0.01 increments, in Settings > Other Settings > MultiMarkdown, only available if `Use Old Preview` is not selected.

download this quick fix release from <https://github.com/vsch/idea-multimarkdown/blob/master/dist/idea-multimarkdown.1.1.4.2.zip?raw=true>

**Comment by sbonnick** [comment]
zoom worked great! Is it possible to go to maybe 5 or something? 3 works perfect for me, but I can see people with a larger resolution needing a large zoom factor.

**Comment by vsch** [comment]
I'll change the range to 0.2 to 5 in the next release. I thought 3 was overkill but then on the mac I don't need any zoom.

**Comment by sbonnick** [comment]
Thanks Vladimir. Awesome work!

**Comment by vsch** [comment]
My pleasure.
