### ISSUE TITLE
List and wrap not playing together

### ISSUE THREAD

**Issue by GordonFerguson** [vsch/idea-multimarkdown#270]
Hi, I use the navigator enhanced version with PhpStorm and 
the latest version 1.8.1 is giving me problems.
I want to create a list, but the word wrap seems to take
over and move the intended list items under an
existing item. I've tried the various wrap options but to no avail.
I was able to create lists with earlier versions.

**Comment by vsch** [comment]
@GordonFerguson, to get around the bug, temporality turn off wrap on typing using toggle wrap on typing  toolbar button ![wrap_on_typing](https://cloud.githubusercontent.com/assets/10299086/16782128/3e44d59e-484c-11e6-9186-70ed35a92205.png). I added it for that purpose. You can turn it on again right after you are done.

Previous versions used heuristic parsing of document text to figure out the markdown context and what to do,  which had issues with recognizing proper markdown in some cases. 

Now I use the PsiTree of the parsed markdown source. The current version traded off those limitations for having to deal with the fact that the PsiTree is not updated yet when the character handler is called and I need "predict the future PsiTree" based on context and character typed. This means I need to tweak problem cases to do the right thing.

If you could give me a bit more details on the use case I can address it.

**Comment by GordonFerguson** [comment]
Thanks for the quick work around, my afternoon was much more pleasant with that.
I've not ferreted out a stable scenario yet, but I'll let you know.

**Comment by vsch** [comment]
@GordonFerguson, no rush. I have addressed over a dozen cases that I have encountered but I am always on the lookout for these.
