### ISSUE TITLE
Feature request: Auto create links when pasting Evernote links 

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#276]
Auto create links when pasting Evernote links 

Such copied links contain both test and URL but currently the editor gets the url only at this time.

**Comment by SemanticBeeng** [comment]
It would be a killer to have full integration with Evernote and Confluence.

For example, when typing [[ + Ctrl Space the user would have the chance to pick a link from both Evernote and Confluence.

Both of these technologies have APIs and such integration is doable.

Of course the plugin would have to allow one to provide credentials for login to both Evernote and Confluence.

**Comment by vsch** [comment]
@SemanticBeeng, EAP update with HTML to Markdown conversion is available in EAP release. Now you can convert HTML content copied from a browser to Markdown simply by pasting it into a markdown document. When you paste into Markdown document, the available clipboard content is checked for text/html and if available this is converted to markdown and used for the paste. No selection stuff. Most of the time you get what you want. On those occasions where HTML is desired to be pasted in Markdown then you will need to paste it into a scratch file and copy to clipboard so that clipboard content is plain text.

This also allows you to copy a link from Evernote or any other application that supports text/html mime format and have it converted to a markdown link on paste.

I implemented HTML to Markdown parser in the [flexmark-java](https://github.com/vsch/flexmark-java) project so this functionality is available in OSS if desired. 

Now you can search on Google for reference information, then just copy the HTML table from the search results page and paste it into Markdown to get a markdown table or any other content. 

When I got the link pasting working and tried it generic HTML content I was blown away. For some reason I never extrapolated from links to generic HTML to Markdown conversion. Did it manually like a peasant many times before.

Thank you for triggering the process to a great feature for the plugin.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
