### ISSUE TITLE
Inject Language

### ISSUE THREAD

**Issue by kiru** [vsch/idea-multimarkdown#279]
If I have a string in Java, like this:

String sql = "select * from MyPerson";

I can inject a language, and mark that string as SQL. So I can directly run that SQL from there.

In Markdown, when I've a code block like this:
```
select * from MyPerson;
```

Is it possible to inject a language, and say intellj that the code block is of type SQL.

**Comment by vsch** [comment]
@kiru, language injections are only supported in the enhanced edition. Either through manual injection for indented code blocks and automatic injection for fenced code blocks, based on the string following the opening marker, if the option is enabled:

![screenshot_settings_verbatiminjection](https://cloud.githubusercontent.com/assets/10299086/17271778/5c0b8afe-5653-11e6-88cc-cd6a1865ee79.png)

**Comment by kiru** [comment]
@vsch Thank you for the help. I was not aware of that feature.
