### ISSUE TITLE
Print HTML Preview

### ISSUE THREAD

**Issue by kiru** [vsch/idea-multimarkdown#283]
Is it possible to print the html preview?

I've tried to export the markdown file as HTML ( File -> Export to HTML ), but the result was the export of the markdown source.

**Comment by vsch** [comment]
@kiru, the export as HTML is IDE implemented function to export the source of the currently open file.

To export converted markdown select the HTML Text preview then select the HTML and copy it to a scratch file.

The HTML text comes in two varieties: html used for creating the preview with all the extras needed to render the HTML, or plain HTML as converted by the parser from markdown without any fluff needed for preview rendering.

**Comment by CreamyCookie** [comment]
@vsch I don't really understand you explanation. Copying the text from the HTML Preview tab doesn't seem to contain any HTML. I'd also love a "Open in browser" feature.

**Comment by vsch** [comment]
@CreamyCookie, it only works in the enhanced version which requires a license or a trial license.

## Split Layout Control

![Screen Shot Toolbar](https://github.com/vsch/idea-multimarkdown2/wiki/img/ScreenShot_toolbar_layout.png)

| Button                                                                            | Action                                 | Notes                                               |
|-----------------------------------------------------------------------------------|----------------------------------------|-----------------------------------------------------|
| ![Editor Preview](../raw/master/resources/icons/layout/Editor_preview%402x.png)   | Show editor and preview                |                                                     |
| ![Preview Only](../raw/master/resources/icons/layout/Preview_only%402x.png)       | Show preview only                      |                                                     |
| ![Editor only](../raw/master/resources/icons/layout/Editor_only%402x.png)         | Show editor only                       |                                                     |
| ![Html Preview](../raw/master/resources/icons/layout/Html_preview%402x.png)       | Show HTML preview                      |                                                     |
| ![Html Modified](../raw/master/resources/icons/layout/Html_modified%402x.png)     | Show HTML text used for browser        |                                                     |
| ![Html Unmodified](../raw/master/resources/icons/layout/Html_unmodified%402x.png) | Show plain HTML as generated by parser | Plain HTML as converted from markdown by the parser |

Actions available but not in the toolbar. Can be mapped to shortcuts.

| Non Toolbar Actions                                                                           | Action                | Notes                                                             |
|-----------------------------------------------------------------------------------------------|-----------------------|-------------------------------------------------------------------|
| ![Cycle Editor Preview](../raw/master/resources/icons/layout/Cycle_editor_preview%402x.png)   | Cycle split layout    |                                                                   |
| ![Toggle Editor Preview](../raw/master/resources/icons/layout/Toggle_editor_preview%402x.png) | Toggle Editor Layout  | toggles preview on/off                                            |
| ![Cycle Html](../raw/master/resources/icons/layout/Cycle_html%402x.png)                       | Cycle preview content | cycle through preview, modified and unmodified HTML preview types |

**Comment by vsch** [comment]
HTML Export available in Enhanced version via the plugin EAP channel update.

Also print JavaFX HTML Preview is in dev mode. If anyone is interested in trying it out let me know. I will enable the dev feature on your license or trial license.

**Comment by vsch** [comment]
Print HTML Preview for JavaFX WebView preview browser added to plugin EAP update channel.

**Comment by kiru** [comment]
@vsch Thank you for your effort. Print function works perfectly.
