### ISSUE TITLE
There's always a horizontal scrollbar

### ISSUE THREAD

**Issue by CreamyCookie** [vsch/idea-multimarkdown#289]
When I change the size of the editor (smaller or bigger), the scrollbar appears and disappears over and over (it's periodic). When I close and reopen it when the scrollbar wasn't displayed, the horizontal scrollbar reappears.

Editor is set to soft-wrap.

![screenshot from 2016-08-18 19-32-01](https://cloud.githubusercontent.com/assets/3063858/17783935/afc00db0-657a-11e6-8439-530bb7a1bb01.png)

I'm on Ubuntu 16.04 using:

```
IntelliJ IDEA 2016.2.2
Build #IC-162.1628.40, built on August 16, 2016
JRE: 1.8.0_76-release-b216 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by vsch** [comment]
@CreamyCookie, the plugin does not control the scroll bar of the editor. It is controlled by the underlying editor.

I cannot duplicate this behaviour.

Can you try the Markdown Support plugin from JetBrains. Markdown Navigator uses the code from that plugin for its split editor. If the JetBrains plugin exhibits the same behaviour then it is a JDK or IDE issue.
