### ISSUE TITLE
I get null when opening project.

### ISSUE THREAD

**Issue by MarinKacaj** [vsch/idea-multimarkdown#290]
I got a bug popup from IntelliJ 14.1.4 when opening a project previously generated by this command:
`mvn archetype:generate  ^
    -D archetypeGroupId=org.apache.isis.archetype ^
    -D archetypeArtifactId=simpleapp-archetype ^
    -D archetypeVersion=1.13.0 ^
    -D groupId=com.mycompany ^
    -D artifactId=petclinic ^
    -D version=1.0-SNAPSHOT ^
    -D archetypeRepository=http://repository-estatio.forge.cloudbees.com/snapshot/ ^
    -B`
The message on IJ's popup was just this: `null`

Maven version: 3.3.3
Java: 1.8.0_60
OS: Windows 10

**Comment by vsch** [comment]
@MarinKacaj, I tried opening a new project created by the mvn command you used in IDEA 14.1.4 and did not receive any errors.

Is this a one type error or does it happen every time you open the project?

**Comment by MarinKacaj** [comment]
It happened only the first time.I don't know how IJ might be affected, but the project was previously generated in the cmd line.IJ was already open on another project and then, when I switched to the new one (the maven-generated one) on the same window, the report came up.

    On Wednesday, August 24, 2016 4:05 PM, Vladimir Schneider <notifications@github.com> wrote:
 

 @MarinKacaj, I tried opening a new project created by the mvn command you used in IDEA 14.1.4 and did not receive any errors.Is this a one type error or does it happen every time you open the project?—

**Comment by vsch** [comment]
@MarinKacaj, there are some differences in initialization sequence and timing depending on whether the project is opened when IDE starts up or whether it is opened after a project is closed. Could be related to this.

**Comment by defconx** [comment]
As a data point, I was experiencing this about once out every 5 times I opened IJ and always after an update of IJ. I did an "Invalidate Caches / Restart" with plugin disabled and it has been working with no issues since then. I am using JetBrains Toolbox and the migration from non-toolbox IJ installation to ToolBox didn't go well, I lost a lot of settings. So it may be related to toolbox?
