### ISSUE TITLE
ENTER key stops working

### ISSUE THREAD

**Issue by simarsenault** [vsch/idea-multimarkdown#292]
If you open the attached file in IntelliJ, the `ENTER` key stops working (within the file).

[BUG.zip](https://github.com/vsch/idea-multimarkdown/files/445828/BUG.zip)

IntelliJ 15.0.6
Markdown 2.0.0 (Enhanced)

**Comment by vsch** [comment]
@simarsenault, the bug is the same as #286 and a fix is available in the latest patch release 2.0.0.8 available from the EAP channel in Languages & Frameworks > Markdown or direct download https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.8.zip

**Comment by simarsenault** [comment]
Glad to hear it was already fixed :smile: 

Thank you!
