### ISSUE TITLE
Cannot adjust settings for "Explicit Link"

### ISSUE THREAD

**Issue by awood** [vsch/idea-multimarkdown#293]
When I attempt to adjust the color settings of "Explict Link", the settings are not respected.  Additionally, clicking on the Explicit Link section in the preview doesn't actually link back to the correct entry in the settings list.

I am using a custom color scheme and I have made sure that the parent is set to Darcula (as you described in your Common Issues document).

![recorded](https://cloud.githubusercontent.com/assets/17975/18140539/fc428fec-6f83-11e6-8811-dbe5c6b53053.gif)

In the attached screenshot you can see that clicking on other tokens in the preview pane moves the list to the correct entry but Explicit Link does not.  Additionally you can see that setting for Explicit Link (#6C71C4) does not show up in the preview.  In actual Markdown documents, I'm having the same problem where the setting is not being used.

Any assistance you could provide would be appreciated!

**Comment by vsch** [comment]
@awood, the explicit link colors and a few others have dynamically generated attributes which create a mix of the final color between the attribute and context color. For example, an explicit link in a table cell will create a dynamic attribute which combines row/col and link to create a new attribute which is a mix of these.

The IDE only generates a subscription notification to color Scheme changes, not to color changes within the color scheme. It does make a call to editors to notify of the color change but I did not find a way of trapping these. This means that changing colors for attributes which have dynamically derived attributes will not be reflected until a schema change or restart of the IDE.

As a work around, change the Scheme, press OK. Reopen settings and change the Scheme back to the one you want to use. After a scheme change the dynamic attributes are re-computed.

**Comment by awood** [comment]
Unfortunately changing the scheme and changing back didn't work for me.  It sounds like this is an issue in IDEA (I myself am using PyCharm).  Maybe it's worth filing a bug with JetBrains?  I would vote for the bug if you file it :smiley: Thanks for your help!

**Comment by vsch** [comment]
@awood, the issue is caused for a different reason. Sorry, I did not clue in that it was the unlicensed version which handles syntax highlighting slightly differently. Licensed version has different colors for individual parts of the link, the unlicensed version only has one and it is `Link` not `Explicit Link`.

Click on the link in the sample doc or on the `Link` attribute in the list then change the color.

<img width="959" alt="screen shot 2016-09-02 at 7 54 04 pm" src="https://cloud.githubusercontent.com/assets/10299086/18221096/27d8e1d2-7147-11e6-8843-599a90d1a5f4.png">

**Comment by awood** [comment]
> Sorry, I did not clue in that it was the unlicensed version which handles syntax highlighting slightly differently. Licensed version has different colors for individual parts of the link, the unlicensed version only has one and it is Link not Explicit Link.

Interesting.  I'm actually using the unlicensed version but do not see "Link" in the token list.  I'm running 2.0.0 installed directly via PyCharm.  Maybe I should try a trial license and see if that changes things?

**Comment by vsch** [comment]
@awood, the fact that Link is not showing up but Explicit Link does is a bug. I will be releasing a patch release shortly that addresses this issue. I'll post a link here.

**Comment by vsch** [comment]
@awood, patch available through EAP update channel or download: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.0.0.10.zip

Download and install plugin from disk.

**Comment by awood** [comment]
Awesome!  I will be registering my copy shortly!  Thanks for the help on this.
