### ISSUE TITLE
Syntax highlighting is gone

### ISSUE THREAD

**Issue by natros** [vsch/idea-multimarkdown#3]
For some reason the syntax highlighting is not working for me. I have all the options enabled.

![preferences](https://cloud.githubusercontent.com/assets/4996289/9450407/58fe3420-4aa0-11e5-8763-3c159e78d38a.png)

IJ-141.1311.1 (14.1.5 EAP)
Plugin version 1.0.14
```
java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

**Comment by vsch** [comment]
You don't need the last 3 options: Force Item Para and the two Suppress. However, that is not the issue.

I am looking into it. I can duplicate it on 14.1, while it works fine on 14.2.

**Comment by vsch** [comment]
It was two things but which one I could not isolate so make sure you do both:

1. if you have Markdown plug-in installed you need to uninstall it. Not just disable it. The two conflict.
2. You need to download a new version of the plugin. I just uploaded it. I made a change in plugin.xml that is required for 14.2, but 14.1 apparently still looks for the old config attribute. So I put both. It works on both 14.1 and 14.2 that I tried.

Please let me know if it solved your highlighting issue.

**Comment by vsch** [comment]
You may need to close file tabs and re-open or modify the Markdown file to have it re-parsed for syntax highlights.

**Comment by natros** [comment]
After the update it's working again.

Thanks.

**Comment by vsch** [comment]
Thank you for letting me know it was broken, in the first place.
