### ISSUE TITLE
Preview and Editor & Preview grayed out

### ISSUE THREAD

**Issue by HWiese1980** [vsch/idea-multimarkdown#304]
I've just installed the plugin to my PyCharm 2016.2.2 and can't figure out how to enable the Markdown preview. The two buttons related to the preview are both grayed out. Is that a bug? Or what am I doing wrong?

Thanks

**Comment by vsch** [comment]
@HWiese1980, the basic plugin has a HTML Preview Tab.

<img width="579" alt="screen shot 2016-09-16 at 2 19 11 pm" src="https://cloud.githubusercontent.com/assets/10299086/18596810/0b5e42fe-7c19-11e6-90ee-ff3b67a77001.png">

Selecting it show the HTML Preview:

<img width="579" alt="screen shot 2016-09-16 at 2 19 28 pm" src="https://cloud.githubusercontent.com/assets/10299086/18596819/15f6d8a2-7c19-11e6-9c24-36981ac5486f.png">

Enhanced version requires a [license](https://vladsch.com/product/markdown-navigator/buy). You can get a [trial license](https://vladsch.com/product/markdown-navigator/try) to try out the enhanced version before purchasing.

Enhanced version [feature comparison](https://vladsch.com/product/markdown-navigator) lists differences between the two versions.

The enhanced version has split editor preview and toolbar editing actions, wrap on typing, table formatting and markdown document formatting.

<img width="1197" alt="screen shot 2016-09-16 at 2 21 16 pm" src="https://cloud.githubusercontent.com/assets/10299086/18596944/9cc173f6-7c19-11e6-8d0e-ce9295b023f6.png">
