### ISSUE TITLE
Wrapping selected text with various styling by typing it

### ISSUE THREAD

**Issue by neochief** [vsch/idea-multimarkdown#310]
It would be awesome if you could integrate following scenario to plugin. Here's how this works in Sublime Text:

1. Select a word.
2. Press *
3. The word becomes enclosed with *
4. Press * again
5. The word becomes enclosed with **

This should also work for _ , ` and other marks. Currently, a word just gets replaced with *.

It is super handy! You can try it in Sublime Text with this plugin https://github.com/SublimeText-Markdown/MarkdownEditing

**Comment by vsch** [comment]
@neochief, wrapping/unwrapping bold/italic is available via ⌘B/⌘I on Mac and Ctrl+B/Ctrl+I on Windows, respectively.

Wrapping selection on * or _ is a good suggestion. The IDE handles the deletion of the selection before invoking the registered TypedHandlerDelegate provided by the API. I will look into adding this functionality via another mechanism. 

Typing `*`, `_` or `~` will add a closing counterpart when typing if the "smart edit" options are enabled for the corresponding characters.

![smartedit](https://cloud.githubusercontent.com/assets/10299086/18877558/a03be9c8-849b-11e6-8835-7626d4ee98be.gif)

<img width="1063" alt="screen shot 2016-09-27 at 10 09 33 am" src="https://cloud.githubusercontent.com/assets/10299086/18877480/6185136c-849b-11e6-9c31-926bd1020678.png">

**Comment by neochief** [comment]
Thanks, it looks that I'll need to change the habit :)
