### ISSUE TITLE
Soft wraps on right margin

### ISSUE THREAD

**Issue by neochief** [vsch/idea-multimarkdown#311]
Hey Vladimir!

Currently if you enable soft wraps in phpstorm, the markdown gets wrapped at the end of visible line (IDE window edge).

Do you know, is it possible to get the soft wraps for markdown to wrap text after right margin? I'd like to get the same effect as with your setting "break on typing", but with soft wraps.

Hard wraps don't work for me, because I use 3rd party validation software, which treats hard line endings as end of the sentence.

**Comment by vsch** [comment]
@neochief, soft wraps are implemented and controlled by the IDE. This feature has been requested before, #75.

I agree that soft wrap column should have an option to be controlled separately from the window size. I find that having the text wrap at the right edge of the text window is not practical if the window is very wide.

You should open a feature request on [YouTrack](https://youtrack.jetbrains.com/issues). If there is enough user support for this then it might get added to the IDE.

**Comment by neochief** [comment]
Too bad, I thought there might be some workaround. Well, thanks anyway Vladimir, you're doing great job!

**Comment by vsch** [comment]
@neochief, I am sure there is a way to do this but I think it requires changes to the soft wrapping model of the editor in the IDE core that implements the soft wrapping.

I will take a look at the idea-community project to see if I can implement the changes then make the patch available with the feature request on YouTrack. Having the implementation will probably shorten the adoption time of the feature.

**Comment by vsch** [comment]
@neochief, good news. While looking into how multiple carets are implemented I stumbled into the soft wraps implementation. After a couple of hours perusing the code to see if I can propose a patch to JetBrains for the feature, I found what I needed was right there, only minor mods required. The API is awesome! It usually it takes 20 lines of code but to find what, where and when to plug in can take hours if not days.

To make a long story short, I have the option to implement soft wraps on right margin for markdown implemented. It will be in today's EAP release and in the next official release scheduled for Nov 14.

Soft wrap at right margin off:
<img width="859" alt="screen shot 2016-11-06 at 11 39 03 am" src="https://cloud.githubusercontent.com/assets/10299086/20039699/40e43d8c-a416-11e6-8e3c-3551a0d68c0a.png">

Soft wrap at right margin on:
<img width="862" alt="screen shot 2016-11-06 at 11 40 33 am" src="https://cloud.githubusercontent.com/assets/10299086/20039705/5dd8a3c4-a416-11e6-8381-6dbb6e09ba41.png">

<img width="1013" alt="screen shot 2016-11-06 at 11 56 37 am" src="https://cloud.githubusercontent.com/assets/10299086/20039786/1e48577a-a418-11e6-839f-e211c730207f.png">

**Comment by vsch** [comment]
@neochief, Available via plugin EAP update channel.

**Comment by neochief** [comment]
Hey Vladimir! I absolutely feel your pain (and also happiness), since I created an IDEA plugin myself, being non-Java developer. That [thing](https://plugins.jetbrains.com/plugin/8412) was the most research-challenging work I ever had. I remember spending days in a frustration over non-documented APIs of IDEA. Ah, sweet tears of nostalgia :D

But, anyway, thanks so much for the update! Glad that you kept this request on the radar.

**Comment by vsch** [comment]
@neochief, you are welcome.

I have a motto now for plugin functionality: "It will probably take only 10 lines of code but it will take indeterminate number of days to figure out which 10 lines"

**Comment by neochief** [comment]
Yeah, totally. Sometimes I wonder whether there is a person in JetBrains who knows all of their code base or is it too big for one human brain to contain.

**Comment by vsch** [comment]
From my experience with their guru's they definitely have some three frontal lobed developers. 

It is impossible to know it all but based on the complexity of what is there, someone had to fit enough of it into their head to work it out and create meaningful abstractions.

Having a high level map of available functionality and where to look for it is the most piece of information. I suspect the great ones at JetBrains have a very good satellite view of the code base. 

Takes time to wrap your head around it but I find it to be worth the effort. I have an obsessive need to hone and tweak my tools. These IDEs give me that option in the event that someone has not done it already.
