### ISSUE TITLE
Changing fonts causes WebStorm to freeze

### ISSUE THREAD

**Issue by oliversalzburg** [vsch/idea-multimarkdown#313]
Please see https://youtrack.jetbrains.com/issue/WEB-23661 for details

> What steps will reproduce the problem?
> 1. Have Fira Code as the selected font, with font size 14, line spacing 1.0.
> 2. Open the settings and change the font size to 12, line spacing 1.1
> 3. Click Apply

**Comment by vsch** [comment]
@oliversalzburg, thank you for the report. Seems that the behaviour has changed. I will add a check to ensure that the function is not re-entered to prevent infinite recursion.

**Comment by vsch** [comment]
@oliversalzburg, confirmed that the recursion appeared in version 2016.3 EAP and did not occur in 2016.2.

Patch available through EAP update channel or download and install from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.1.4.zip
