### ISSUE TITLE
Number of columns in right margin

### ISSUE THREAD

**Issue by allejo** [vsch/idea-multimarkdown#318]
Is there a way for this plugin to respect or at least set the number of columns the right margin should be at? In my PhpStorm settings, `Editor > Code Style > Right margin (columns)` is set to 120 but any markdown file opened has the right margin set to 80 columns.

**Comment by allejo** [comment]
Derp... `Editor > Code Style > Markdown` has a "Right margin" setting. Sorry!

**Comment by vsch** [comment]
@allejo, I was about to answer but you found the setting.

You can always select the "default" check box if you want Markdown right margin to track the general right margin setting.

The plugin can also override the IDE default for "Soft Wraps" and overrides white space trimming at end of lines for Markdown documents. Found in preferences (settings on Win/Linux) Languages & Frameworks > Markdown.

There are a ton of customizations in the plugin. If you find something missing please feel free to make a suggestion.

**Comment by allejo** [comment]
Oh thanks for the note about "Soft Wraps" actually; I was wondering about that for a while now and I hadn't noticed that that option existed. Thank you 👍

**Comment by vsch** [comment]
@allejo, a summary of all the configuration settings and their location is shown in [Wiki: Installation ConfigurationSettings](https://github.com/vsch/idea-multimarkdown/wiki/Installation#configuration-settings)

The screenshot in the wiki is for the upcoming release which has Languages & Frameworks > Markdown > Preview settings moved into its own sub-section from the main section and 3 new configuration sections: HTML Export, Rendering, Profiles which do not exists in the current version.

Everything else matches the current version. It is a screenshot and a half page of text that will show give you a quick reference for what and where of configuration.
