### ISSUE TITLE
In preview, mutliparagraph list items do not keep order but default to 1.

### ISSUE THREAD

**Issue by Dbz** [vsch/idea-multimarkdown#321]
Hello,

List items with paragraphs between them all default to starting at `1.` in preview mode. A great feature of markdown is able to start all list items with the same number (`1.`) in order to make editing your document and moving around list items easy. However, when previewing, it appears as if the markdown will not show correctly even though it does. See this example markdown:

``` markdown
1. First item

  paragraph of text   

1. Second item

  paragraph of text
```

Each item is defaulted to `1.` even though the second item should be `2.`

This is how the same markdown actually renders:
1. First item
   
   paragraph of text   
2. Second item
   
   paragraph of text

---

It may also be worth noting that this behavior is also in github's language fencing parser- I incorrectly made an [issue](https://github.com/github/linguist/issues/3309) there; subsequently, it's not a bug for the parser because it's not supposed to process the text rather than display the actual code. Here the preview and html preview tabs are supposed to process the text, so it does appear to be a bug.

**Comment by vsch** [comment]
@Dbz, markdown comes in many dialects and the biggest difference between them is how they interpret indent spaces.

By default the plugin uses the "Fixed 4 Spaces" as an indentation for sub-lists and list item paragraphs. Which means that you need to indent paragraphs contained in list items by 4 to 7 spaces. The fixed 4 spaces indent gives the most consistent rendering across most parsers.

If you want closer to GitHub style interpretation you need to change the parser option:

<img width="829" alt="screen shot 2016-10-30 at 9 00 10 am" src="https://cloud.githubusercontent.com/assets/10299086/19836728/d60d1290-9e7f-11e6-9edb-e54c211d0c1c.png">

The rendering will be as you expect:

<img width="1091" alt="screen shot 2016-10-30 at 9 06 17 am" src="https://cloud.githubusercontent.com/assets/10299086/19836740/231b48a4-9e80-11e6-8749-100a1987244d.png">
