### ISSUE TITLE
Missing configuration options Mac Sierra

### ISSUE THREAD

**Issue by neoaddix** [vsch/idea-multimarkdown#326]
I seem to be missing some configuration options in my installation (see screenshot). I'm Using:

Plugin version 2.1.1 (enhanced version)
IntelliJ Build #IU-162.2228.15, built on October 14, 2016
Mac OS with Sierra

I'm missing the options:
- Preview 
- HTML export
- Link map
- Rendering

I removed all other Markdown plugins and also reinstalled the Navigator plugin to no avail

Thanks

Jeroen
![markdown-navigator-configuration](https://cloud.githubusercontent.com/assets/22679396/19931020/42967310-a10b-11e6-9479-7a498ee3d9f6.png)

**Comment by vsch** [comment]
@neoaddix, the last official release does not have these options. The new options are available in the EAP plugin update channel. The selection for the update channel is at the top of the options pane you have in your screenshot.

These new features will be in the official release scheduled for Nov 14.

**Comment by neoaddix** [comment]
@vsch, thanks for the clarification, I'll show some patience ;-)
