### ISSUE TITLE
unexpected HTML export files

### ISSUE THREAD

**Issue by bstout** [vsch/idea-multimarkdown#330]
My HTML export is as:
![image](https://cloud.githubusercontent.com/assets/742839/19971782/4a32839c-a19d-11e6-96be-7aa612e6ffdd.png)

I also have a README.md at the module root.  When I make changes to that, an HTML file is created right next to it.  By above config, it shouldn't generate an HTML file, and even if it did, it shouldn't put it right next to it - but in the docs/html folder.

All I can think of is once, previously, I had it configured where the root was the module root and I think I also had target dir the module root which I think produced files like I'm seeing now.  But it was messy and I re-organized it and no longer have that config.  Is it possible that old config is still being acted upon somewhere?  Or, maybe the issue is elsewhere, but it's not my expectation this $ContentRoot$/README.md would generate an html file.

**Comment by vsch** [comment]
@bstout, it is a bug. ExportAll action checks for the right path prefix. OnSave actions does not. 😊

**Comment by vsch** [comment]
Available from the plugin EAP update channel.

**Comment by vsch** [comment]
@bstout, EAP release 2.1.1.26 has new HTML Export options to automatically export files on settings change and optionally on project open. These will also remove any generated files that are no longer part of the export profile.

![screenshot_htmlexport](https://cloud.githubusercontent.com/assets/10299086/20021947/a26e434a-a2ae-11e6-8c89-fd259cad5266.png)

Rudimentary wiki also updated: https://github.com/vsch/idea-multimarkdown/wiki/HTML-Export

**Comment by vsch** [comment]
@bstout, 2.1.1.26 was a dud. Use 2.1.1.28.

**Comment by vsch** [comment]
@bstout. eap 2.1.1.34 out. HTML export now shows progress dialog (only happens if you have a lot of files exported) and can be put in the background. Editing files that are being exported will result in a stale export.
