### ISSUE TITLE
Refactor file name reference in Jekyll Front Matter when renaming file

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#332]
@neoaddix, yes, I would appreciate a sample of actual Jekyll use case.

I will probably add Jekyll or Text based refactoring configuration that will allow flexible reference/refactoring in markdown elements based on RegEx patterns. That way any additional front matter variables, or other text elements, could be refactored without me having to modify code. 

For example file ref pattern: `^permalink: (?:(?:.*/)*)([^\\]+)\.html$` to file name replacement: `$1.md` would extract the file name from the permalink and change the extension.

A map from file name to permalink would take care of replacing it during refactoring. Similar to how link mapping works.

BTW, the link mapping feature in the next release, already available on the EAP update channel, can be used to change all the links to .html during completions and to resolve .html link addresses to .md documents. It can also be used to change path. Along with scope based markdown rendering profiles this allows you a lot of flexibility in how each document will be processed and rendered. See: [Modifying Link Processing](https://github.com/vsch/idea-multimarkdown/wiki/Modifying-Link-Processing) and [Installation: Configuration Settings](https://github.com/vsch/idea-multimarkdown/wiki/Installation#configuration-settings)

![linkmap](https://cloud.githubusercontent.com/assets/10299086/20037613/ddc2b3ac-a3f0-11e6-91ca-8d443bdab296.gif)

<img width="1004" alt="screen shot 2016-11-06 at 7 13 55 am" src="https://cloud.githubusercontent.com/assets/10299086/20037589/a28007ea-a3f0-11e6-8c81-02885bc5297e.png">

**Comment by neoaddix** [comment]
@vsch I have added a basic Jekyll example to Github that you can browse through a bit and get acquainted with Jekyll. I tried to add clear explanations, it's a starting point and let me know if you have any questions

https://github.com/neoaddix/jekyll-markdown-navigator

**Comment by vsch** [comment]
@neoaddix, thank you. Much appreciated. 

Here is the progress on the jekyll front matter refactoring:

![jekyll](https://cloud.githubusercontent.com/assets/10299086/20169950/323484b0-a6f8-11e6-9dd8-5711c55fc115.gif)

Here is the extended configuration that lets you define how to map text to file references (same as link references) and then from file to text. The former is used for finding file references and the latter is used to refactor the text when the file is renamed.

<img width="1148" alt="screen shot 2016-11-10 at 3 46 45 am" src="https://cloud.githubusercontent.com/assets/10299086/20169979/5c1deca8-a6f8-11e6-8993-e37369c0732a.png">

**Comment by vsch** [comment]
@neoaddix, eap 2.1.1.34 has this feature and I also updated the [wiki](https://github.com/vsch/idea-multimarkdown/wiki/Modifying-Link-Processing#jekyll-front-matter). For now this is under modifying link processing but has a section on jekyll front matter.

I added a section to experiment and validate the patterns so it makes it easier to get it right.

![Img](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_LinkMap_Jekyll_Settings.png)

**Comment by neoaddix** [comment]
@vsch really awesome work! I have downloaded the EAP release and am working with it nog and it seems to work smoothly. Thanks

I'm not really good at regex (not at all ;-) nut I assume this way of working can also be applied to the liquid include code? such as:

{% include links.html %}

**Comment by vsch** [comment]
@neoaddix, I put the regex for `permalink:` in the wiki so it can be copied into config:

> To ignore path in the permalink (only have the file name refactored) and change the `.md` extension to
> `.html` use the following:
> 
> For text conversion:
> 
> - pattern regex: `(?:^|\n)permalink:\s+(?:(?:.*)/)*([^\s]+)\.html(?:\s|$)`
> - to file reference text: `$1.md`
> 
> For file path conversion:
> 
> - pattern regex: `(?:(?:.*)/)*([^/]+)\.md(?:\s|$)`
> - to file reference text: `$1`
> 

For release I will have a way of adding some "standard" mapping groups without needing to write them yourself.

Support for liquid tags is not possible at the moment because it requires being able to process text blocks for liquid tags. I will see see if I can do the same as front matter processing for text blocks.

For proper Jekyll support I am considering a dedicated plugin for Jekyll projects. Kludging Jekyll support into a Markdown plugin has its limits. 

❓ Am I correct to assume that you would have a separate project for a Jekyll site and not have it embedded in another project?

**Comment by neoaddix** [comment]
@vsch Your last assumption is correct (at least in our case). When using Jekyll for documentation of projects we create separate projects/repositories for the documentation. And in other cases such as blogging the same. A dedicated Jekyll plugin sounds awesome. And if you need any 'help' from me just let me know.

I did copy the regex patterns from the wiki and they are working great. Concerning the liquid tags I was only thinking including files such as:

`{% include links.html %}`

But on second thought: it doesn't really add something because there is not much need for refactoring file names for such includes. It doesn't really matter what they are called eventually

At this moment I'm already really happy with the additional support, it makes working with Jekyll a lot easier, thanks!
