### ISSUE TITLE
Toolbars disappear when there's not enough space to fit all icons

### ISSUE THREAD

**Issue by lolmaus** [vsch/idea-multimarkdown#338]
Any other app I've ever worked with only hides icons that don't fit. This way, most icons always stay available.

Markdown Navigator hides all icons if one of them doesn't fit.

I work with two editor panes and I never see any icons on the toolbar.

**Comment by vsch** [comment]
@lolmaus, you may want to file YouTrack issue for this. The plugin does not control the toolbar behaviour. Being a plugin it works within the provided environment.

I will add configuration for the toolbar in settings so that you can remove buttons that you don't use. I got a ton of these uselessly taking up space.

**Comment by lolmaus** [comment]
Thx!

**Comment by vsch** [comment]
@lolmaus, came up with a temporary solution. In settings Languages & Frameworks > Markdown there is a new option: Hide disabled buttons. Actually quite nice, removes all the buttons you cannot press anyway.

Hope this is an acceptable contractor special for this issue. EAP 2.1.1.46 (also solves the trailing spaces issue, was a small bug with big consequences)

**Comment by vsch** [comment]
@lolmaus, BTW thank you for motivating me on this. I don't know if you are using the hide disabled buttons but I am hooked on the feature. All the stuff that I cannot press out of the way makes it easier to find the right operation.

Thank you.

**Comment by vsch** [comment]
@lolmaus, in the latest EAP rarely used actions are moved to popup menu buttons, making the toolbar short and with hide disabled buttons really short. #589
