### ISSUE TITLE
breadcrumb not support chinese

### ISSUE THREAD

**Issue by NonePro** [vsch/idea-multimarkdown#339]
![image](https://cloud.githubusercontent.com/assets/5492842/20645003/929c92a6-b487-11e6-8910-6d7ff579a448.png)

**Comment by vsch** [comment]
@NonePro, I am not sure but suspect it is a font issue. With the font I use there seems to be no problem:

<img width="389" alt="screen shot 2016-11-26 at 9 04 48 pm" src="https://cloud.githubusercontent.com/assets/10299086/20645031/2134aff6-b41c-11e6-8887-bff2987eebc6.png">

<img width="767" alt="screen shot 2016-11-26 at 9 05 19 pm" src="https://cloud.githubusercontent.com/assets/10299086/20645033/25c13148-b41c-11e6-9380-59aec1aae24b.png">

Did you try this with bread crumbs in XML which the IDE supports natively? If they don't work there then you should open an issue on [YouTrack: IDEA Issues](https://youtrack.jetbrains.com/issues/IDEA?q=project:%20%7BIntelliJ%20IDEA%7D)

The plugin supports actual character width for formating and wrap on typing specifically for non-latin alphabet users: 

Formatted without using actual character width:

<img width="1039" alt="screen shot 2016-11-26 at 9 07 20 pm" src="https://cloud.githubusercontent.com/assets/10299086/20645050/036f39f4-b41d-11e6-9a37-02360abfdee9.png">

And formatted using actual character width:

<img width="1010" alt="screen shot 2016-11-26 at 9 07 44 pm" src="https://cloud.githubusercontent.com/assets/10299086/20645051/086495d0-b41d-11e6-8d9d-343cfaa45f93.png">

**Comment by NonePro** [comment]
I'm truly grateful for your help.
