### ISSUE TITLE
ArrayIndexOutOfBounds when parsing text block with \ as last character

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#343]
Caused by flexmark-java escaped char extension not checking for this condition. 

vsch/flexmark-java#19

**Comment by FatherShawn** [comment]
Is this the same issue as this error message:

`Flexmark parser exception: String index: 23 out of range: 0, 22`

**Comment by vsch** [comment]
@FatherShawn, depends on whether the markdown has a trailing \ as part of a paragraph or a list item.

Can you please post the first few lines (enough to include the first 23 characters of the file) so I can double check it?

**Comment by FatherShawn** [comment]
I'm not sure which file - I really was just working in phpStorm and the exception came up. I didn't want to spam your issue queue if it was the same. I've loaded everything I know into https://github.com/vsch/idea-multimarkdown/issues/356

**Comment by vsch** [comment]
@FatherShawn, thank you for taking the  time to report this. 

The file you included seems like the right one because it is only 22 characters long. It is a table separator row. It makes sense that you were typing in a new table and triggered the bug if the parser was expecting more characters after the first line.

The new version of the flexmark-java parser and the plugin no longer have a problem with it. In the last few releases of the parser I added more tests and fixed bugs having to do with files not terminated with a \n or \r\n.

You can get the EAP plugin update which has this issue fixed by switching the plugin update channel to EAP and do a check for updates in the IDE. 

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by FatherShawn** [comment]
You are welcome!

It sounds like you have this, but just to be clear: _I was not working in markdown, nor did I have any markdown files open._

**Comment by vsch** [comment]
@FatherShawn, as long as you have markdown files in the project and the plugin installed, the IDE will have the plugin parse markdown files when it is indexing the project. So something triggered indexing of files on the project and this partial file was indexed causing an exception.

**Comment by FatherShawn** [comment]
That make perfect sense.  I had recently pulled from the repo.  Thank you for this project!

**Comment by vsch** [comment]
@FatherShawn, you are welcome.
