### ISSUE TITLE
Show version number on plugin configuration screen

### ISSUE THREAD

**Issue by gkertai** [vsch/idea-multimarkdown#349]
Just a small idea for improvement: display the currently installed version number on the *Languages & Framework / Markdown* page for easier inclusion in issue reports. 

It would be quicker to access than scrolling through dozens of plugins on the Plugins page (or searching thereof).

![screen_shot_2016-12-09_at_18_41_23](https://cloud.githubusercontent.com/assets/1874498/21058675/66d0c554-be3f-11e6-8720-96432dc8ff90.png)

**Comment by vsch** [comment]
@gkertai, I will add it to the top too. :)

![screenshot_settings_version](https://cloud.githubusercontent.com/assets/10299086/21059230/6a256050-be0f-11e6-8d2d-82252a5f894d.png)

**Comment by gkertai** [comment]
Oops… my bad. :)

Close this then?

**Comment by vsch** [comment]
@gkertai, no. You are right. It should be next to the update channel selection drop down.

**Comment by vsch** [comment]
@gkertai, next release:

![screenshot_settings_version](https://cloud.githubusercontent.com/assets/10299086/21658418/8f0aff08-d294-11e6-8741-d794f3a8aae4.png)
