### ISSUE TITLE
Files without suffix are not resolved in links

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#352]
![image](https://cloud.githubusercontent.com/assets/3531020/21305873/4a69b3c6-c5ce-11e6-8544-c0cdb29333db.png)

There actually is a `LICENSE` file locally and on GitHub, it seems just not to be recognized by the plugin - maybe because it does not have a suffix?

Edit: _Both_ the errors shown in the screenshot belong to this single link.

**Comment by vsch** [comment]
@bkimminich, files are looked up using file type index. To address this issue I add "Text" file type if no index is given in completion or a link has no extension. It will work for files without extensions that were not assigned a different file type by the user to a file without extension.

Assigning a different file type in the IDE to a file without extension will make it again invisible to the plugin for completions and link resolution.

**Comment by vsch** [comment]
Fix available on the plugin EAP Channel.
