### ISSUE TITLE
Icons are disable in the markdown toolbar

### ISSUE THREAD

**Issue by danielgodard** [vsch/idea-multimarkdown#355]
Only few icons are enables in the toolbar:

![image](https://cloud.githubusercontent.com/assets/15653345/21643834/cad05dee-d28a-11e6-89d1-34e1edb054d8.png)

**Comment by vsch** [comment]
@danielgodard, the toolbar buttons are contextual and will enable/disable based on the caret context in the document.

You can hide disabled toolbar buttons to save screen real-estate by selecting the `Hide disabled toolbar buttons` in main settings panel:

![Screen Shot Settings Hide Toolbar Buttons](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_HideToolbarButtons.png)

**Comment by vsch** [comment]
@danielgodard, latest EAP release adds reason why toolbar button is disabled. #385 

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
