### ISSUE TITLE
"Reformat Document" inflates files with link references

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#359]
I did not realize this problem before the affected README file reached 30MB in size. It's hard to explain what happens, so I created a "screenshot-story" instead! :book: 

The first screenshot below shows my starting situation:
![image](https://cloud.githubusercontent.com/assets/3531020/21818955/0a62489e-d76a-11e6-80d6-72fdd190bfe8.png)

Every following one was taken after I clicked "Reformat Document" once more:
![image](https://cloud.githubusercontent.com/assets/3531020/21818966/11968904-d76a-11e6-8a62-0194150478a2.png)

![image](https://cloud.githubusercontent.com/assets/3531020/21818973/1a68d442-d76a-11e6-9e01-53ee074f9dff.png)

![image](https://cloud.githubusercontent.com/assets/3531020/21818981/22ed449a-d76a-11e6-82b1-c6fc46d18fce.png)

and so on and so forth until at some point the performance while typing is going down and my IDEA commits suicide... :gun:

**Comment by vsch** [comment]
@bkimminich, thank you for reporting it. I will look into the bug. Are these footnotes (you have footnotes extension enabled in parser settings) or link references that look like footnotes because of the ^ prefix?

**Comment by bkimminich** [comment]
I use the GitBook profile with Footnotes enabled. When I turn Footnotes off in the profile the problem does not occur any more.

**Comment by vsch** [comment]
@bkimminich, it gets confused on the content of footnotes and doubles the text. The surprise for me is that the performance of the plugin is so good that you only noticed it when the file grew to 30MB.

I'll fix it and make a fix release and post a link here.

**Comment by bkimminich** [comment]
> The surprise for me is that the performance of the plugin is so good that you only noticed it when the file grew to 30MB.
Yep, the plugin is definitely worth it's license cost! :grin:

**Comment by vsch** [comment]
@bkimminich, confirmed it is a dumb bug I introduced when refactoring code to make all elements respect the parser "List Type" processing and unified the element prefix/text handling. For footnotes I used the wrong element type to mark the start of text. Fix coming shortly.

**Comment by vsch** [comment]
@bkimminich, EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
