### ISSUE TITLE
HTML Export "CSS dir" and "script dir" not saved

### ISSUE THREAD

**Issue by saldi** [vsch/idea-multimarkdown#361]

**Comment by saldi** [comment]
When I changed settings off "CSS dir" or "Script dir" a new configuration is not saved between export steps. Next export is made with default settings.
Windows 7/Idea 2017.1 EAP

**Comment by vsch** [comment]
@saldi, thank you for report this. It is confirmed to be a bug caused by recursive event triggering during initialization of settings UI that overwrites values of the text fields.

I will make an EAP release with a fix shortly.
