### ISSUE TITLE
PhpStorm - Highlight preview element settings doesn't persist between sessions

### ISSUE THREAD

**Issue by fulopattila122** [vsch/idea-multimarkdown#365]
Hello,

here's a tiny little bug (I guess). The title should tell it all, but also see this short video demonstrating it:
https://youtu.be/RD7SsA-MZyc

**Comment by vsch** [comment]
@fulopattila122. thank you for reporting it. Confirmed that the setting is lost when the IDE restarts. Investigating it now.

**Comment by vsch** [comment]
@fulopattila122, EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by fulopattila122** [comment]
Thank you, that was fast :) I confirm that it works on my end as well.
