### ISSUE TITLE
"Unknown emoji" error reported for timestamp

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#366]
![image](https://cloud.githubusercontent.com/assets/3531020/22042048/c6358da2-dd09-11e6-85ae-f81ae29a73a0.png)

⌚️ != 😃 

----

😛

**Comment by vsch** [comment]
@bkimminich, emoji shortcuts are between two colons. If I can think of a good constraint to eliminate common two colon constructs I will add it to the parser not to interpret these as emoji shortcuts.

I will add this case to the list. For now you can safely ignore it. 😁

**Comment by vsch** [comment]
@bkimminich, I settled for not highlighting emoji shortcuts that contain all digits and are 2 digits in length.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
