### ISSUE TITLE
Right margin setting not honored with soft wrap

### ISSUE THREAD

**Issue by tomjohnson1492** [vsch/idea-multimarkdown#368]
I have soft wrap enabled, but the Markdown Navigator plugin isn't honoring the right margin setting that I specify. Is this a bug, or is there another way to adjust where the content wraps? The default column is too narrow.
![rightmargin](https://cloud.githubusercontent.com/assets/6385062/22160020/765540a2-def8-11e6-8995-11e7e364bff9.png)
![rightmargin2](https://cloud.githubusercontent.com/assets/6385062/22160021/7657cdae-def8-11e6-815e-a7c5b46e93eb.png)

**Comment by vsch** [comment]
@tomjohnson1492, please check markdown code style to make sure you have default checked for the right margin settings. Otherwise, markdown has its own margin.

<img width="920" alt="screen shot 2017-01-20 at 1 10 38 pm" src="https://cloud.githubusercontent.com/assets/10299086/22160129/0b1107bc-df12-11e6-8ce4-268ef488a95b.png">

**Comment by tomjohnson1492** [comment]
ahhh, that works. I hadn't set that margin setting. Thanks! 

By the way, it seems like there are two Right Margin settings. One at Code Style, and another at Code Style > Markdown.

**Comment by vsch** [comment]
@tomjohnson1492, the right margin at Code Style applies to all languages, Markdown also provides its own since chances are good that you don't want the same margin for code and docs.

**Comment by vsch** [comment]
@tomjohnson1492, Markdown has many IDE settings that it overrides because the IDE settings don't always make sense for Markdown. Trim Trailing spaces is one, soft wrapping is another. The former is in Code Style > Markdown and the latter in Languages & Frameworks > Markdown.
