### ISSUE TITLE
'Wrap on Typing' setting doesn't apply in .md editors

### ISSUE THREAD

**Issue by cemerick** [vsch/idea-multimarkdown#381]
In the top-level 'Code Style' settings, I've selected a margin of 100, and enabled 'Wrap on Typing'. This works as expected in all other editor types, but seems to be ignored in .md buffers. The margin rule is drawn properly, but my typing rolls right through it without any wrapping.

**Comment by vsch** [comment]
@cemerick Markdown has its own margin by default. Please see #368.

**Comment by cemerick** [comment]
I tried ticking that 'Default' checkbox, with no change.

I see the "code style only available in enhanced edition" text; I presume that applies here.

**Comment by vsch** [comment]
@cemerick, yes it does. Wrap on Typing requires full parse tree for Markdown which is only available in the enhanced edition. You can get a trial license at https://vladsch.com/product/markdown-navigator/try to enable all enhanced features for 15 days.
