### ISSUE TITLE
Remove unnecessary frame in preview

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#396]
The preview should not wrap content again, since the preview pane is part of the editor, so the user is always aware of the file name

![image](https://cloud.githubusercontent.com/assets/200952/23453698/9e5b64ec-fe69-11e6-8434-7bcd62304b5d.png)

It's more obvious in the fx-preview but also applies to the regular swing preview

**Comment by vsch** [comment]
@holgerbrandl, the frame is there only to match the GitHub look. To turn it off de-select `Add Page Header`

![screenshot_html_pageheader](https://cloud.githubusercontent.com/assets/10299086/23464558/82e2945c-fe63-11e6-9c8d-ffa367ef8f54.png)

**Comment by holgerbrandl** [comment]
How could it I miss it?! Thanks for helping out.

Since github is just a very special use-case the default should imho be the other way round.
