### ISSUE TITLE
Good code is red:  images links in non-project markdown files

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#397]
When opening non-project markdown files (e.g. by dragging them into idea or by using Idea's shell helper), image references are flagged as `Unresolved`.

However they are resolvable with respect to the document location in the filesystem and even the preview works:
![image](https://cloud.githubusercontent.com/assets/200952/23453812/04d68abc-fe6a-11e6-8188-095ab2d77edf.png)

**Comment by vsch** [comment]
@holgerbrandl, completions and resolution of links is done via file index which requires that the IDE considers them as project files otherwise it does not index these files.

The preview browser uses its own resolution rules which resolves files relative to the document location.

My solution so far has been to mark the root directories of these files as `Test Resources` root, then they will be indexed.

**Comment by holgerbrandl** [comment]
Also in module-included vcs-versioned markdown files relative links are tagged as errors:

![image](https://cloud.githubusercontent.com/assets/200952/25942440/2589cb42-363d-11e7-955b-65fc995ebf93.png)


IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
Licensed to Max-Planck-Institut fuer Molekulare Zellbiologie und Genetik / holger brandl
Subscription is active until January 25, 2018
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4


Markdown Navigator version: 2.3.7.10

**Comment by vsch** [comment]
@holgerbrandl, seems to depend on the project structure. Simple attempt to duplicate this failed.

Is the module under a project directory or located at another location?

**Comment by holgerbrandl** [comment]
It's a single module project, with the module being located in the project-directory. However, the mentioned markdown file sits in another content-root which I have added to the module:
![image](https://cloud.githubusercontent.com/assets/200952/26251120/7cbf353a-3cac-11e7-8d84-080da48f9304.png)
From an idea  perspective it's still part of the module, and is listed under "project" in the project-tool window.

**Comment by vsch** [comment]
@holgerbrandl, I think this one is fixed in the latest EAP 2.3.8.2. 

I found some code that would cause a file to be flagged as unresolved if it is not under VCS and has an empty path in the URL. This falls under this use case.
