### ISSUE TITLE
Highlight search results in preview

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#399]
It would be awesome if the plugin could also highlight search results in the preview pane. Ie. yellow background for the search results hits also for the preview. Here's mockup for the expected result:
![image](https://cloud.githubusercontent.com/assets/200952/23454429/7bb3ec40-fe6c-11e6-90d1-a9acbf7e7d8a.png)

This would allow to actually use the preview more often. Especially when being combined with the amazing "Sync source to preview on click".

**Comment by vsch** [comment]
@holgerbrandl, I wanted to do this for a long time. Not knowing exactly how to do it has put it on the back burner. Thank you for bringing it to the forefront.

I will look for the IDE API to get the search criteria so I can add it to flexmark-java library to have the generated HTML generates with highlighted text. This way both JavaFX and Swing preview will have this functionality.

**Comment by vsch** [comment]
@holgerbrandl, figured out how to get search panel information and notifications when this changes. Tomorrow I will add code to highlight search results.

No way for me to get excluded elements so the search results will be results of the search through the document text. 

I will have to regenerate the HTML with highlights every time the document changes or search criteria change. Text in preview will be highlighted based search match offsets from the markdown document. 

The reasons for this is to allow partial highlights for example searching for `**text` which will match part of `**text**`. In preview the bold word `text` will be highlighted.

I think this is the most intuitive way to transfer the search results from Markdown to preview. 

What do you think?

**Comment by holgerbrandl** [comment]
Sound like a great improvement to me. Just let me know when I could try/test it via EAP.

I would guess that in 99% of the time users don't bother with element exclusion when searching stuff.

**Comment by vsch** [comment]
@holgerbrandl, here is the result so far. Need to clean up some code and it will be ready for EAP, may have a few bugs.

![searchhighlight](https://cloud.githubusercontent.com/assets/10299086/23531513/bd4e5056-ff74-11e6-8c9c-9cead19f006c.gif)

**Comment by vsch** [comment]
@holgerbrandl, EAP available

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment]
@holgerbrandl, each feature leads to another feature. :) Another EAP released.

I think you will like this one. I find it very convenient:

![previewhighlights](https://cloud.githubusercontent.com/assets/10299086/23539349/ba9489e6-ffa8-11e6-84cc-67c56f6662be.gif)

To customize colors add these selectors to your custom CSS text (modify style to your liking):

```
.search-highlight {
    border: solid 1px #000;
    padding: 1px;
    background-color: rgb(255,255,0);
    color: #000;
}

.selection-highlight {
    color:#000;
    padding:1px 0 1px 0;
    border: solid 1px #52CC7A;
    background-color: #B5FFCE;
}

```

![image](https://cloud.githubusercontent.com/assets/10299086/23539407/28bcaba6-ffa9-11e6-8d05-2943fb7ae31c.png)

**Comment by holgerbrandl** [comment]
Once it's enabled, it works just great. Thanks a lot! Its a  super handy feature and gives MN another clear edge over JB MS.

It took me a while to realize that it's not enabled by default. Why would anyone not like it enabled by default? Personally I would not even have added a settings item for it at all.  Imho the MN is a bit too obsessed with configurability and should rather go for convention where possible. Many colleagues of mine never bother checking "the settings" to see if there are "hidden" features.

Highlighting selections did not work for me. Not sure what I do wrong.

**Comment by vsch** [comment]
@holgerbrandl, could be configuration, although I have it enabled by default. Could be a bug or a version diff. I have not tested on anything but IDEA, RubyMine, PyCharm and PhpStorm may have quirks that I will need to debug.

I try to make defaults acceptable but I add options because there is always someone with a system that under performs or they just don't like it.

Is it enabled on your system?

<img width="919" alt="screen shot 2017-03-03 at 12 51 04 am" src="https://cloud.githubusercontent.com/assets/10299086/23539844/c5f45c00-ffab-11e6-8603-04392b3030a4.png">

**Comment by vsch** [comment]
@holgerbrandl, just tried RubyMine, PyCharm, WebStorm, PhpStorm all 2016.3 and all had selections working. What IDE and version are you using?

I am developing on latest 2017 EAP and tried PhpStorm 2017 too. All worked. Are you getting any exceptions?

**Comment by holgerbrandl** [comment]
IntelliJ IDEA Ultimate 2016.3.4. Anyway I figured it out. You pushed out another EAP after the EAP with the search highlighting, which I had not installed. Now I can see the additional settings entry as well, and the selection highlighting works like charm.
