### ISSUE TITLE
Parser fails if code chunks contain mardkown header elements

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#401]
Example markdown code

[scratch_60.txt](https://github.com/vsch/idea-multimarkdown/files/810339/scratch_60.txt)

![image](https://cloud.githubusercontent.com/assets/200952/23455868/85c17a7c-fe71-11e6-975f-d1d9f8593835.png)

The 2 last lines are regular markdown, but the parser got confused when using a comment with a preceding leading line in the code-chunk. 

Language injection is not needed, so you don't need the r plugin to reproduce the problem.

It would work with the plugin if the code chunk is preceded by an empty line, but I don't think that this is required by the markdown specs.

For me this renders the plugin unusable at the moment (since I have a gazillion code chunks like that) and I have to move back to the JB Markdown support plugin until a fixed version is being released.

**Comment by vsch** [comment]
@holgerbrandl, this is a bug in the parser library that I will address in the EAP release shortly. I will post as soon as it is available.

**Comment by vsch** [comment]
@holgerbrandl, temporary workaround is to switch list item parsing rules to CommonMark, it is an issue with GitHub parsing rules. I am fixing it now.

![screenshot_parser_lists](https://cloud.githubusercontent.com/assets/10299086/23466162/503981fa-fe68-11e6-83ef-487d9f8ccffd.png)

**Comment by vsch** [comment]
@holgerbrandl, I made an official release for the NPE bug on paste and the fix for parser fix is part of it. If you update the plugin to version 2.3.4 then parsing will work correctly with GitHub list processing.

**Comment by holgerbrandl** [comment]
This was amazingly quick :-). Thanks a lot for the great support!
