### ISSUE TITLE
Incorrect spacing in rendered lists

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#409]
Using the following markdown code, 
```
* Configure tang lab for Yvonne

* Equipment
* Chemicals
* Consumables
* Enzymes
* GMO
* Antibodies
* DNA Constructs
* RNA Constructs
* Vectors
* Oligos
```
I get the following preview when using version  2.3.4.8:
![image](https://cloud.githubusercontent.com/assets/200952/23703830/2c452a84-0402-11e7-81fa-c391f0377dd7.png)

Imho there's unintended space after "Equipment". Or do I miss some part of the Markdown language specs?

**Comment by vsch** [comment]
@holgerbrandl, welcome to GitHub Document processing idiosyncrasies. Here is a document created with your source and displayed on GitHub:

![image](https://cloud.githubusercontent.com/assets/10299086/23716293/b3419b30-03fd-11e7-87c7-606627005eb4.png)

You can turn off this idiocy-ncrasy in Parser settings by de-selecting the `GitHub loose list item rules` but then the document will not display correctly on GitHub, if that matters to you:

![screenshot_parser_settings](https://cloud.githubusercontent.com/assets/10299086/23716507/82110388-03fe-11e7-9f2d-ee62d379943b.png)

**Comment by holgerbrandl** [comment]
I don't see why gh would call this a feature, looks more like a bug to me. Anyway thanks for the info and the settings item.

**Comment by vsch** [comment]
@holgerbrandl, I agree and can cry over a long list of "features" that I had to find by trial and error and then wrestle with mimicking in my rendering.

At least they switched to CommonMark for issue and pr comments. Before that their parser would be even weirder than for documents.

Markdown only looks simple at first glance.
