### ISSUE TITLE
Allow to apply atx/setext quickfix to all occurences in file

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#417]
It would be great if the quickfix could be applied to all occurrences in a file
![image](https://cloud.githubusercontent.com/assets/200952/24138127/440d4bf0-0e17-11e7-8e8b-d6ba69b71ebd.png)

Similar to how java-quickfixes can be applied to a complete file
![image](https://cloud.githubusercontent.com/assets/200952/24138146/56dc09b0-0e17-11e7-80bf-a11f130e4b77.png)

**Comment by vsch** [comment]
@holgerbrandl, I am looking into the API so I can figure out how to implement this. If you have any idea where to start looking please let me know. I will also post a question on plugin dev for advice.

**Comment by holgerbrandl** [comment]
That's a good question. For actual inspections (i.e. subclasses of com.intellij.codeInspection.LocalInspectionTool you get it automatically if a corresponding LocalQuickFix is defined. However for com.intellij.codeInsight.intention.IntentionAction's the "Fix all" is also missing in my R-plugin. Let's see what the JB folks say in the forum.

**Comment by vsch** [comment]
@holgerbrandl, I think I saw an adapter from LocalQuickFix to IntentionAction in the API, maybe there is one for the reverse or I can rewrite intentions as local quick fixes and use an adapter to turn them into extensions.

**Comment by vsch** [comment]
@holgerbrandl, to make the Fix All available on the sub-menu these intentions need to be changed to Inspection quick fixes.

Now that can be done and then all intentions that make sense to apply to a file will automatically have the Fix All.

The other option which I already implemented as a quick fix is to add "Apply all '...' in file" low priority intention which puts these at the bottom of the intention list.

![image](https://user-images.githubusercontent.com/10299086/28222011-a19343ac-6893-11e7-8de0-ead8cdf7cb93.png)

I am of two minds on this. Inspections have the advantage of being used in analyze reports. Intentions do not require going through the whole file (only the caret context).

What do you think would be the best approach from your perspective?

**Comment by vsch** [comment]
@holgerbrandl, eap plugin channel updated with above fixes added.

**Comment by holgerbrandl** [comment]
I did not now about the existing "Apply all" which completely solves my usecase. Thanks a lot for the improvement!

I think most users won't need mass markdown refactorings using analyze reports, so I'd guess the "Apply all" is sufficient.
