### ISSUE TITLE
"Find" / Cmd+F Keyboard Shortcut Breaks Editor With This Plugin

### ISSUE THREAD

**Issue by codekiln** [vsch/idea-multimarkdown#427]
In PyCharm 2017.1, using the latest version of the markdown plugin, if I use Cmd+F (Mac) to search the readme document, the entire document turns to a blank rectangle, and it needs to be closed and reopened to continue editing it. 

I uninstalled the markdown plugin, and find works just fine again.

**Comment by vsch** [comment]
@codekiln, was there an exception? Do you have a stack trace that you can post here?

**Comment by vsch** [comment]
@codekiln, I was not able to duplicate this in PyCharm 2017.1 and 2017.1.1 RC for both plugin version 2.3.5 and 2.3.5.4 eap.

If you try the eap plugin version 2.3.5.4 and do get an exception can you please send the exception report so I can see what is causing the problem.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
