### ISSUE TITLE
Lack of encoding declaration when exporting in html

### ISSUE THREAD

**Issue by Guilouf** [vsch/idea-multimarkdown#428]
There is a missing `<meta charset="UTF-8">` in the html code preview. This does not cause any problem to view inside the jetbrains IDE, but when putting the html code in a html file, obviously some chars did not display properly.

**Comment by vsch** [comment]
@Guilouf, thank you for the report. I will make the change to HTML export and make an EAP release with the fix shortly.

**Comment by vsch** [comment]
@Guilouf, you can use a workaround by manually adding the meta tag to HTML Generator tab of your export profile or to the project HTML Generator if you have export defined in the project profile:

![image](https://cloud.githubusercontent.com/assets/10299086/24920227/7e420f10-1eb4-11e7-966f-3ef67ecfe2d4.png)

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by Guilouf** [comment]
Thank for the tips!
