### ISSUE TITLE
Single line breaks in list item generates a <br/>

### ISSUE THREAD

**Issue by johnsoftek** [vsch/idea-multimarkdown#431]
List items should be allowed to continue over multiple source lines with the line breaks treated as "soft". The generated HTML should auto-flow the list item content without inserting ```<br/>``` for each line break.

Note that the treatment of line breaks is not consistent across all Markdown renderers. Notably, Github does ignore single line breaks as does this online Markdown editor: http://dillinger.io/ and Webstorm's built-in Markdown renderer.

John Gruber said back in 2004:

> The implication of the “one or more consecutive lines of text” rule is that Markdown supports “hard-wrapped” text paragraphs. This differs significantly from most other text-to-HTML formatters (including Movable Type’s “Convert Line Breaks” option) which translate every line break character in a paragraph into a ```<br />``` tag.

> When you do want to insert a ```<br />``` break tag using Markdown, you end a line with two or more spaces, then type return.

**Comment by vsch** [comment]
@johnsoftek, you need to de-select `Hard Wraps` option in parser settings. Please see issue #91

**Comment by johnsoftek** [comment]
@vsch That works. Thank you.
