### ISSUE TITLE
Add a way to disable the startup notification

### ISSUE THREAD

**Issue by SUPERCILEX** [vsch/idea-multimarkdown#432]
### This is the one I'm talking about BTW:

![untitled](https://cloud.githubusercontent.com/assets/9490724/25357560/20cbf4ec-28f3-11e7-8bcf-e986ac980976.png)

**Comment by vsch** [comment]
@SUPERCILEX, this is only supposed to pop-up after an update to a new version or a new installation. Are you getting it every time you start the IDE? If you are then this is a bug.

**Comment by SUPERCILEX** [comment]
@vsch Yup, just restarted Intellij and the `2.3.5.10` notification is still there. It's really kinda annoying actually.

**Comment by vsch** [comment]
@SUPERCILEX, thank you for the information. I found the bug.

The information about the version is stored in the markdown_navigator.local.xml file in IDE settings `options` subdirectory. This file holds all non-shared local settings for the plugin.

The line holding the information is the following:

    <WasShown licensedAvailable="true" lastFeatureUpdateVersion="2.3.5.12" lastLicensedAvailableVersion="" javaFxAvailable="false" jekyllFrontMatter="false" />

If you change the `licensedAvailable` attribute value to `true` it will work as it is supposed to. I will make a fix in the next release that will do this automatically. It is a leftover from previous versions that I failed to catch.

On OS X the file is in `~/Library/Preferences/IdeaIC2017.1` or `~/Library/Preferences/IntelliJIdea.1` depending on whether it is Community or Ultimate. On Windows and other OS it is stored in a user directory with all other IDE preferences.

**Comment by SUPERCILEX** [comment]
@vsch Awesome, thanks!!!

**Comment by vsch** [comment]
@SUPERCILEX, you are welcome and thank you for reporting it.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by SUPERCILEX** [comment]
@vsch Thanks, I was already in the EAP I enjoy your plugin so more more than JetBrains'. Thanks for the great work!

**Comment by vsch** [comment]
@SUPERCILEX, please send me your name and e-mail to my `vladimir at vladsch dot com` address and I will send you a complimentary license. If you think you are enjoying the plugin now you will be surprised at how much more enjoyable it is with all the IntelliJ smarts features enabled.

BTW, the nag about licensed features was a suggestion from a user who was shocked by the difference in the licensed version and told me that I must "nag the hell out of users" to inform them of the differences. Unfortunately I missed the bug and caused a bit more of a nag than I desired. 😊

**Comment by SUPERCILEX** [comment]
@vsch Aw man, getting a free license would be awesome!!! Haha, can't wait to try out the pro version if it's just _that_ good! 😁

PS: I sent you the email.
