### ISSUE TITLE
Spellchecker context menu is duplicated

### ISSUE THREAD

**Issue by blowsie** [vsch/idea-multimarkdown#434]
WebStorm 2017.1.1
Build #WS-171.4073.40, built on April 11, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.

![image](https://cloud.githubusercontent.com/assets/308572/25390874/b3b21852-29cc-11e7-8e61-afcf7b1fe069.png)

---
I have confirmed this does not happen with other file types.

**Comment by blowsie** [comment]
Sorry I did search for this issue before posting this issue, however I found this one after.

#423

feel free to close

**Comment by vsch** [comment]
@blowsie, thank you for reporting this. I am still in the process of trying to find the condition under which this occurs.

If you have a snippet of Markdown that shows this bug can you please post it here so I can duplicate this for debugging.

**Comment by blowsie** [comment]
I will try and share something next time it comes up. Interestingly right now, I have no spell checking working at all

**Comment by blowsie** [comment]
I just discovered with the same text in PHPStorm this is not and issue, like it is in WebStorm

**Comment by blowsie** [comment]
Here is an example file that causes this error
```
I Lurve Sauaseges
```

**Comment by blowsie** [comment]
Perhaps WebStorm matches more than one of the following
- Code
- Literals
- Comments

![image](https://cloud.githubusercontent.com/assets/308572/25524911/4f22b84e-2c04-11e7-87ab-9d11c119ac0e.png)

**Comment by vsch** [comment]
@blowsie, thank you for the extra information. However, I am not able to duplicate the issue which only means that there is some other required condition for this bug to be activated.

It could also be related to IDE implementation changes making it version dependent.

**Comment by vsch** [comment]
@blowsie, found the condition when this happens. It is duplicated for every level of block quotes.

**Comment by vsch** [comment]
@blowsie, EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
