### ISSUE TITLE
false positive typo annotation in header

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#441]
For some reason words followed non-word characters (!, ?, .) in headers (and just there) are tagged as typo

![image](https://cloud.githubusercontent.com/assets/200952/25650925/75ecc6a6-2fe0-11e7-9567-9b35816627b0.png)

MN version: 2.3.7.4

**Comment by vsch** [comment]
@holgerbrandl, I tried it on intellij-community master branch build and I am not getting this nor in IDEA 2017.1.2 nor 2016.3, nor PyCharm 2017.1.2

What IDE and version is this in? The plugin passes the text to the IDE for spell checking, without breaking it up on any characters. I suspect it is an issue in the IDE code.

**Comment by holgerbrandl** [comment]
IntelliJ IDEA 2017.1.2
Build #IU-171.4249.39, built on April 25, 2017
Licensed to Max-Planck-Institut fuer Molekulare Zellbiologie und Genetik / holger brandl
Subscription is active until January 25, 2018
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.4

Not sure what other  info to provide. It's flagged as typo just in markdown headers (both atx and setext. But don't waste any time on it. It is just about spellchecking and happens rarely. :-)

**Comment by vsch** [comment]
@holgerbrandl, just realized that I missed a critical detail of text in Headings. I can duplicate this so I will take a look at the cause.

**Comment by vsch** [comment]
@holgerbrandl, found the bug. For elements that can have references IdentifierSplitter was used to split text for spellchecking but for Markdown TextSplitter should be used since these elements are text and not Camel case identifiers.

EAP 2.3.7.10 has this issue fixed.
