### ISSUE TITLE
Doesn't work synchronised scrolling between the left and right (preview) views

### ISSUE THREAD

**Issue by kirilenko** [vsch/idea-multimarkdown#443]
Doesn't work synchronised scrolling between the left and right (preview) views

**Comment by vsch** [comment]
@kirilenko, this functionality is available in the licensed version with the options enabled. You can get a free trial license to enable the functionality https://vladsch.com/product/markdown-navigator/try

![screenshot_settings_previewsourcesynchronization](https://cloud.githubusercontent.com/assets/10299086/25776795/c22eb91c-3296-11e7-8825-a7a56f7a2b00.png)

**Comment by kirilenko** [comment]
Thanks

**Comment by Mochnant** [comment]
Any chance this could be moved to the normal edition?  Seems like pretty basic functionality that still aligns with the vision of the unpaid version as intended to preview work done manually in the source window.

**Comment by vsch** [comment]
@Mochnant, I will take a look at the code to see if this can be enabled separately from other missing components in the AST. If it is possible I will enable it in the basic edition.

I will let you know as soon as I can verify the possibility of enabling this functionality.

**Comment by Mochnant** [comment]
I appreciate the exceptionally fast reply and the willingness to explore the possibility!

**Comment by vsch** [comment]
@kirilenko, @Mochnant, latest EAP has the synchronized scrolling enabled for basic version. I also made highlights and sync from preview to source available.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by Mochnant** [comment]
Thank you, @vsch!

I have selected EAP and updated plugins and restarted.  It shows version 2.4.0.34.

However, I still see the scrolling options as greyed out.  Is this the correct version?

![screen shot 2018-01-24 at 8 28 40 am](https://user-images.githubusercontent.com/746190/35334512-ab4aeef0-00e0-11e8-8fec-99877c1d4b34.png)

![screen shot 2018-01-24 at 8 28 48 am](https://user-images.githubusercontent.com/746190/35334519-b2936f2a-00e0-11e8-87de-8e2a20ac63df.png)

**Comment by vsch** [comment]
@Mochnant, these options only work with the JavaFX preview browser. Swing does not support synchronization.

You need to switch the preview browser type in Preview settings.

**Comment by Mochnant** [comment]
Thank you, that change fixed it.  Looks good, the only thing I notice is that the preview seems to have trouble with the beginning and ends of files.  When those are reached in the editor pane, it does not seem to want to go to the beginning/end in the preview pane.

**Comment by vsch** [comment]
@Mochnant, the plugin uses the caret visual vertical position vs the total visible text view to calculate the % position. The preview is then asked to place the corresponding element at the same % position of total view port to align the **vertical center** of the element.

At the start and end of the document this logic can fail, depending on the content size and content of the page which is not rendered from markdown.

If you could provide example markdown that exhibits this I can see if I can add start/end document logic to improve synchronization for these cases.

**Comment by Mochnant** [comment]
@vsch I have attached an .md file that shows this behavior (.txt is for github uploading and can be removed).

Thanks!

[Demo.md.txt](https://github.com/vsch/idea-multimarkdown/files/1664774/Demo.md.txt)

**Comment by vsch** [comment]
@Mochnant, thank you for the file. I will see if I can improve the scrolling for the top element. 

There is no issue in this case with bottom of file but will exist if the last markdown element is vertically greater than one line. The code will center it against the source line and half of it will be below the bottom line.

**Comment by Mochnant** [comment]
@vsch Thank you.  It may be due to the top par's issue you mentioned, but if I put both the editor and the preview pane at the very top of the file, and put the cursor in the first line, when I scroll the editor down it will not reach the bottom.

Note that I added #s to the subheadings to make it a little more clear.

![screen shot 2018-01-25 at 1 31 18 pm](https://user-images.githubusercontent.com/746190/35405436-227b45b2-01d4-11e8-92c9-f91846c3863d.png)

**Comment by vsch** [comment]
@Mochnant, you should scroll the preview in such cases. The sync is intended to align source to preview of the caret position to allow quick visual location of the preview element.

The scrolling of the preview when the source is scrolled is a side-effect of this alignment, not really indented to scroll the preview from top to bottom.

I might be able to figure this out by scaling the source scroll to the vertical span of the preview but cannot see all the gotchas until I try it.

**Comment by Mochnant** [comment]
@vsch Understood.  The clicking to jump to the correct location in the preview pane seems to work well.  Now that I understand the scrolling is a happy byproduct of this, but not the main focus, it makes more sense that it does not work as well.

If you do manage to make the scrolling to be well sync'd with the preview pane, I think that would be an excellent addition.  While I do a lot of editing, because I am building documentation, I also do a lot of scrolling and reading before the editing, and that would be helpful.

Thanks again!
