### ISSUE TITLE
there should no be default language injection in bare code chunks

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#445]
For some reason there's syntax highlighting in bare code chunks. But since no language is defined after the triple-backtick there should be none. 

![image](https://cloud.githubusercontent.com/assets/200952/26203847/1e474814-3bdd-11e7-993d-cb81de6c25ef.png)

**Comment by vsch** [comment]
@holgerbrandl, HighlightJS tries to guess the language when one is not supplied. I will add an attribute to fenced code without language and indented code blocks to not try to guess a language.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by holgerbrandl** [comment]
Where else than EAP would I be? :-)

Just to confirm: Works great for me. Thanks a lot for the fix/feature,.

**Comment by vsch** [comment]
@holgerbrandl, I agree with your sentiment.

On the other hand I am getting but reports from users for version 2.3.5 of the plugin which is more than 3 months old.
