### ISSUE TITLE
How does HTML export really work?

### ISSUE THREAD

**Issue by chrullrich** [vsch/idea-multimarkdown#446]
I'm having trouble getting the HTML export working:

* When I have a Markdown file open and click  the "Export Markdown as HTML" menu item, nothing happens.
* If I click the button for "Export rendered HTML as per rendering profile", one HTML file and various JS and CSS files are exported.
* If I then use the above menu item again, the previously exported files are deleted, and nothing further happens.

After turning on the "export on save" option, I get exported HTML both upon saving the file and from the "Export Markdown as HTML" option. This behavior (menu item only works if "export on save" is enabled) seems to match the documentation, which says that the menu item "will export all automatically exportable markdown files in the project", but that surely cannot be the intended effect? How would I ever export anything where that option is not enabled?

This is with 2.3.7 (enhanced) in PyCharm 2017.1.2 on Windows.

**Comment by vsch** [comment]
@chrullrich, the menu item triggers export for all files configured to export on save. It will also delete any exported files that are no longer exported on save.

The toolbar button does it for the current file regardless if it is configured to export on save.

You can configure export settings using "Profiles" and IDE scopes to control which files (or directories) should be exported and with what settings. https://github.com/vsch/idea-multimarkdown/wiki/Custom-Rendering-Profiles

**Comment by chrullrich** [comment]
Hm. I'm not sure if I get it now, but thanks for explaining again. I think I will understand it if I think about it again.

**Comment by ianfp** [comment]
I cannot figure out how to export to HTML at all. I defined a keyboard shortcut and used it, and it did nothing. I see no menu items about exporting Markdown to HTML. I have the free version -- is this a paid version-only feature? If so, why is that not obvious?

**Comment by kunambi** [comment]
Any updates on this? I, too, have a hard time figuring out how to export markdown files to HTML and/or PDF.

**Comment by vsch** [comment]
@kunambi, @ianfp, the HTML export functionality is only available in the licensed version of the plugin.

You can get a trial license to validate that the functionality works for your use case at https://vladsch.com/product/markdown-navigator/try
