### ISSUE TITLE
Exported HTML has unexpected CSS and JS URLs

### ISSUE THREAD

**Issue by chrullrich** [vsch/idea-multimarkdown#447]
HTML files exported from Markdown contain really weird CSS and JS URLs, which prevent either from working at all (intervening lines deleted):

    <link rel="stylesheet" href="../../../../..//C:/Daten/Projekte/E/ExportHTML/css/multimarkdown_layout-fx.css">
    <link rel="stylesheet" href="../../../../..//C:/Daten/Projekte/E/ExportHTML/css/multimarkdown_default-fx.css">
    <link rel="stylesheet" href="../../../../..//C:/Daten/Projekte/E/ExportHTML/css/multimarkdown_hljs-default.css">
    <script src="../../../../..//C:/Daten/Projekte/E/ExportHTML/js/multimarkdown_highlight.pack.js"></script>

Markdown Navigator 2.3.7 (enhanced) in PyCharm 2017.1.2 on Windows.

I tried setting the CSS and JS directories in the settings to relative paths (just "css" and "js"), and the result was this:

    <link rel="stylesheet" href="../../../../..//C:/windows/system32/css/multimarkdown_layout-fx.css">
    <link rel="stylesheet" href="../../../../..//C:/windows/system32/css/multimarkdown_default-fx.css">
    <link rel="stylesheet" href="../../../../..//C:/windows/system32/css/multimarkdown_hljs-default.css">
    <script src="../../../../..//C:/windows/system32/js/multimarkdown_highlight.pack.js"></script>

Apparently the paths are then considered relative to the application's working directory, which is sensible, but this result is not.

I'm sure I'm doing something wrong here, but I cannot figure out what. The references should obviously always be relative to the exported HTML, or be URLs independent from the actual file locations, or else how would you ever move the exported file anywhere?

**Comment by vsch** [comment]
@chrullrich, it looks like a bug in Windows path resolution. 

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by chrullrich** [comment]
Fixed. Thanks for the quick turnaround!
