### ISSUE TITLE
Auto-format breaks Jekyll metadata

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#448]
Using the _Format_ button in documents that contain Jekyll-metadata (e.g. for GitHub pages) will break the metadata so that it cannot be interpreted by Jekyll any more.

### Before auto-format
![image](https://cloud.githubusercontent.com/assets/3531020/26240773/81348144-3c82-11e7-959f-64ab4fba17d6.png)

### After auto-format
![image](https://cloud.githubusercontent.com/assets/3531020/26240787/90d3350a-3c82-11e7-954e-6a0b814a18d1.png)

**Comment by vsch** [comment]
@bkimminich, you need to enable the `Jekyll front matter` parser option. Without it the source is parsed as a thematic break followed by a level 2 heading.

![Screenshot_Parser_Settings](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_Settings.png)

**Comment by bkimminich** [comment]
Seems I failed at RTFM once again... 😇

Thank you!
