### ISSUE TITLE
Generate plantuml pycharm

### ISSUE THREAD

**Issue by pguichon** [vsch/idea-multimarkdown#450]
hi.
Sry for my bad english.
Thx for your awesome works.

I have a bug with plant uml.

I wrote this : 

![alt](https://g.gravizo.com/g?
 @startuml
 actor "Informatique" as dev
 actor "Personnel administratif" as administratif
 actor "Personnel pédagogique" as professeur
 actor "Etudiant" as etudiant
 node "pfsense"
 node "serveur client léger" as serveur_client_etudiant
 node "serveur client léger" as serveur_client_administratif
 cloud "Internet" as internet
 card "imprimante" as imprimante
 node "Pc Windows" as pc
 node "client léger pédagogique" as cl_pe
 node "client léger étudiant" as cl_etu
 node "DHCP" as dhcp

 dev -- imprimante
 dev -- serveur_client_etudiant
 dev -- serveur_client_administratif
 dev -- dhcp

 etudiant -- cl_etu
 cl_etu -- serveur_client_etudiant
 professeur -- cl_pe
 cl_pe -- serveur_client_administratif
 administratif -- pc
 pc -- imprimante
 imprimante -- serveur_client_administratif
 imprimante -- dhcp
 serveur_client_administratif -- dhcp
 serveur_client_etudiant -- dhcp
 pc -- dhcp
 serveur_client -- pfsense
 pc -- pfsense
 dhcp -- pfsense
 pfsense -- internet

 @enduml
)
and i have just a java error java.lang.AssertionError with a big trace.
I don't realy understand how do with plantuml.
I create a md file.
i read https://github.com/vsch/idea-multimarkdown/issues/103
but i don't have insert fragment in my text.
It's a bug or i do a mistake ?
Thx

**Comment by vsch** [comment]
@pguichon, the limitation in the plugin is that no blank lines are allowed in the multi-line URL because a blank line ends the paragraph that contains the image link.

Also, you need to add semicolons at the end of lines. The following works:

```
![alt](https://g.gravizo.com/g?
@startuml;  
actor "Informatique" as dev;  
actor "Personnel administratif" as administratif;  
actor "Personnel pédagogique" as professeur;  
actor "Etudiant" as etudiant;  
node "pfsense";  
node "serveur client léger" as serveur_client_etudiant;  
node "serveur client léger" as serveur_client_administratif;  
cloud "Internet" as internet;  
card "imprimante" as imprimante;  
node "Pc Windows" as pc;  
node "client léger pédagogique" as cl_pe;  
node "client léger étudiant" as cl_etu;  
node "DHCP" as dhcp;
dev -- imprimante;  
dev -- serveur_client_etudiant;  
dev -- serveur_client_administratif;  
dev -- dhcp;
etudiant -- cl_etu;  
cl_etu -- serveur_client_etudiant;  
professeur -- cl_pe;  
cl_pe -- serveur_client_administratif;  
administratif -- pc;  
pc -- imprimante;  
imprimante -- serveur_client_administratif;  
imprimante -- dhcp;  
serveur_client_administratif -- dhcp;  
serveur_client_etudiant -- dhcp;  
pc -- dhcp  ;
serveur_client -- pfsense;  
pc -- pfsense;  
dhcp -- pfsense;  
pfsense -- internet;
@enduml;  
)
```

**Comment by pguichon** [comment]
it's works thx
