### ISSUE TITLE
Paste image tool breaks when using an image folder.

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#452]
I have a project which I will have a lot of markdown files and rather than pollute the folder tree with lots of image files ( I don't think there is a way to hide them in Intellij project folder tool) I've tried to move them to an image folder.  

The paste image tool correctly generate a unique name for the image (which is great as there will likely be 100's to 1000's of images.)

However although it automatically detects to store them in the image folder, Non of the link styles work ( I presumably would need a repo relative link here (or file link) rather than page relative).
Instead the output. )

eg:

<img width="917" alt="screen shot 2017-06-08 at 11 43 27" src="https://user-images.githubusercontent.com/1826271/26924949-bc13643e-4c3f-11e7-897a-05e201b8719e.png">

**Comment by vsch** [comment]
@yunti, is the folder for images under the project directory or project root? It appears that the plugin is not recognizing the location properly and not adding a `file:/` prefix.

Can you give me more details of where the image directory is relative to the project?

Also, what plugin version are you using?

**Comment by yunti** [comment]
Version 2.3.7

Structure in the attached. (but one below project directory)

<img width="124" alt="screen shot 2017-06-12 at 14 24 52" src="https://user-images.githubusercontent.com/1826271/27035939-14086746-4f7b-11e7-90a4-2ae1995e091e.png">

**Comment by vsch** [comment]
@yunti, is the project also under `~/Library/Mobile Documents/.../notes`? If it is not then is the notes directory a module?

**Comment by yunti** [comment]
Yes the root project folder is `~/Library/Mobile Documents/.../notes`

**Comment by vsch** [comment]
@yunti, I think this is fixed in the latest EAP plugin release. Can you please let me know if it is still an issue for you.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment]
@yunti, I think this one is fixed in the latest release.

**Comment by vsch** [comment]
@yunti, please let me know if this is resolved when you get a chance to try this in the latest released version.
