### ISSUE TITLE
Option to hide toolbar

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#453]
I couldn't seem to find it, if it's there, but generally I work without toolbars so that it's less distracting.

Could you add an option to show hide toolbar?
Thanks.

**Comment by vsch** [comment]
@yunti, I can add this option but it would also affect the preview buttons that switch: Text Only, Preview Only, Split View with the preview type buttons: Preview, HTML, Raw HTML.

You can define keyboard shortcuts to perform these functions. Is this something that would address your needs?

**Comment by yunti** [comment]
Yes that's ideal thanks.  (I normally access all IDE tools via keyboard shortcuts with all toolbars turned off.)

**Comment by vsch** [comment]
@yunti, EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by yunti** [comment]
Excellent thanks

Barclay
