### ISSUE TITLE
 Incorrect filename inspection error

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#454]
I'm getting an incorrect file inspection error, where it's incorrectly detecting spaces in the filename.
(Note these are filename autogenerated by the image paste tool) 

<img width="356" alt="screen shot 2017-06-08 at 11 12 06" src="https://user-images.githubusercontent.com/1826271/26926291-fc7e432c-4c44-11e7-9b5d-12965f723e6d.png">

**Comment by vsch** [comment]
@yunti, it is an erroneous inspection warning. It should only apply to Wiki pages. I'll fix it.

**Comment by yunti** [comment]
Thanks

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by yunti** [comment]
Thanks I'll give it a test

Barclay
