### ISSUE TITLE
Allow search within preview

### ISSUE THREAD

**Issue by thekalinga** [vsch/idea-multimarkdown#457]
Currently there is no way to search for a given text within preview. I need to switch to edit mode to search for any string.

It would be much helpful if search can be done without toggling back between modes.

**Comment by vsch** [comment]
@thekalinga, sorry about the tardy reply. It got buried in my inbox.

The search uses the IDE text search mechanism to highlight and navigate the preview. All of the search functionality would have to be implemented in the preview. That is a very significant effort and it would need to keep up with the changes in the IDE to be intuitive.

Why don't you use the split mode so you can have both text and preview visible then you can navigate in the text and see it synchronized in the preview?

**Comment by thekalinga** [comment]
@vsch If its a lot of work, I think, Its OK with me to use the split mode.

Thanks
