### ISSUE TITLE
IntelliJ IDEA crashes after restart to activate the freshly installed plugin

### ISSUE THREAD

**Issue by Ghostium** [vsch/idea-multimarkdown#462]
Hey there,
I've just installed Markdown Navigator today. After the installation, when I restart the IDE, it gets unresponsive and then crashes.

JavaFX version: 8u111-b14-1
[File that should have rendered](https://github.com/vsch/idea-multimarkdown/files/1145489/why-commit-convention.md.txt)

The details below are taken from the [crash log](https://github.com/vsch/idea-multimarkdown/files/1145478/java_error_in_IDEA_27254.log.txt). If you need any further information just add a comment to this issue, I should respond within the next 24 hours.

Error:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcbeb3659c8, pid=27254, tid=0x00007fcbf1b7d700
#
# JRE version: OpenJDK Runtime Environment (8.0_131-b11) (build 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11)
# Java VM: OpenJDK 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjfxwebkit.so+0x19209c8]
```

Environment:
```
OS:DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"

uname:Linux 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017 x86_64
vm_info: OpenJDK 64-Bit Server VM (25.131-b11) for linux-amd64 JRE (1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11), built on May  2 2017 02:51:42 by "buildd" with gcc 6.3.0 20170406
```

**Comment by vsch** [comment]
@Ghostium, the crash is occurring in a JavaFX native library and the plugin cannot do anything about it other than not use JavaFX by switching to Default Swing Browser in settings Languages & Frameworks > Markdown > Preview.

There was previously a JavaFX had issues with SVG and PNG images that would cause a crash.

The file you provided does not have any images. Only text so there should not be an issue unless there is an issue with JavaFX.

One question is why is your JRE 8u131-b11 while the JavaFX version is 8u11-b14? These should be from the same release with the same version.

I am running UBUNTU 16.04 using the JetBrains bundled JRE:

![image](https://user-images.githubusercontent.com/10299086/28180602-946c1638-67d3-11e7-9deb-8fd3704319a9.png)

**Comment by Ghostium** [comment]
The swing renderer worked fine. I am using the JVM I've installed over apt. As JavaFX is not bundled in the openjdk-8-jre package, a separate package called openjfx is needed for JavaFX. To my surprise, the versions in the Ubuntu repository are, in fact, two different versions. 

https://packages.ubuntu.com/search?lang=en&suite=zesty&keywords=openjdk-8-jre
OpenJDK Java runtime, using Hotspot JIT 
8u131-b11-0ubuntu1.17.04.1 [security]: amd64 i386 
8u121-b13-4 [ports]: arm64 armhf powerpc ppc64el s390x

https://packages.ubuntu.com/search?lang=en&suite=zesty&keywords=openjfx
JavaFX/OpenJFX 8 - Rich client application platform for Java [universe] 
8u111-b14-1: amd64 arm64 armhf i386 powerpc ppc64el s390x

Your plugin works perfectly fine in the IntelliJ IDEA with bundled JDK version. 

The problem was either already fixed in a newer JavaFX version or the version difference is the problem. Anyways just using the bundled JVM would hide the symptoms but not solve the problem. What would you think is the right way to ask if someone forgot to update the package. E-Mail to the package maintainer, or filing an issue on their bug tracker?

**Comment by vsch** [comment]
@Ghostium, the bundled JRE from JetBrains has critical fixes, including rendering of fonts under OSX and I suspect also for Linux. Font rendering in Oracle or OpenJDK is horrible compared to JetBrains JRE so there are added benefits for using the bundled JRE.

The JetBrains OpenJDK is available for download separately. The last "stable" bundled version with 2017.1.5 is available here: https://bintray.com/jetbrains/intellij-jdk/openjdk8-linux-x86/736.21#files

You can get all versions if you know of another stable one here: https://bintray.com/jetbrains/intellij-jdk/openjdk8-linux-x86 

If you want to build from sources, if you are adventurous here: https://github.com/JetBrains/jdk8u (with actual module sources in various other projects)
 
I found that running the IDE with the bundled JRE is the best and most stable option.

**Comment by holgerbrandl** [comment]
I'm still having this crash problem on a daily basis with the current  2.3.8.28 build (and latest 2017.2.5 release of IJ): Sometimes e.g. freezes when starting up, but sometimes even when opening empty markdown files into in IJ:
![image](https://user-images.githubusercontent.com/200952/31541628-91c8b2cc-b00f-11e7-9d01-459e67d96ab5.png)

It seems indeed related to the fx-renderer, but the swing one looks old und not really pretty.

**Comment by vsch** [comment]
@holgerbrandl, from past YouTrack issues I have researched this was an issue that was related to OS X and was very hardware version dependent. The JavaFX initialization hangs waiting on native code.

Something in the native implementation was causing this issue. I thought this was fixed in the Open JDK that comes bundled with the IDE.

On the plugin side there is nothing that can be done for this other than switching to swing and loosing all the rendering improvements. Swing has a very old and partially implemented HTML renderer with a ton of limitations.

I spent a lot of time trying to improve the Swing rendering and what you have now is the best that I could get. It simply has too many limitations, quirks and un-implemented features that make quality rendering impossible.

Did you try changing the JRE for the IDE to latest Oracle version to see if the problem disappears?

I don't recommend running with Oracle because its font rendering is much worse than JetBrains bundled JRE but if the problem disappears you can open a YouTrack issue for the IDE and have JetBrains address the crash.

**Comment by holgerbrandl** [comment]
Thanks for looking into that problem.

Sorry, I did not mean to be offensive about the swing renderer. 

I'll change the jre for testing purposes and let you and jb know if it solves the problem.

**Comment by vsch** [comment]
No offense taken. Quote from the read me file at the bottom:

> It all started with a desire to see Markdown files in PhpStorm IDE as they would look on GitHub. I was already using nicoulaj/idea-markdown plugin but found its preview was more like Craig's List than GitHub. It did not appear to have been recently updated, so I decided to fork it and modify the style sheet it uses. How hard could that be?

So I fully agree with you on swing's retro, 1990's look.
