### ISSUE TITLE
Move (refactoring) of .md files breaks links to sections in same file

### ISSUE THREAD

**Issue by mirkotschaeni** [vsch/idea-multimarkdown#468]
When moving .md files (using refactor move or drag and drop, all links in the file that point to sections in the same file are broken after the move.

File a.md in folder foo
# A
 [XYZ](#xyz)
# abc

# xyz

--> move to sibling folder bar
# A
 [XYZ](../foo/a.md#xyz)
# abc

# xyz

It does not matter if the original link is just a hash link (as in the example) or if it is a relative link to the same file (i.e. a.md#xyz or ../foo/a.md#xyz).

**Comment by vsch** [comment]
@mirkotschaeni, thank you for reporting this. It is a bug. I will address it shortly and make an EAP plugin release.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
