### ISSUE TITLE
Support for local file line reference

### ISSUE THREAD

**Issue by arslancharyev31** [vsch/idea-multimarkdown#471]
Good day. For links to files, hosted on github repository, appending to file link `#L' or '#L-#L'  highlights the specified line(s) in the github website. However, this doesn't work for relative links. Moreover, in the preview clicking on the relative link with line reference doesn't open the file in the IDE itself. It would be nice if plugin could not only open such files, but also highlight specifies lines.

**Comment by vsch** [comment]
@arslancharyev31, this feature is available in version 2.3.8 and improved in latest EAP 2.3.8.10 to include conversion of "Copy Reference" strings to links with line references on paste into Markdown documents.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by arslancharyev31** [comment]
Good news. Thank you!

**Comment by arslancharyev31** [comment]
This EAP release indeed fixed the problem with opening such files. However, it does neither direct to specified line or select specified lines

**Comment by vsch** [comment]
@arslancharyev31, how are you navigating the link?

The link has two navigable parts: the file URL and the anchor. Navigating the file will only open the file and not change the caret location or selection. Navigating from the anchor ref will open the file and navigate to the start line, and select the lines if the end line is part of the link.

Clicking the link in preview will open the file on GitHub with the lines selected if the file is "under git VCS with a remote" however, if the link is `file://` format then clicking the link in preview will open the file and move caret and select the lines.

Can you please be more specific on how you are navigating the link so I can duplicate what you are getting.

**Comment by vsch** [comment]
@arslancharyev31, BTW this is how a class method reference `aClass.aMethod()` is handled in the IDE. If you navigate to declaration from the class name then you will be taken to the class declaration. If you navigate from the method name you will be taken to the method declaration.

**Comment by arslancharyev31** [comment]
@vsch, I am referencing files according to this post about [Relative links in markup files](https://github.com/blog/1395-relative-links-in-markup-files) and appending links like so: `[file.ext](directory/file.ext#L20)`. Navigation to the file works in both github and IDE markdown preview, however
in IDE it doesn't place caret to the specified line. Even if I specify a full path to local file like `[file.ext](file://C:/project-root/directory/file.ext#L20)` it still doesn't go to the specified line.

**Comment by vsch** [comment]
@arslancharyev31,

> however in IDE it doesn't place caret to the specified line

To get this behaviour you must have the caret on the anchor ref part of the node `#L20` for the above example. The anchor ref is treated as a separate element from the URL in the source.
