### ISSUE TITLE
"Apply all setext header" should just be availabe just for atx headers

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#478]
Currently it is even available on regular text which is confusing

![image](https://user-images.githubusercontent.com/200952/28641782-b1ccebc6-7250-11e7-8ce0-b1f411542864.png)

**Comment by vsch** [comment]
@holgerbrandl, the apply all intentions work on the file. Hence they will appear on any element.

Can be addressed in the following way:

1. only allow "Apply all...." intentions to show up on relevant elements 
2. change all intentions to include the relevant source element so in this case it will become "Apply all 'Change atx to setext header' in file".

Solution 1. has the advantage of not being confusing while option 2 lets you apply intentions from anywhere in the file.

What do you think is the best solution?

**Comment by vsch** [comment]
@holgerbrandl, I opted out to apply both. Now there is a Markdown setting to allow showing "Apply all ... in file" intentions on any element. By default it is disabled and the apply all intention will only show up on element it affects.

**Comment by vsch** [comment]
EAP channel updated with fix.

**Comment by holgerbrandl** [comment]
Works great, thanks!
