### ISSUE TITLE
Pressing Tab in fenced code blocks inserts 4 spaces instead

### ISSUE THREAD

**Issue by freedimension** [vsch/idea-multimarkdown#482]
I expected, that inside of fenced code blocks, indentation can be done with tabs. Instead it keeps inserting 4 spaces. There really may be reasons to use spaces outside of fenced code blocks, but what happens inside should be my choice. IMHO it should at least follow the Code Style options set for the injected language.
Using return-Key to insert a new line produces tabs if there is an indentation level.

**Comment by vsch** [comment]
@freedimension, the plugin does not yet do its own tab key processing so this is how the IDE handles tabs in injected code. 

If you edit the code fragment in a separate editor via the "Edit injected code fragment" then the editor will be that of the injected language.
