### ISSUE TITLE
Header Outline view?

### ISSUE THREAD

**Issue by lihaoyi** [vsch/idea-multimarkdown#485]
Would it be possible to include a nice outline/navigation bar while editing markdown documents? e.g. this is from the Typora markdown app:

![screenshot 2017-08-21 22 34 32](https://user-images.githubusercontent.com/934140/29523918-04c8dc70-86c1-11e7-96fc-896e7becc553.png)

You can see on the left, it pulls out all the headers, arranges them in a nice tree, and highlights the one you are currently looking at. This makes it much easier to keep track of large documents, anything more than a few hundred lines of markdown.

(BTW I tried this plugin a year or two ago and it was terribly slow. Now it's crazy fast. Great work!)

**Comment by vsch** [comment]
@lihaoyi, the plugin does support the IDEA structure view API and provides structure navigation tree.

You can see the document outline in the IDE structure view."Headers" section shows heading hierarchy.

You also have sections for Links, Images, References, Tables, Footnotes and Abbreviations showing their corresponding list of elements.

The Document section shows elements in the document in the order of their appearance. Here is a screenshot of the README.md file for this repo:

![image](https://user-images.githubusercontent.com/10299086/29560417-f843293a-86ff-11e7-9d3b-1b0e5d5c6c19.png)

**Comment by lihaoyi** [comment]
Oh cool, did not realize that at all!

**Comment by lihaoyi** [comment]
@vsch Maybe put this in the readme somewhere? I suspect I'm not the only one who didn't realize that this was available

**Comment by lihaoyi** [comment]
I mean in the big image that shows off all the features. I saw that it's in the changelog, but the changelog isn't the first place I look for what features it has

**Comment by vsch** [comment]
@lihaoyi, you are completely right. I have to add all the new features to the [Enhanced Features](https://github.com/vsch/idea-multimarkdown/wiki/Enhanced-Features) wiki. I created it to highlight the major features to help users get oriented. However, the feature set grows quite quickly with user demands and the documentation lags significantly.

I need to take some time to address the documentation. I have been updating it sporadically and it is long overdue for re-organization and update.

**Comment by vsch** [comment]
I added an issue for the Enhanced Features update #487
