### ISSUE TITLE
HTML code boundary detection fails

### ISSUE THREAD

**Issue by mfrost66** [vsch/idea-multimarkdown#49]
The following renders incorrectly in HTML (starting with #Header).  Issues are noted within sample

#Header 
```code line 1```   
```code line 2 (clipped by code box) ```

Should not be code, but is

```
should be code, but is not
```

**Comment by vsch** [comment]
@mfrost66 thanks for the parsing bug. 

I'll take a look at why pegdown parses the second code line as a verbatim block instead of inline code. That is the source of everything else because it then treats the opening verbatim of `should be code...` as the closing of the code line 2's opening inline code marker.

**Comment by vsch** [comment]
@mfrost66, as a workaround until the fix, you can change the number of back ticks for the inline to any other number than the verbatim opening block as long as the number in opening and closing match.

    #Header 
    ````code line 1````   
    ````code line 2 (clipped by code box) ````
    
    Should not be code, but is
    
    ```
    should be code, but is not
    ```

gives:
# Header 
``code line 1``   
``code line 2 (clipped by code box) ``

Should not be code, but is

```
should be code, but is not
```

this also works:

    #Header 
    ``code line 1``   
    ``code line 2 (clipped by code box) ``
    
    Should not be code, but is
    
    ```
    should be code, but is not
    ```

**Comment by vsch** [comment]
@mfrost66 you can download the fixed version from https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.1.12.6.zip. 

It also has a few other fixes in preparation for the next release.
