### ISSUE TITLE
Syntax highlighting and editor features not working

### ISSUE THREAD

**Issue by blowsie** [vsch/idea-multimarkdown#490]
For some reason, maybe an update, lots of markdown navigator features are not working at all for me anymore. 

Please advise or let me know if you require any additional information.

Windows 10 64bit
Webstorm 2017.2
Markdown Navigator 2.3.7

![image](https://user-images.githubusercontent.com/308572/29926038-29c6a7e6-8e5a-11e7-90df-0deabcf09c26.png)

**Comment by vsch** [comment]
@blowsie, are the features enabled in the parser options? For example Jekyll, Abbreviations, etc.

![Screenshot_Parser_Settings](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_Settings.png)


Does the plugin think it's license is not valid or activated? If license is valid and activated it should look something like this:

![Screenshot_Main_licensed](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Main_licensed.png)

**Comment by blowsie** [comment]
I simply copied the example for the syntax highlighting options. I woudl have expected at least some of it to work.

![image](https://user-images.githubusercontent.com/308572/29926949-c4e0eab4-8e5c-11e7-9728-4e7caa217328.png)

![image](https://user-images.githubusercontent.com/308572/29926960-cc9e64c0-8e5c-11e7-91a3-34debbf11030.png)

**Comment by blowsie** [comment]
Its worth adding that its everything in the left side, editor that Im having issues with. Not the publishing / preview.

**Comment by blowsie** [comment]
Somehow the file name ended up in the Text file type association list. Which caused the text editor to be used instead.

![image](https://user-images.githubusercontent.com/308572/29927454-56c282b6-8e5e-11e7-905b-96754f9efd65.png)
