### ISSUE TITLE
Enable autocompletion for relative links in subdirectories

### ISSUE THREAD

**Issue by koppor** [vsch/idea-multimarkdown#491]
When pressing <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to autocomplete an image link, there is "no suggestions" shown even if files are existing.

- OS: Windows
- Path separator used: `/`

![grafik](https://user-images.githubusercontent.com/1366654/30013337-3f569adc-9146-11e7-81a0-f44c33c37dec.png)

I think, the starting directory of resolution for autocompletion is not the current directory, but the root directory:

![grafik](https://user-images.githubusercontent.com/1366654/30014087-9be1f978-914a-11e7-8ddd-4cac74c7e713.png)

**Comment by vsch** [comment]
@koppor, your image link is missing the closing `)` so it is not interpreted as an image link but an image ref with some text following it.
