### ISSUE TITLE
Auto completion should offer lower case, too

### ISSUE THREAD

**Issue by koppor** [vsch/idea-multimarkdown#492]
I miss a lower case variant for auto completion of linked files:

`images/ManageExternalFileTypes.png` should propose `manage external file types`, too.

![grafik](https://user-images.githubusercontent.com/1366654/30015707-301f6254-9152-11e7-89e1-a3592030b048.png)

**Comment by vsch** [comment]
@koppor, the lowercase variants are generated but they are not shown because your caret is preceded by `Manage exter` and the IDE uses it as partial match to exclude all that don't match.

Put the caret before `Manage ... ` and you will get all the variants.
