### ISSUE TITLE
Add ability to fold headers?

### ISSUE THREAD

**Issue by lihaoyi** [vsch/idea-multimarkdown#494]
Since it seems you already extract the "structure" of the headers in a markdown document into IntelliJ's file `Structure` viewer, it would be super useful if I could use IntelliJ's code fold/unfold shortcuts to fold/unfold parts of the markdown document in the editor

**Comment by vsch** [comment]
@lihaoyi, it is on the short to do list. i will see if I can add it to the next release.

**Comment by vsch** [comment]
@lihaoyi, EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by lihaoyi** [comment]
Thanks!!!
