### ISSUE TITLE
Is it possible to make a Github-styled preview?

### ISSUE THREAD

**Issue by neochief** [vsch/idea-multimarkdown#495]
This item in feature list:

_GitHub style rendering that you are used to, out of the box_

Gives me the impression that plugin must have some way to render preview exactly as I would see them on github. Is it the case? If so, how would I turn this on? Right now without attaching some external css, I can only see the default styles.

**Comment by vsch** [comment]
@neochief, you probably have the preview browser configured as Swing. Then it is the best swing browser can do. For better preview you should switch to JavaFX WebView preview.

The plugin does show an editor annotation if you have Swing and JavaFX is available on your system, unless you turn it off.

Go to settings (preferences on mac) Languages & Frameworks > Markdown > Preview and change preview browser to JavaFX (if it is there)

If not then there is the wiki to see if you can get it working [JavaFX WebView HTML Preview Now Working](https://github.com/vsch/idea-multimarkdown/wiki/Troubleshooting-Common-Problems#javafx-webview-html-preview-not-working)

**Comment by neochief** [comment]
Thanks!
