### ISSUE TITLE
Default colors with darcular theme could be better

### ISSUE THREAD

**Issue by dkandalov** [vsch/idea-multimarkdown#5]
<img width="764" alt="ij-md-colors-screenshot" src="https://cloud.githubusercontent.com/assets/28375/9475369/2b7ede0a-4b5e-11e5-90ce-ea6ca8bf4058.png">

**Comment by vsch** [comment]
The highlighting looks like it is conflicting with the old Markdown plugin. I will rename all the classes in the next release. To solve the problem for now you have to uninstall the old Markdown plugin, not just disable it.

Here is what the theme is supposed to look like with the latest release:

<img width="927" alt="screen shot 2015-08-25 at 2 53 04 pm" src="https://cloud.githubusercontent.com/assets/10299086/9476270/bb75c174-4b39-11e5-8cfd-b34b7a2be1d0.png">

This should do the trick. Additionally, you may have some colors left over from the old darcula theme. Try selecting `Use inherited attributes' for all colors that you did not modify in settings: Editor > Colors & Fonts > Markdown.

Please let me know if this solves the highlighting on your installation.

**Comment by dkandalov** [comment]
Thanks a lot for very quick response!
You're right this is a problem with my own color scheme, not the plugin.

The reason was that custom darcular color scheme .icls file had `parent_scheme="Default"` instead of `parent_scheme="Darcula"`. After fixing this colors match the screenshot.

**Comment by vsch** [comment]
You are welcome. I am new to the plugin dev scene so some issues will come up based on my lack of experience and breadth of possibilities in the IDEA environment. However, please feel free to make suggestions and feature requests.
