### ISSUE TITLE
Trouble with proxy

### ISSUE THREAD

**Issue by cLupus** [vsch/idea-multimarkdown#501]
Is there a way to make the license lookup work through a corporate proxy?

I get the following error message:

>There was an error communicating with the license server. It is an intermittent error. You can:
>* Retry license activation
>* Continue without activating the license
>* e-mail vladimir@vladsch.com to report an issue with license activation

**Comment by vsch** [comment]
@cLupus, on some corporate networks the secure connection through a proxy causes the communications to fail. You can try turning off `Use secure connection` for license activation to see if it will work:

![Screenshot_Main_unlicensed](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Main_unlicensed.png)
