### ISSUE TITLE
Wrapped Text not aligned to left when wrapping

### ISSUE THREAD

**Issue by acrodrig** [vsch/idea-multimarkdown#503]
When writing markdown text, it would be nice to have all text aligned to the left when wrapping. Right now, as shown in the image, the text looks as if there was a hanging indent from the first line. The extra character is distracting when reading/writing text. The file line numbers to the left already give a visual indication that the line is being wrapped.

Please provide a way to turn off. Thanks!

![screen shot 2017-10-06 at 14 43 55](https://user-images.githubusercontent.com/959336/31299819-276b228a-aaa5-11e7-8d1c-b08108645c82.png)

**Comment by vsch** [comment]
@acrodrig, this is an IDE soft-wrapping issue not the plugin. If you turn off the soft-wrap and set wrap on typing for markdown (Code Style > Markdown), the plugin will do exactly that.

In the IDE, there is only an option to display the soft-wrap symbol for the current line, however the indentation remains. It just does not show the wrap symbol.
