### ISSUE TITLE
Settings file under `.idea` conflicts with source control best practices

### ISSUE THREAD

**Issue by lilred** [vsch/idea-multimarkdown#506]
See [JetBrains support: How to manage projects under Version Control Systems](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems). `.idea` is for files worth checking in, with the notable exception of `workspace.xml` and `tasks.xml`. But `.idea/markdown-navigator/profiles_settings.xml` is probably not something I want under source control - the rest of my team doesn't use this plug-in, they don't care about my settings, etc.

**Comment by vsch** [comment]
@lilred, the IDE saves project based config files under that directory. Plugins do not have control over this so you better let JetBrains know to either update their documentation or project settings persistence implementation.

At the same time if they are not using the plugin then these settings will have no effect on them and unless they routinely manipulate files in this directory they will not be the wiser.

**Comment by neochief** [comment]
As a workaround, you could add the `.idea/markdown-navigator` directory to your project's `.git/info/exclude` list. This will only affect your own project copy, so you won't need to mess with the project's `.gitignore` file.
