### ISSUE TITLE
How to be sure that HTML autogenerated link will have unchanged url 

### ISSUE THREAD

**Issue by trzye** [vsch/idea-multimarkdown#507]
Let's say that I've got  `[description](data/home/init.sql)` line in my *.md file.

After using `Export HTML as per rendering profile` I can get one of these:

1. `<a href="data/home/init.sql" class="absent">description</a> `
2. `<a href="https://github.com/ANYTHING/data/home/init.sql" class="absent">description</a> `
3. `<a href="C://ANYTHING/data/home/init.sql" class="absent">description</a> `

How to be sure to have always first point (exactly the same text as inputted in md file)? 
I just want to be able to create html document which will work without internet on different machines.

Actually my md file is inside git repository directory, and it was simple linking like at first point until first commit. After committing it is always converting as shows second point. I don't know how to revert this.

Best regards,

Michał

**Comment by trzye** [comment]
My settings

![0](https://user-images.githubusercontent.com/7382132/31590059-9fed17ec-b20a-11e7-8a18-7a6ca0bc58ef.PNG)
![1](https://user-images.githubusercontent.com/7382132/31590060-a00c88ca-b20a-11e7-99d2-14d6bac257e6.PNG)
![2](https://user-images.githubusercontent.com/7382132/31590061-a02e9992-b20a-11e7-93d2-e6dfdc795db7.PNG)
![3](https://user-images.githubusercontent.com/7382132/31590062-a04dd546-b20a-11e7-96a9-ff06e2f1a2d6.PNG)
![4](https://user-images.githubusercontent.com/7382132/31590063-a06da2ea-b20a-11e7-893f-d61d90e7e2c7.PNG)
![5](https://user-images.githubusercontent.com/7382132/31590064-a09600aa-b20a-11e7-973a-4183884a1849.PNG)
![6](https://user-images.githubusercontent.com/7382132/31590065-a0ce4fa0-b20a-11e7-87b9-a269a8c7cd01.PNG)
![7](https://user-images.githubusercontent.com/7382132/31590066-a13de518-b20a-11e7-94e8-f05098af28ff.PNG)

**Comment by vsch** [comment]
@trzye, I will have to add an option to always render links in a specific format: page relative (this is what you want), site relative (`/....`), http:// absolule, file:// absolute 

Right now if the file is on GitHub the plugin uses http:// absolute format.

I will make an EAP release and post it an update here.

**Comment by vsch** [comment]
@trzye, EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

There is a new dropdown in html export settings for the link format. It is enabled if "Link to exported HTML" is not set. 

In the next release I will improve the logic so that this setting will always be enabled but only used for all non-exported file links when "Link to exported HTML" is enabled.

**Comment by trzye** [comment]
I was using relative mapping intensively and it works great. Thank you!
