### ISSUE TITLE
About TOC, why can't generate

### ISSUE THREAD

**Issue by jamesiter** [vsch/idea-multimarkdown#508]
![image](https://user-images.githubusercontent.com/2541839/31838574-0eb7c488-b5a3-11e7-9662-8c7de55a105e.png)
![image](https://user-images.githubusercontent.com/2541839/31838593-1b194f62-b5a3-11e7-951a-276129d4c3ed.png)
![image](https://user-images.githubusercontent.com/2541839/31838625-3bd9b9d0-b5a3-11e7-8c15-026fb612d56e.png)
![image](https://user-images.githubusercontent.com/2541839/31838680-8c0acf3e-b5a3-11e7-8ea2-dc277bdd04fe.png)

**Comment by jamesiter** [comment]
My another old project. This is normal.
![image](https://user-images.githubusercontent.com/2541839/31838728-bc897534-b5a3-11e7-8fd7-b30585335a81.png)

**Comment by vsch** [comment]
@jamesiter, TOC element parsing is optional and if you don't enable it in Languages & Frameworks > Markdown > Parser then it will be treated as a reference link and that is why you are getting all the link related intentions.

Enable the Table of Contents  in Parser options and it will work like it does in your other project.

![Screenshot_Parser_TOC](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_TOC.png)

**Comment by jamesiter** [comment]
success！Thank you.........

**Comment by jamesiter** [comment]
You can close this! Thank you.
