### ISSUE TITLE
Toolbar always collapsed on small editor window

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#510]
I use a MBP with Retina display with 3 editors open + Project pane. This seems like a standard setup.

The toolbar icons are always collapsed. This is frustrating because I often just want to quickly switch between preview and output, but have to click an additional button each time.

![screen shot 2017-10-28 at 5 59 50 pm](https://user-images.githubusercontent.com/281413/32136103-d2fd5f08-bc09-11e7-9ac4-b1dab2b8854a.png)

I use `hide disabled toolbar buttons` already.

**Is there the possibility for a quick fix to always show the preview toggle buttons?**

**Comment by vsch** [comment]
@vjpr, I think latest EAP addresses this issue. 

Moved rarely used actions to popup menu buttons. #589
