### ISSUE TITLE
`Cycle split layout` shortcut stop working when `Preview Only` is selected

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#511]
I have `Command+P` set to this command. When it reaches the `Preview Only` I have to click on the preview before the key will work.

I am using FX preview.

**Comment by vsch** [comment]
@vjpr, I will take a look at it. If I remember right in the text view I had to add a change focus to have the shortcut working. I suspect I need to add something similar for the preview.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
