### ISSUE TITLE
Vertical editor/preview split

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#513]
When using 3 editors on one screen there is not much horizontal space in the editors.

I would prefer to have a vertical split.

**Comment by vsch** [comment]
Already on the todo list #260

**Comment by vjpr** [comment]
@vsch Could we have a keyboard shortcut for this?

**Comment by vsch** [comment]
@vjpr, added to EAP release, fresh off the presses. Action added, you need to define your own shortcut in Keymap > Plugins > Markdown Navigator, "Toggle Editor Split Orientation" action to toggle Vertical/Horizontal split orientation
