### ISSUE TITLE
ES6 javascript code highlighting not compatible with Github

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#514]
When I write:

Doesn't highlight correctly in multimarkdown but works on Github.com:

```
\```js
import foo from 'foo'
const foo  = 1
\```
```

Highlights correctly in MM but not on GH:

```
\```js6
import foo from 'foo'
const foo  = 1
\```
```

**Comment by vsch** [comment]
The plugin uses language name of available languages for highlighting. Some hardcoding for compatibility is added manually. For example `js` is a copy of `javascript`, `shell` is a copy of `bash`.

On my IDEA Ultimate I don't have `js6` listed as available languages.

What IDEA settings are you using for JavaScript to have `js6` configured as ES6 javascript?

**Comment by vjpr** [comment]
Hmm, just tried again and it works for `js` now.

But when I type something random it also highlights correctly...

**Comment by vsch** [comment]
That is probably a side effect of highlightjs which tries to identify the language of the code block.
