### ISSUE TITLE
Scrolling on MacBook touchpad in JavaFX preview is jumpy when scrolling past the bottom

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#515]
If I use my mouse which is set to scroll 3 lines at a time it works fine.

_Mostly_ occurs once you have scrolled to the bottom of the document.

Sometimes happens before the bottom.

**Comment by vsch** [comment]
See #488

**Comment by pzrq** [comment]
@vsch #488 is quite long so I only skimmed it, but thanks for linking to it.

I tried this plugin over the Jetbrains official one - it works great on Ubuntu PyCharm 2017.3.3!

I agree with @vjpr that there is an issue with the Macbook Pro trackpad, in that the editor window scrolls very very quickly.

**Workaround: Use the pointer to click the sidebar, then drag the sidebar.**
