### ISSUE TITLE
Invalid tool tip for "Show Breadcrumb text"

### ISSUE THREAD

**Issue by Javaru** [vsch/idea-multimarkdown#517]
In the settings, the tool tip for  "Show Breadcrumb text" says "Show notification when plugin is updated."

![image](https://user-images.githubusercontent.com/2196944/32343901-7ded3562-bfdb-11e7-8c71-2a8216c4721d.png)

**Comment by vsch** [comment]
@Javaru, thanks for catching it. I will update the tooltip.
