### ISSUE TITLE
Null on new Maven project

### ISSUE THREAD

**Issue by MarinKacaj** [vsch/idea-multimarkdown#52]
Hello,
I received a "null" message (Internal IDE Error) when opening a newly created Maven project. I don't know if Maven is related or not.
This is the stack trace:
> null
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
> java.lang.NullPointerException
> 	at com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileListUpdater$1.run(MultiMarkdownProjectComponent.java:173)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
> 	at java.awt.EventQueue.access$500(EventQueue.java:97)
> 	at java.awt.EventQueue$3.run(EventQueue.java:702)
> 	at java.awt.EventQueue$3.run(EventQueue.java:696)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
> 	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> 
>

**Comment by vsch** [comment]
@MarinKacaj, thank you for taking the time time to report this. It is fixed for next release. That whole section of code had been replaced with more efficient IDEA open api calls. 

I will be producing a new release as soon as my iMac finishes recovering Yosemite from my foolhardy venture into El Capitan. Probably some time tomorrow I will be able to upload a new release with this and a few more fixes and enhancements.

**Comment by MarinKacaj** [comment]
OK thank you.
