### ISSUE TITLE
License terms

### ISSUE THREAD

**Issue by psicho2000** [vsch/idea-multimarkdown#521]
What happens after one year license expires - does the plugin not provide enhanced features anymore? Or is it simply not possible to receive updated versions, but with enhanced features in the already installed plugin still working?

**Comment by vsch** [comment]
@psicho2000, after one year you can keep using any version of the plugin that was released before your license expired.

**Comment by psicho2000** [comment]
Thanks for the answer. So after expiration, I can still use enhanced features, but just not update anymore. Great!
