### ISSUE TITLE
Keyboard shortcut to insert fenced code block

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#522]
```
like this
```

**Comment by vsch** [comment]
@vjpr, look into Live Code Templates they already do this. You can also define `surround` templates that will allow you to select a block of lines and wrap them in a fenced code.

Fenced code mnemonic is `.codefence` but you can change it to anything you like

You can also record your own macro and assign it to a key that will insert fenced code or any other element. The IDE provides a lot of customization options so there is no need for plugins to add these features.

**Comment by vjpr** [comment]
Cool!

![screen shot 2017-11-04 at 12 37 31 pm](https://user-images.githubusercontent.com/281413/32405008-f17a68a6-c15c-11e7-816a-fe8bff6c561c.png)

**Comment by vjpr** [comment]
I'm going to leave this open actually. Usually I will create a code block up front and fill it with code. Having to use surround means you have to type something first, then use the surround shortcut. There still should be a keyboard shortcut to create the block.

**Comment by vsch** [comment]
@vjpr, 

> You can also record your own macro and assign it to a key that will insert fenced code or any other element. The IDE provides a lot of customization options so there is no need for plugins to add these features.

Why wait for the plugin to implement this action when you can spend 30 seconds and record a macro and assign it to a key, which will do it for you now?

**Comment by vjpr** [comment]
I just made a live template for ``<tab>`. This will be fine. Closing.

I've never used macros before, thanks for the tip.
