### ISSUE TITLE
Dedent shortcut not working properly

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#524]
- indent a nested list
- dedent the same list

Don't get the same results.

![kapture 2017-11-05 at 10 44 22](https://user-images.githubusercontent.com/281413/32413649-6f35c772-c216-11e7-9861-b33fc9026325.gif)

**Comment by vsch** [comment]
@vjpr, bug.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
