### ISSUE TITLE
Table sorting 

### ISSUE THREAD

**Issue by ghost** [vsch/idea-multimarkdown#525]
It would be great to sort a table column ascending / descending in my markdown. It would be much easier than sorting this by hand (obviously). 

I would really like to see this as a feature.

**Comment by vsch** [comment]
@bdiekert, did you try the [String Manipulation plugin](https://plugins.jetbrains.com/plugin/2162-string-manipulation) which has really nice sorting options including Sort Lines by Sub-Selection?

It is the reason I haven't bothered adding these options yet. The functionality offered by this plugin already does a good job.

**Comment by bdiekert** [comment]
@vsch Never heard of the plugin, but I just tested it and it works great.

IMHO I still see a feature :)

Thank you so much for your help.

**Comment by vsch** [comment]
@bdiekert, I agree it is a future feature.

**Comment by vsch** [comment]
Table Sort added:

![Screenshot_TableSort](https://user-images.githubusercontent.com/10299086/71537635-cb836400-28ec-11ea-8329-6b8255fc4f29.png)
