### ISSUE TITLE
How to use *italics* instead of _italics_ when pressing `Ctrl+I`

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#527]

**Comment by vsch** [comment]
@vjpr, at the moment there is no option for this. I will take a look if a current option can be used to determine which characters to use.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
