### ISSUE TITLE
Duplicate 3rd level headline marked as warning

### ISSUE THREAD

**Issue by tdeuling** [vsch/idea-multimarkdown#530]
The same spelled 3rd level headline in different 2nd levels are marked as warning. But the headlines are unique in their 2nd level sections.
![selection_049](https://user-images.githubusercontent.com/1298841/32931977-3684ab96-cb67-11e7-87c2-f7a23588b7f2.png)

**Comment by vsch** [comment]
@tdeuling, the heading id attribute is derived from the heading text. When two headings have the same text it results in the same id which means that the anchor reference will not resolve to a single element.

You can ignore the warning. It is only there as an indication that you can't create an anchor ref to this heading that will work as expected.

**Comment by tdeuling** [comment]
@vsch Thanks for your reply. I understand, you're right.
I just ask, because I love that 'green bar feeling' below the scrollbar so much ;) I need to ignore that.
