### ISSUE TITLE
[support request] Reset Markdown Navigator settings to defaults?

### ISSUE THREAD

**Issue by lolmaus** [vsch/idea-multimarkdown#532]
Hi! I've been using Markdown Navigator for years and I feel some of my settings have become outdated over time, e. g. an inoptimal renderer.

How do I reset them to defaults?

**Comment by vsch** [comment]
@lolmaus, Markdown Navigator settings are stored in two places: 

1. Project based settings are stored in the .idea directory in files starting with `markdown-` and in the directory `markdown-navigator` 
   
   If you delete these files then defaults will be used.

2. Application wide settings are stored in the IDE settings directory (OS specific) in the `options` sub-directory. 

   1. file `markdown_navigator.local.xml` stores non-shared settings and should not be deleted unless you want to reset everything to defaults.

    2. file `markdown_navigator.shared.xml` stores shared settings, many of which were migrated to project based settings and now these are used as project defaults. Delete this file to reset these settings to defaults.

**Comment by vsch** [comment]
@lolmaus, latest EAP has the following settings management functionality added (including reset to defaults):

* Add: #549, Add settings management functionality. Now in main settings panel there is a
  "Manage..." button in top-right corner, clicking it pops up a menu with the following options:
  * `Copy to Project Defaults`
  * `Copy from Project Defaults`
  * `Export Settings`
  * `Import Settings`
  * `Reset Settings` to reset settings to default. Project defaults, current project settings
    and markdown navigator application settings.

  These actions copy from current unsaved project settings and to current unsaved project
  settings therefore you can modify settings, copy to project defaults (or export) and then
  cancel, result will be project defaults (or exported settings) having modified settings while
  project settings being those before modification.

  If you copy from defaults or import a file followed by `Cancel` then no settings will be
  modified.

Reset will reset project defaults which means Swing browser.

You should probably configure the settings to your liking and then Export them to a file so you can easily import them into any IDE.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by lolmaus** [comment]
Thx. I've switched to VS Code, let's assume this is resolved until someone says otherwise.
