### ISSUE TITLE
Emojis do not display in preview

### ISSUE THREAD

**Issue by acrodrig** [vsch/idea-multimarkdown#538]
I cannot the emojis in the preview (see attachment). I see weird characters.

![screen shot 2017-12-12 at 5 20 59 pm](https://user-images.githubusercontent.com/959336/33913805-f36d42ec-df60-11e7-8a4d-44e89115c9af.png)

**Comment by vsch** [comment]
@acrodrig, can you please provide the markdown text with the emojis so I can duplicate this.

**Comment by acrodrig** [comment]
The following example:

```markdown
# Legend

- 📦 Backend
- 📊 Frontend
```

Renders as:

![screen shot 2017-12-12 at 5 24 57 pm](https://user-images.githubusercontent.com/959336/33913921-68151246-df61-11e7-8e89-6a4238320c90.png)

**Comment by vsch** [comment]
@acrodrig, the markdown text is showing up with the emoji images not emoji shortcut text.

![image](https://user-images.githubusercontent.com/10299086/33913985-ff50f514-df69-11e7-9c0d-2a98edf13012.png)

**Comment by vsch** [comment]
BTW, the plugin is using the https://www.webpagefx.com/tools/emoji-cheat-sheet/ list of emojis and shortcuts.

**Comment by acrodrig** [comment]
@vsch The markdown is but the preview is not!

**Comment by vsch** [comment]
@acrodrig, now I understand. You are inserting unicode into the file but are not getting it in the display.

I looked at the HTML generated and it is correct but JavaFX does not seem to properly display it.

```html
<ul>
  <li md-pos="10-23"><span md-pos="12-22">📦 Backend</span></li>
  <li md-pos="23-37"><span md-pos="25-36">📊 Frontend</span></li>
</ul>
```

However, Swing preview browser handles properly:

![image](https://user-images.githubusercontent.com/10299086/33918016-424c3f3a-df7f-11e7-95cb-d3a6f6d709fb.png)

It appears to be a JavaFX WebView issue.

**Comment by acrodrig** [comment]
I see. I switched to Swing, but there are other things Swing does not handle (like todo lists with checkboxes). Thanks.

**Comment by vsch** [comment]
@acrodrig, EAP version of the plugin has option to replace Unicode emoji with provided image links. Now you can get Unicode emoji to display in JavaFX WebView preview or Swing.

The emoji shortcuts and symbols were also updated to include the full GitHub emoji set.

Select desired emoji set in parser settings, GitHub has more symbols, best to select GitHub, Emoji Cheatsheet option which uses GitHub, and falls back to Emoji Cheatsheet when GitHub does not have the emoji. Select images so images are used not Unicode emoji characters:

![ScreenShot_parser_emoji.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_parser_emoji.png)

And enable Unicode emoji replacement with images in preview settings (last checkbox):

![Screenshot_Settings_Preview.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_Preview.png)

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
