### ISSUE TITLE
Big local images (e.g. .gif) referred to in an open .md file get locked and cause merge conflicts and issues on checkout

### ISSUE THREAD

**Issue by OleksiyRudenko** [vsch/idea-multimarkdown#539]
How to reproduce on a project under git control:
1. Create an `.md` file with text only content
2. Create new branch e.g. `branch-a`
3. Add big `.gif` (1Mb is sufficient) file to current branch and refer to it in the `.md` file (e.g. `![demo](demo.gif)` ), and commit
4. Checkout `branch-a`
Expected result:
1. The `.gif` file is not on a working tree.
2. `.md` file doesn't contain reference to the `.gif`
Outcome:
1. The `.gif` file is on working tree and its name marked red by IDE denoting it is not staged
2. `.md` file state is as expected
3. Attempt to remove the `.gif` file causes error (please, see screenshot attached).
Looks like the image file gets locked and git cannot manage it properly.

In another scenario merging from a branch that contains another version of the same `.gif` file causes merge conflicts.

Plugin settings:
 * `Settings > Languages & Frameworks > Markdown > Application settings: Disable GIF images in preview = <checked>`
 * `Settings > Languages & Frameworks > Markdown > Preview: Preview browser = Swing`

Initial frame of a big `.gif` in rendered view would be better than having a locked file...
Not a critical issue and it happens to deal with big `.gif` too often, but figuring the issue out took a plenty of time. There is a workaround: just close an `.md` file that refers to a `.gif` before any git operation, but should one neglect the rule extra efforts will be required to put things back in order.

IDE details:
```
WebStorm 2017.3.1
Build #WS-173.3942.31, built on December 12, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
![sshot-intellijwebstorm-filelock](https://user-images.githubusercontent.com/8686631/33914401-a6e6cfba-dfa6-11e7-94ab-81c45ef5d7ed.jpg)

**Comment by vsch** [comment]
@OleksiyRudenko, it definitely looks like a caching issue of the preview browsers. Disabling gif images does not work for Swing because it was added to prevent JavaFX WebView from displaying huge animations which make it hog a ton of memory.

I can add this to swing too and it will be a stop-gap measure. I don't have any control over the preview browser's implementation and can only add code to mitigate the problem.

Do you have any suggestions on how to handle this more robustly?

**Comment by OleksiyRudenko** [comment]
@vsch, thank you looking into it.
I believe making 'disable GIF' option working for Swing would do.
If it were possible to implement some behaviour based on file size, that would be great.
E.g. if image size is bigger than X Kb then display a stub saying 'the image is too big' or an initial frame from `.gif` just like default JetBrains markdown support plugin does.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by OleksiyRudenko** [comment]
Thank you!
