### ISSUE TITLE
When "Autoscroll to source" is enabled in project view, markdown navigator editor steals focus when moving through project view with keyboard arrows

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#548]
http://recordit.co/0YNiKmav91

Notice how it turns grey (steals focus to editor)

It also happens when you click on an item.

Reselecting the same item doesn't steal focus, but pressing arrow up or down does.

**Comment by vsch** [comment]
@vjpr, it steals focus to make the toolbar button shortcuts work but in this case it interferes with the function of navigation via buttons, related to #511 

I will see if I can resolve one without introducing a problem with the other.

**Comment by vsch** [comment]
@vjpr, fixed.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
