### ISSUE TITLE
applying settings - softwrap not applied until after viewed another file

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#550]
When altering the settings in markdown navigator, (eg tested with softwrap) these aren't enabled until another file is viewed (non markdown) and then returned to the original file.  This leads to a confusing experience as initially it looks like the settings changes have no impact. (note 'Apply' has been pressed but settings change still does not take affect)

(using markdown navigator 2.4.0)

**Comment by yunti** [comment]
Hmm this seems temprimental, sometimes they are applied when 'Apply' is clicked.

**Comment by vsch** [comment]
@yunti, are settings applied consistently when you press OK?

When you use Apply, the settings dialog remains open and not all updates can be done when there is a modal dialog open.

The other question is what softwrap setting are you trying and what setting?  Softwrap has: Default, Enabled, Disabled the other is Softwrap at right margin.

BTW, softwrap default/enable/disable changes are applied to all open markdown files. However, you can change between Enabled/Disabled setting on a per-file basis using right-click in the margin and selecting `Softwrap current file`.

<img width="339" alt="screen shot 2018-01-18 at 10 41 59 am" src="https://user-images.githubusercontent.com/10299086/35106467-479ae7dc-fc3c-11e7-94a3-37c6203cff20.png">
