### ISSUE TITLE
code block is not highlight

### ISSUE THREAD

**Issue by qiuyuhome** [vsch/idea-multimarkdown#552]
code block is not highlight,  and ` settings -> Stylesheet -> Scripts` is not available, can not click checkbox. 

![image](https://user-images.githubusercontent.com/17526777/35192039-4356d28c-fec4-11e7-8b6c-f7e7a9d9698f.png)

![image](https://user-images.githubusercontent.com/17526777/35192063-e95c4b94-fec4-11e7-96cf-a1ec917d666c.png)

I want to use like this:

```php
// demo
if ($a > 0) {
    var_dump($a);
}
```

But , It is this:

```
// demo
if ($a > 0) {
    var_dump($a);
}
```

Please tell me how to do . 
Thank you .

**Comment by vsch** [comment]
@qiuyuhome, Swing browser does not support scripts nor many of the other advanced features.

If you switch to JavaFX browser in Preview (two panels above Stylesheet settings) then you will have these options enabled.

**Comment by qiuyuhome** [comment]
@vsch Thank You.
