### ISSUE TITLE
Markdown Navigator checks license at every launch of AppCode

### ISSUE THREAD

**Issue by dnedrow** [vsch/idea-multimarkdown#555]
For some reason, every time I start AppCode, Markdown Navigator is attempting to check the license I have installed. The problem is that I use AppCode behind a corporate firewall and the license check fails unless I unplug from the network. I used to only have to do this once after each AppCode update.

Has something changed in this regard? Or is this unintentional? I'm using Markdown Navigator 2.4.0 with AppCode 2018.1 EAP.

AppCode 2018.1 EAP
Build #OC-181.3007.19, built on January 25, 2018
AppCode EAP User
Expiration date: February 24, 2018
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

**Comment by vsch** [comment]
@dnedrow, the license is only activated when a new version is installed. However, some users have discovered that if they use a settings repository then the local settings file which stores information about the activation gets overwritten with a version that has the activation missing.

The local settings are stored per IDE in the IDE settings directory. The plugin checks for the activation code on start up and if it is missing or expired then it will try to activate the license.

In one user's case the plugin's settings file was being overwritten with a version without the activation code. So every IDE startup it tried to activate the license.

On some corporate networks the secure connection through a proxy causes the communications to fail but non-secure works. Have you tried turning off `Use secure connection` for license activation to see if it will work:

![screenshot_main_connection](https://user-images.githubusercontent.com/10299086/35820352-593e2a04-0a73-11e8-812e-abd9a3b34545.png)

If you cannot get this resolved, please contact me by e-mail and I will do my best to find a working solution for your setup.

**Comment by dnedrow** [comment]
@vsch , thanks for the fast response. I did some testing and it does appear to have something to do with settings syncing in JetBrains IDEA-based products. Also, disabling secure connection fixed my startup issue with the license check.
