### ISSUE TITLE
Suggestion: code coloring inside ```

### ISSUE THREAD

**Issue by sebolio** [vsch/idea-multimarkdown#558]
Hi, I think it would be really useful to have code coloring in the preview, not only in the "fenced code", since github does it and is very very helpful.

**Multi Markdown:**
<img width="606" alt="captura de pantalla 2018-02-14 a la s 17 56 57" src="https://user-images.githubusercontent.com/197329/36227696-a29385a2-11b0-11e8-9c6e-ea315a8a7fcb.png">

**Github:**
<img width="453" alt="captura de pantalla 2018-02-14 a la s 17 57 52" src="https://user-images.githubusercontent.com/197329/36227890-3eb41082-11b1-11e8-8043-2ef07489b827.png">

**Comment by vsch** [comment]
@sebfindling, syntax highlighting in preview is available in the enhanced version: https://vladsch.com/product/markdown-navigator via HighlightJS or Prism.js.

Don't forget GitHub can rely on a full browser while the plugin has to make do with a Java based browser. There are some limitations. You also have the page regenerated as you type so performance is an issue.

**Comment by sebfindling** [comment]
@vsch I'm using a trial license, and it looks like the screenshot: no coloring :(

**Comment by vsch** [comment]
@sebfindling, go to settings, Languages & Frameworks > Markdown > Stylesheet and turn on either the HighlightJS or Prism.js highlighters. They are not enabled by default because they do slow down the preview generation. Prism.js a lot worse than HighlightJS

![screenshot_stylesheet](https://user-images.githubusercontent.com/10299086/36228451-3a8dbf3a-11a2-11e8-857b-fb4d7a267425.png)

**Comment by sebfindling** [comment]
@vsch all the options are disabled 🤔 i even restarted webstorm

<img width="1137" alt="captura de pantalla 2018-02-15 a la s 10 54 53" src="https://user-images.githubusercontent.com/197329/36259948-ad1e9c8a-123e-11e8-91dd-026ef8cae8f0.png">

**Comment by vsch** [comment]
@sebfindling, the options don't work for Swing browser.

If you are using 2018.1 EAP, rendering > profiles don't save CSS Text. The project profile is fine, only the rendering profiles used for scoping are affected by a bug in the IDE.

You should try the JavaFX browser. You will like it more than Swing. Not only do the task items display correctly but in the enhanced edition you can click on the check box in preview to toggle its state in the markdown source.

In the next release of the plugin, I integrated Chrome Dev Tools debugging for JavaFX WebView. Much easier to debug scripts and to add functionality on the preview side. It was a debugging blind nightmare before that.
