### ISSUE TITLE
When creating a new markdown file, how do you make it start in markdown only mode instead of markdown plus preview?

### ISSUE THREAD

**Issue by SpencerBrown** [vsch/idea-multimarkdown#560]

**Comment by vsch** [comment]
@SpencerBrown,

To change the default text/preview combination when opening a new markdown file change the `Default editor layout` to your desired configuration.

![Screenshot_Settings_Preview.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_Preview.png)

**Comment by SpencerBrown** [comment]
Thank you Vlad, your work and support on this project is exemplary. That perfectly answers my question.

**Comment by SpencerBrown** [comment]
Hi, reopening because what I was looking for was to set _editor only_ as the default for all projects. The setting you mentioned seems to be only for the current project, and I have to set it again each time I open a new project.

Is it possible to set this option globally? Thanks.

**Comment by vsch** [comment]
@SpencerBrown, settings management is implemented for the next release. You will need to use the EAP version of the plugin to get these features now. See #549 

Adds Copy to/from Project defaults and import/export project settings as xml file.

**Comment by SpencerBrownDG** [comment]
I tried this and it's not working for me.

1. enabled EAP for Markdown and updated to version 2.4.0.46
2. restarted GoLand EAP (using 2018.1 latest)
3. opened project A, changed preview to "Show editor only", works for project A
4. clicked Manage... and Copy to Project Defaults, then OK
5. restarted GoLand EAP, created new project
6. new project Markdown preview setting is "Show editor and preview", not the expected result of "Show editor only"

Am I doing something wrong here?

**Comment by vsch** [comment]
@SpencerBrown, I will verify, but it sounds like a bug with something overriding project defaults in initialization. I will try it with GoLand 2018.1 EAP and let you know.

**Comment by SpencerBrownDG** [comment]
I just tried the same sequence on WebStorm 2017.3.4 and got the same results.

**Comment by vsch** [comment]
@SpencerBrown, I probably broke some of the old code handling project defaults with new features.

**Comment by vsch** [comment]
@SpencerBrown, it was a conflict between what the IDE thinks is project defaults and the plugin. Original plugin did not have project based settings. When these were added, I could not use the IDE based project defaults because they would overwrite the non-project settings, which were now used  as project defaults.

Somewhere along the line, the IDE changed how it does this and my code broke. So my newly created project with defaults were being overwritten with the IDE's version.

This is now fixed. EAP released.

**Comment by SpencerBrown** [comment]
Thank you very much for the quick and complete resolution of this issue. I tested with the new EAP release and it works now.
