### ISSUE TITLE
'_'s are replaced by '-'s in TOC

### ISSUE THREAD

**Issue by chilek** [vsch/idea-multimarkdown#567]
How to disable this function? All headers which contain underscore characters are broken in TOC links :(

**Comment by vsch** [comment]
@chilek, by broken do you mean the anchor ref is not working?

**Comment by chilek** [comment]
@vsch yes, that's it.

**Comment by vsch** [comment]
@chilek, thank you for reporting this. I will fix it and post an update for the EAP channel here.

**Comment by chilek** [comment]
thanks for very fast response!

**Comment by vsch** [comment]
@chilek, I tried it in my dev version and it does not exhibit the problem. Can you please post a snippet of the markdown with the TOC and a heading or two. It could be combination that I am not hitting just right.

**Comment by chilek** [comment]
Original markdown:
```
# **[documents]**

## documents.add_message

```

Generated TOC:
```
- [**[documents]**](#documents)
    - [documents.add_message](#documentsadd-message)
```

I've switched to EAP channel - it updated to 2.4.0.74. The problem still persists.

**Comment by vsch** [comment]
@chilek, can you please enable `Show heading anchor id` in settings and see if they agree with what is in the generated TOC. Mine is generating the correct ids. Once you enable them, please take a screenshot of the text and post it so I can figure out what is going on.

![Screenshot_Main_licensed.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Main_licensed.png)

Other settings are in the wiki: [Application-Settings](https://github.com/vsch/idea-multimarkdown/wiki/Application-Settings)

It will look something like this:

![issue-567](https://user-images.githubusercontent.com/10299086/37420907-5baa673e-278e-11e8-8134-f1088e478d16.png)

I tried it with reference for `documents` defined and not defined. It works, so I would like to find out why it isn't working on your system.

**Comment by chilek** [comment]
Checked "Show heading anchor id" and you have the result:
![zrzut ekranu z 2018-03-14 18-52-47](https://user-images.githubusercontent.com/1457437/37421281-2fed8cb8-27b9-11e8-890b-c61d5a44904d.png)

**Comment by vsch** [comment]
@chilek, it looks right. Where does the link from TOC not work, GitHub or another markdown processor?

**Comment by chilek** [comment]
But in github wiki internal anchors are underscore preserved. For the above example from screenshot I have working example:
https://gist.github.com/chilek/d02db670670e614a3bfd60b86df2dd80

**Comment by vsch** [comment]
@chilek, OK that makes it clear. I will check and correct this. 

GitHub has been upgrading their markdown processing to CommonMark and it broke backward compatibility with a few features. I have been discovering them piece meal and by trial and error.

**Comment by vsch** [comment]
@chilek, yes they did change the handling of _. I'll fix it and release the EAP.

**Comment by chilek** [comment]
I'm looking forward for it. Thanks for great support! I appreciate your help.

**Comment by vsch** [comment]
@chilek, EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by chilek** [comment]
2.4.0.76 (EAP) resolves the problem!
