### ISSUE TITLE
Zoom of preview pane feature request

### ISSUE THREAD

**Issue by bondden** [vsch/idea-multimarkdown#57]
Thanks for the so waited feature of live preview! It's great, synchronization with code view works better, than anywhere else, I`ve seen, and the #54 is announced to be fixed in the next release.

But what about zooming the preview pane?

**Comment by vsch** [comment]
@bondden it has been available for a while in the JavaFX WebView based preview. #56 #27 

The Swing based preview, what I call 'Old Preview', does not support zooming.

**Comment by vsch** [comment]
@bondden, #54 is also labeled as 'fix available' which I use to mark fixed bugs for which interim releases exist that you can download from the repo if you need the fix before the release is made to the official plugin repository. #54 has a link to the zip file you can download and then install using Settings > Plugins > Install  plugin from disk...

**Comment by bondden** [comment]
@vsch, thank you very much!
