### ISSUE TITLE
Can not fix typo in header

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#571]
Example
```
### There's a fascinating edcosystem out there, ready to be unleashed on your data
```
![image](https://user-images.githubusercontent.com/200952/37605834-5f1b98a2-2b94-11e8-9626-ee82c0b2a5f0.png)
![image](https://user-images.githubusercontent.com/200952/37605842-62eeda16-2b94-11e8-808d-da1734a5398d.png)
Now I'd expect the spelling dialog but instead I get
![image](https://user-images.githubusercontent.com/200952/37605871-6f7b5c50-2b94-11e8-860c-b9a007107d2a.png)
It's actually possible to fix the typo in the rename refactoring dialog, but it lacks some UX imho.

**Comment by vsch** [comment]
@holgerbrandl, I'll see if I can have both the fix typo and rename. The heading is a named element and `typo: rename to` will retarget any anchor refs to it, whereas `typo: change to` will not.

Why don't you use the drop down? It has the spellchecker suggested fixes applied to the header text:

<img width="795" alt="screen shot 2018-03-19 at 9 01 46 pm" src="https://user-images.githubusercontent.com/10299086/37630067-c3be087a-2bb8-11e8-860e-1eb00dea6034.png">

I actually spent a lot of time figuring out how to make it work. ;)

**Comment by holgerbrandl** [comment]
I actually would prefer the per word built-in spelling correction, because otherwise I have to review the complete phrase for other unintended false positive typo corrections.

**Comment by vsch** [comment]
@holgerbrandl, I added an option to Languages & Frameworks > Markdown:

* Add: `Use rename for spelling error intention` to allow turning off `Rename to:` spellchecking  intention and use the regular `Change to:` intention.

Disable it to get the default behaviour.

**Comment by holgerbrandl** [comment]
Thanks. What would a user gain from renaming a section with refactoring? There are section cross-references but they typically need some normalized header (like from the generated TOC).

**Comment by vsch** [comment]
@holgerbrandl, if you refer to a header from another file using an anchor ref. Changing the header text changes the anchor, using refactoring the link in the other file is changed. Using text change it does not.

The same applies to links within the file to headers.

**Comment by holgerbrandl** [comment]
Nice, thanks for the explanation.

>
