### ISSUE TITLE
Preview Horizontal / Vertical should be toolbar buttons

### ISSUE THREAD

**Issue by skewty** [vsch/idea-multimarkdown#573]
When I switch from my landscape oriented monitor to my portrait monitor I like to switch where the preview text is displayed.  This would be much more convenient if there was one toolbar button for portrait preview and another for landscape preview.

**Comment by vsch** [comment]
@skewty, how do you make the switch? Is it dual monitor system and you drag the IDE window between monitors or is it different systems?

The reason I ask is if it is on different systems then a setting to choose layout based on width/height ratio would do it automatically.

In either case I will add actions: set horizontal, set vertical and toggle vert/horiz layout. That way they can be assigned to keys.

I can then add the toggle vert/horiz layout action to the toolbar.

**Comment by vsch** [comment]
@skewty, there is an action "Toggle Editor Split Orientation" available so you can assign a keyboard  shortcut to it in settings > KeyMap > Plugins > Markdown Navigator

I also added a toolbar button for the orientation on the right toolbar for the next EAP release.

<img width="227" alt="screen shot 2018-05-06 at 7 38 49 pm" src="https://user-images.githubusercontent.com/10299086/39679025-86cf045a-5165-11e8-9f31-24421ae83e2b.png">
