### ISSUE TITLE
Toolbar button to open html code in Browser

### ISSUE THREAD

**Issue by skewty** [vsch/idea-multimarkdown#574]
Recently I wanted to print the "Preview" of a Markdown document and I can't seem to find an easy way to do this either inside Markdown Navigator or by easily opening the HTML / CSS to a place where I can open it in my Browser.  Perhaps a toolbar button to open in default IDEA browser or to print using IDEA itself.

**Comment by vsch** [comment]
@skewty, print is available in the JavaFX preview. Swing does not have print function.

![print_preview 2x](https://user-images.githubusercontent.com/10299086/37623118-f6c78d14-2b99-11e8-896c-b71a0dc55b5a.png)

or the dark scheme:

![print_preview 2x_dark](https://user-images.githubusercontent.com/10299086/37623130-003a8e5a-2b9a-11e8-9bdc-8feaf592bfa1.png)
