### ISSUE TITLE
Add feature to move table columns

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#577]
1. Easiest: move column left or right actions
2. More work: copy, cut, paste column
3. Harder: copy, cut, paste multiple columns
4. Hardest: add table editor to edit tables similar to Excel and Numbers where columns/rows could be selected/moved/copied etc.

**Comment by dkellenb** [comment]
Already just option (1) would bring a huge benefit. In my case i have actually only tables without column spans. In a first version you could just offer the functionality if there are no column spans.

**Comment by vsch** [comment]
I will add it to the next EAP release.

**Comment by vsch** [comment]
@dkellenb, EAP update with a fix for the issue is available.

Table actions added for move column left/right

<img width="257" alt="screen shot 2018-08-28 at 8 22 56 pm" src="https://user-images.githubusercontent.com/10299086/44758089-78cf4780-ab00-11e8-8e95-ca84b9dcf9c1.png">


To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by dkellenb** [comment]
Works great! Thank you.
