### ISSUE TITLE
"unresolved wiki page reference" when using links with anchors to the same page

### ISSUE THREAD

**Issue by mauricio-medeiros** [vsch/idea-multimarkdown#58]
If you have a page called "test-page.md", and try to put a link inside that page pointing for example to `[[test|test-page#someanchor]]`, the link is reported as missing in the IDE.

Without the anchor it works fine.

**Comment by vsch** [comment]
@mauricio-medeiros thank you for reporting this. It is now fixed for next release. The next release will come out in a few days.
