### ISSUE TITLE
Image file refactoring changes name but not reference

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#580]
When renaming an image file (Shift-F6) at an image reference/usage site in a markdown document, the file is being renamed, but the image reference ist not.

Example: before
![image](https://user-images.githubusercontent.com/200952/38732617-1b0b84a8-3f1f-11e8-8b1a-d78855925d4a.png)

after
![image](https://user-images.githubusercontent.com/200952/38732685-5d85f2fa-3f1f-11e8-984e-62a1995ad514.png)

**Comment by vsch** [comment]
@holgerbrandl, several times I have spent hours debugging this exact use case only to realize that I did not select the `Search for references` check box. Now it is ingrained into me.

Check the Search for references and it will work.

**Comment by holgerbrandl** [comment]
Stupid me. But it must be the late Friday afternoon (to blame somebody else at least). Thanks for the help.
