### ISSUE TITLE
vertically align synchronized position of preview

### ISSUE THREAD

**Issue by mike-b-roberts** [vsch/idea-multimarkdown#581]
Using version 2.5.2 of Markdown Navigator (paid licence version) and PyCharm Community Edition 2017.3.3:
The vertical position of the `.md` file being edited and the preview are not aligned or synchronised using the `Default - Swing` browser, although alignment seems to work fine in `JavaFX WebView`.

This or a similar bug is listed as fixed in this version #Fix 561

**Comment by vsch** [comment]
@mike-b-roberts, the synchronized scrolling does not work for Swing browser. The bug fix was for JavaFX for a feature broken in an EAP release.

I could not find a reliable way of getting it to work and gave up, after many wasted hours. This seems to be the story of trying to implement features for Swing browser.

Is there a reason you are using Swing instead of JavaFX?

**Comment by mike-b-roberts** [comment]
Thanks for your quick response.
Swing is the default. And I prefer the look of it, but without synchronised scrolling it's not much use, so I'll revert to JavaFX.

**Comment by vsch** [comment]
@mike-b-roberts, You can get the swing look in JavaFX by switching to JavaFX in Preview settings and then in Stylesheet settings select "Default Swing Stylesheet". JavaFX can use swing stylesheets but not the other way around.

<img width="1005" alt="screen shot 2018-04-16 at 12 04 04 am" src="https://user-images.githubusercontent.com/10299086/38789656-c732f57c-4109-11e8-91ad-540c29c3a28f.png">

**Comment by mike-b-roberts** [comment]
@vsch Thanks Vladimir, that will work for me.

**Comment by vsch** [comment]
@mike-b-roberts, you can also change the HTML Generation options to not generate the page header/wrapper to have plain rendering without extras:

<img width="968" alt="screen shot 2018-04-16 at 12 15 43 am" src="https://user-images.githubusercontent.com/10299086/38789901-5781ec7c-410b-11e8-85af-e8d330e10436.png">
