### ISSUE TITLE
User defined profiles not available

### ISSUE THREAD

**Issue by ddnexus** [vsch/idea-multimarkdown#582]
It looks like only the built-in profiles are available. I can create a new profile for a dir, then I cannot choose it in the Rendering settings because it does not appear in the drop-down (which shows only the built-in Project Files, All, Non-Project Files, ...)

RubyMine 2018.1
Build #RM-181.4203.562, built on March 28, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-15-generic

**Comment by vsch** [comment]
@ddnexus, you need to associate the custom profile with an IDE scope. There is a convenient link in the settings pane to take you to the relevant IDE page where its done. After creating the scope, come back and select it from the drop down, and select the profile you want to associate with it.

<img width="913" alt="screen shot 2018-04-17 at 12 26 46 am" src="https://user-images.githubusercontent.com/10299086/38848635-21dc2396-41d6-11e8-99a3-5d8eca7bfe0a.png">

**You need to be aware that ALL 2018 IDEs have a bug when saving rendering profile settings for the plugin.** They will loose all text fields if they contain whitespaces (ie. spaces or EOL). Which basically means all custom css and html content. See https://youtrack.jetbrains.com/issue/IDEA-184506, if you are affected, feel free to vote it up and/or complain to JetBrains. I provided a patch Feb 25th, however it has not made it into the release.

**Comment by ddnexus** [comment]
Thanks for the fast answer.
When you say "an IDE scope" you mean a built in scope or a custom scope (for example a single dir of files)? 
Because I create an IDE custom scope called "docs" which refers to <project-didr>/docs, and I would like to use that scope to apply a Rendering profile called "docsprofile". 

However there is no "docs" scope in the dropdown, only Project Files, All, Non-Project Files, ...

**Comment by vsch** [comment]
@ddnexus, I think you need to make the scope shared so the plugin will see it. I tried creating a shared scope and it shows up. I have not tried a non-shared scope.

I use scopes to customize profiles all the time for generating HTML project files from markdown. I hate bit-banging HTML, even for a short package description. Unfortunately, 2018 does not work for that without patching.

**Comment by vsch** [comment]
@ddnexus, can confirm that you need to make the scope shared. The profile settings are project settings. If you don't share the scope they are not visible to project based config elements.

**Comment by ddnexus** [comment]
Yes! you are right. Thank you!!!
