### ISSUE TITLE
Bar only gives me one feature

### ISSUE THREAD

**Issue by dschinkel** [vsch/idea-multimarkdown#586]
Wondering why basically all options are greyed out here:

<img width="774" alt="screen shot 2018-04-26 at 2 51 36 pm" src="https://user-images.githubusercontent.com/338798/39328593-6d214f38-4961-11e8-95f6-a2a54f7cc748.png">
<img width="849" alt="screen shot 2018-04-26 at 2 52 57 pm" src="https://user-images.githubusercontent.com/338798/39328629-8b6ab18c-4961-11e8-8003-35b39a9121c4.png">

What's not clear to me looking at your prod and this github repo is what features I should be seeing working in the free version.  Right now it's only hyperlinking.

**Comment by vsch** [comment]
@dschinkel, basic version has limited parse tree building limited to syntax highlighting but not full parsing required for the toolbar manipulation of the markdown text.

The basic version is geared for minor editing and mostly for markdown rendering of existing documents. It can be used to edit markdown but with limited assistance.

The enhanced version has full implementation of completion, navigation, refactoring, formatting, etc. Making markdown a full featured language of the IDE.
