### ISSUE TITLE
can't display unicode 𠃩 in preview

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#594]
![2018-05-09-03-59-49-3](https://user-images.githubusercontent.com/167966/39780261-56c95d34-533e-11e8-9c4a-025af1fcf783.jpg)

**Comment by vsch** [comment]
@bluelovers, it looks like the JavaFX WebView preview is not able to handle the particular unicode code point. It has a few issues with unicode code points, especially new ones.

However in this case this UTF-8 character is claimed not part of the Unicode standard yet, according to https://www.utf8icons.com/character/131305/UTF-8-character

Swing preview browser displays it correctly.

JavaFX WebView will display it correctly if it is converted to an HTML entity first: `&#x200E9;`

The next character 𠃪 with entity value of `&#x200EA;` does not display in WebView in either form, but does display correctly in Swing. Same for the immediately preceding character.

You will have to use the Swing preview browser until JavaFX WebView addresses rendering of these characters correctly.

**Comment by vsch** [comment]
![screenshot_settings_previewbrowser](https://user-images.githubusercontent.com/10299086/39781979-b9dd0b60-52de-11e8-8cff-6c49b550d3fa.png)
