### ISSUE TITLE
PDF Generation Silently Fails when PDF file locked

### ISSUE THREAD

**Issue by preeder** [vsch/idea-multimarkdown#595]
I had the output PDF open in Microsoft Edge browser on Windows 10.  I did not know, but Edge seems to lock the file when opened.  Attempting to export to PDF, I got the "[file] already exists.  Do you want to replace it" warning.  After clicking "Yes", there were no errors, but the PDF file was not written to.

I would expect that this would fail because Edge has the file locked, but there should be a an error alert and perhaps returning to the file picker dialog box to choose a different file name, as is standard for other applications.

**Comment by vsch** [comment]
@preeder, thank you for reporting it. I will have to check but suspect that the exception is being absorbed somewhere inside the implementation and needs to percolate up the call tree.

**Comment by vsch** [comment]
@preeder, fixed, now showing file path and error message from the exception.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/10299086/51679242-63c1ec00-1fac-11e9-833c-3f0e1bd53728.png">

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
