### ISSUE TITLE
Table formatting broken

### ISSUE THREAD

**Issue by ddnexus** [vsch/idea-multimarkdown#598]
I read the issue #435, and mine is similar, with many different lengths of the last column.
No way to fix it. I removed all the bold and other formatting but the problem i still there.

**Comment by ddnexus** [comment]
It looks like the problem is generated by the presence of links in the column. The columns without links work OK.

**Comment by vsch** [comment]
@ddnexus, if it wouldn’t be too much trouble, could you please provide a cut/paste sample of the markdown table source and a screenshot of what it looks like on your system.

**Comment by ddnexus** [comment]
It's quite difficult to show you. Either the last "|" are in completely arbitrary places, or all of a sudden the automatic alignment of colums stops working.
Here is a file how it should be:
```
| A   | B                             | Links                        |
|:----|:------------------------------|:-----------------------------|
| `a` | Text text text text text text | [a](https://github.com/a.rb) |
| `b` | Text text text text text text | [b](https://github.com/b.rb) |
| `c` | Text text text text text text | [c](https://github.com/c)    |
```
and here it is how it is when the automatic alignment is working (but faulty):

```
| A   | B                             | Links                                                                                |
|:----|:------------------------------|:-----------------------------------------------------------------------------------------|
| `a` | Text text text text text text | [a](https://github.com/a.rb)                                                              |
| `b` | Text text text text text text | [b](https://github.com/b.rb)                                     |
| `c` | Text text text text text text | [c](https://github.com/c)                                                       |
```
A clue: copying and pasting it into another editor may result in an arbitrary number of not printable characters (that ugly little squares) before and after the links. I cannot reproduce it now because the column alignement does not work, so it treat the tables as normal text.

**Comment by vsch** [comment]
> I cannot reproduce it now because the column alignement does not work, so it treat the tables as normal text.

@ddnexus, if the table is treated as normal text it means that there is something in the text preventing it from being recognized as a valid table.

Can you copy the table into a separate markdown file so that you can make it available to me for debugging. There are some extra characters in there causing an issue. The unprintable characters are a sign of something extra in the text.

Pasting it into GitHub comment will not work because the text will be cleaned by GitHub.

**Comment by ddnexus** [comment]
[sample bad markdown.txt](https://github.com/vsch/idea-multimarkdown/files/2046697/sample.bad.markdown.txt)

**Comment by ddnexus** [comment]
> I cannot see how this could be left in the text after wrapping but then these are the famous last words before every bug. If I could foresee the conditions then I would have already added code to avoid it.

Could I use it as a quote in the signature of my emails? :)

I never had a problem with zero width character before. I saw many of them in many of the md tables now, but I am wondering if that could be caused by the interaction of some other plugin. 

BTW, even removing them, I get no auto formatting in columns. Why? Did I miss some setting?

**Comment by ddnexus** [comment]
OK, thanks for the settings. So I install the zero-width plugin, removed all the bad chars, then I went to the settings and activated the setting (that for some reason got disabled). At this point, as soon as I type anything in the table, I got a lot of added character picked up by the zero-width plugin. I remove them again and try to type, and again got the extra chars and the align is screwed up.

**Comment by vsch** [comment]
@ddnexus, this is interesting. There must be something in your system that is different and causes the problem.

1. Are you getting any exceptions?
2. What IDE and version are you using?
3. Can you give me a list of custom plugins you have installed. You can get it in settings > plugins  by selecting custom from the Show: drop down. You only need to give me ones that I don't regularly use:

<img width="776" alt="image" src="https://user-images.githubusercontent.com/10299086/40661245-3a14ac50-6321-11e8-8911-1c729d8ad1e7.png">

**Comment by vsch** [comment]
@ddnexus, thank you for the information. I don't use Ruby Mine except when trying to duplicate bugs so I will try it first on OS X and failing to duplicate the problem will run it on Linux under parallels. It could be something different about Ruby Mine that is causing this.

**Comment by vsch** [comment]
@ddnexus, I was not able to duplicate this issue. It could be induced by a conflict or interaction with another plugin.
