### ISSUE TITLE
No table support

### ISSUE THREAD

**Issue by debovitch** [vsch/idea-multimarkdown#6]
# Blah blah

Blah blah

Blah blah

| Blah               	| Blah                                                                                                                                                      	|
|-------------------	|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| Blah                 	| Blah                                                                                                                                                      	|
| Blah            	| Blah                                                                                                                            	|
| Blah             	| Blah                                                                                                                                              	|
| Blah             	| Blah                                                                                                                                             	|
| Blah 	| Blah 	|

![capture d ecran 2015-08-28 a 12 25 02](https://cloud.githubusercontent.com/assets/14014089/9544306/e1ec2422-4d7f-11e5-8ea8-ee6b5001cd78.png)

**Comment by vsch** [comment]
GitHub comments are processed as Markdown. So you need to use fenced code blocks around Markdown source or they will be processed and hard to figure out what the original text was. You would need to write to make the original text accessible:

    ```
    Blah|Blah||------------
    |-----------------------------------
    || Blah || Blah || Blah || Blah || Blah || Blah
    ```

There are two issues you are encountering:

1. The second table has a few errors in it that makes it not a valid table for Markdown

    ```markdown
    Blah|Blah||------------
    |-----------------------------------
    || Blah || Blah || Blah || Blah || Blah || Blah
    ```

    1. You need to have no `-` in the table header columns.
    1. You need at least one `|` after the `-` in the divider:
        * GitHub requires that you have at least two columns and it takes a minimum of `---` for it to be recognized as a column.
    1. You cannot start a table row with `||`

    ```markdown
    Blah|Blah||
    |-----------------------------------|
    || Blah || Blah || Blah || Blah || Blah || Blah
    ```

    change it to

    ```markdown
    Blah|Blah|
    |-----------------------------------|---
    | | Blah || Blah || Blah || Blah || Blah || Blah
    ```

    even then most parser will not accept it. Try a real table instead of a quick random one.

2. The screenshot is of `Markdown Support` plugin from JetBrains, not `MultiMarkdown`.

    * Markdown Support

    <img width="601" alt="screen shot 2015-08-28 at 8 52 31 am" src="https://cloud.githubusercontent.com/assets/10299086/9547030/52d25cee-4d65-11e5-90f3-0743066b4667.png">

    * MultiMarkdown

    <img width="591" alt="screen shot 2015-08-28 at 8 55 37 am" src="https://cloud.githubusercontent.com/assets/10299086/9546995/0f5ae422-4d65-11e5-8b44-57d09f74d0dd.png">

    * Markdown Support needs to be Disabled, so MultiMarkdown can display its tabs.

    <img width="869" alt="screen shot 2015-08-28 at 8 48 55 am" src="https://cloud.githubusercontent.com/assets/10299086/9546968/d2b8c232-4d64-11e5-8e11-a9425d310e47.png">

    * Additionally, you can select Darcula in Settings: Other Settings > MultiMarkdown to have your HTML Preview in Darcula:
     
    <img width="869" alt="screen shot 2015-08-28 at 8 49 37 am" src="https://cloud.githubusercontent.com/assets/10299086/9547015/330caf90-4d65-11e5-920d-562df9ef824b.png">

     To get a preview that looks like this:

    <img width="597" alt="screen shot 2015-08-28 at 9 00 54 am" src="https://cloud.githubusercontent.com/assets/10299086/9547060/9e88c600-4d65-11e5-87cc-53456f11d958.png">

Hope this helps get you on the right track.
