### ISSUE TITLE
Support for system specific protocol handlers

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#605]
It would be great if URLs like `file://` `papers://` or any type of locally registered protocol handler could be opened from the preview.

Currently nothing happens when clicking them in the preview.

![image](https://user-images.githubusercontent.com/200952/41338338-2e247cc2-6ef2-11e8-8abe-ad6f60df66cc.png)

**Comment by vsch** [comment]
@holgerbrandl, did not consider this. I will add it.

**Comment by habemus-papadum** [comment]
very good idea!

**Comment by vsch** [comment]
Now the custom protocol URIs are passed through to the IDE browser launcher.

Please let me know if it works for your use case.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment]
Works great, thanks a lot for the fix.

**Comment by holgerbrandl** [comment]
Would it be possible to extend this feature to also support protocol handler that start with a capitalized letter? E.g when copying links from IBM Lotus Notes, links have the format `Notes://myserver/C12569D/1003369E8` which currently cant't be opened from the preview nor the code.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
