### ISSUE TITLE
Animated gif does not show up in javafx preview

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#609]
Example snippet
```
![](https://cdn-images-1.medium.com/max/800/1*bkFlVrrm4HACGfUzeBnErw.gif)
```

Screenshot
![image](https://user-images.githubusercontent.com/200952/41726857-532a0d2a-7573-11e8-93e6-9855d3ae2fac.png)

**Comment by vsch** [comment]
@holgerbrandl, there is an option to disable GIF display in preview. 

Before enabling you should be aware of #350 and #539. Disabling GIF is a mitigation measure.

<img width="1046" alt="screen shot 2018-06-21 at 10 53 30 am" src="https://user-images.githubusercontent.com/10299086/41727071-7a244f80-7541-11e8-9292-5c17cd547782.png">

**Comment by holgerbrandl** [comment]
Seeing the tickets, I'll stick to the defaults. Sorry for the tracker spam.
