### ISSUE TITLE
How to use "Go to Declaration" to navigate to relative links 

### ISSUE THREAD

**Issue by habemus-papadum** [vsch/idea-multimarkdown#613]
I feel like this must be easy but I can't figure it out.

If I have 
`- [AWS](cs/AWS.MD)`  as a relative link, if I try to execute `Go to Declaration` with the cursor on the relative URL `cs/AWS.MD`, I get a message stating 'No Usages Found' though the file exists (in fact the plugin created if for me.)  Is this supported, or am I doing something wrong?

Similarly, if I do not seem to get auto complete when typing a relative url to a file that already exists -- is this supported?  

Currently the only thing that seems to work is that the plugin can detect links that do not exist and offer to create files.

**Comment by vsch** [comment]
@habemus-papadum, I just tested it and the plugin expects the markdown extension case to match. I will look into where the case sensitivity is causing this but for now if you change the extension to a lower case `.md` it should work.

This is a bug because even if the file is not a recognized markdown file, go to definition on a link targeting the file should take you to the file.

**Comment by habemus-papadum** [comment]
@vsch 
Yes -- the capitalization was the issue, thanks!.  It is easy for me to work around.  

When I try auto-complete with `Ctrl-Space`, I am not seeing completions:
![screen shot 2018-06-29 at 5 00 16 pm](https://user-images.githubusercontent.com/1161604/42114741-2abf2306-7bbe-11e8-9b1f-27e3c57e5dd0.png)

Is this behavior correct?

Thank you very much for your assistance!

**Comment by vsch** [comment]
@habemus-papadum, the link needs a closing `)` before link address completions will work. 

You can use the insert link action (^L) to insert a blank link or live templates defined for markdown (.link) to do the same thing. Then completions will work.

**Comment by habemus-papadum** [comment]
Yup, That's it -- Thanks!
