### ISSUE TITLE
Preview strips XML-tag-like things from code blocks when source code is selected

### ISSUE THREAD

**Issue by reitzig** [vsch/idea-multimarkdown#614]
When I select some text in the source pane, everything that looks like an XML tag is stripped from code blocks:

![2018-07-02 13 19 55 screenshot](https://user-images.githubusercontent.com/4246780/42161399-27d8d8e6-7dfb-11e8-8648-55edb865fec3.png)
![2018-07-02 13 20 07 screenshot](https://user-images.githubusercontent.com/4246780/42161400-27f7c3fa-7dfb-11e8-86eb-bcb45a84c71e.png)

Also affects unfenced (i.e. indented) blocks.

Fun fact: `<*>` seems to be a special case.

This is with Markdown Navigator 2.5.4 in IDEA 2018.1.5.

**Comment by vsch** [comment]
@reitzig, support for showing selections in preview is heuristic and requires adding spans to generated HTML. I will take a look at the code to figure out what causes the stripping out of embedded tags.

It looks like a bug.

**Comment by reitzig** [comment]
Oh my. I thought it'd manipulate the "real" selection. Juggling spans around, no wonder things break sometimes. O.o

**Comment by vsch** [comment]
@reitzig, the same mechanism is used to highlight search highlights and multiple selections.

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/10299086/42243710-40ffc830-7ee0-11e8-8150-7406240bcb19.png">
