### ISSUE TITLE
Refactoring doesn't work in Rider

### ISSUE THREAD

**Issue by ipanin** [vsch/idea-multimarkdown#617]
Refactor -> Rename doesn't work in Rider. I cant rename file with all references to it.

**Comment by vsch** [comment]
@ipanin, usually this is caused by not having the "Search for references" checked in the file rename dialog:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/10299086/42341225-5422d502-8060-11e8-8c1c-469aa29c2a7c.png">
