### ISSUE TITLE
Emoji suggestions do not filter as you type

### ISSUE THREAD

**Issue by jcfranco** [vsch/idea-multimarkdown#624]
Non-matching suggestions should be filtered out.

![emoji-suggestions](https://user-images.githubusercontent.com/197440/43474089-bb4c2bb6-94a6-11e8-992e-53be29d92816.gif)

**Comment by vsch** [comment]
@jcfranco, it actually works right if you create an empty emoji shortcut `::` and place the caret between the colons before doing completion.

I will take a look at the issue. It is trying to simulate an emoji shortcut without the closing colon. I think this is the issue.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by jcfranco** [comment]
Works great, thanks!
