### ISSUE TITLE
Navigate from preview to editor

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#625]
Not sure how difficult this would be to implement, but it would be nice if I could select some text in the preview window (for example, by clicking on it, or highlighting some text), and the cursor would move to the corresponding section in the editor window. [Overleaf](https://www.overleaf.com) has has this feature where you can click on the PDF preview, and the cursor is automatically moved to the same position (or as close as it can approximate) in the editor. It's really convenient.

**Comment by vsch** [comment]
@breandan, click synchronization is already there for JavaFX WebView browser. 

You need to enable it:
<img width="934" alt="screen shot 2018-08-08 at 8 05 43 am" src="https://user-images.githubusercontent.com/10299086/43836014-f5a3c6f2-9ae1-11e8-9973-2bc46d93912b.png">

**Comment by breandan** [comment]
Awesome! I was using the JavaFX Preview, but perhaps this was not enabled. Thanks.
