### ISSUE TITLE
First backspace removes indentation

### ISSUE THREAD

**Issue by ralfbs** [vsch/idea-multimarkdown#626]
When I hit backspace in an sub level entry of a list, the plugin reduces the indentation level by one character upon the first hit. With any consequent hit the backspace button on my mac works fine. 
Example, where | shows the cursor, _ = whitespace:

```markdown
- some text
________- some indented text|
```

after first hit on backspace (no character deleted, but whitespaces from the left are removed):

```markdown
- some text
______- some indented text|
```

This is pretty annoying - any chance to switch this behavior off?

Thanks a lot in advance!

**Comment by vsch** [comment]
@ralfbs, what plugin version are you using?

I tried this on the latest EAP and I am not getting this behavior:

![backspacelistitem](https://user-images.githubusercontent.com/10299086/44460468-31662a00-a5db-11e8-836f-d70ddb0d929b.gif)

As a workaround you can disable format as you type by clicking on the toolbar button: <img width="32" alt="image" src="https://user-images.githubusercontent.com/10299086/44460485-3f1baf80-a5db-11e8-99d6-c04fe5c0331a.png"> to deselect it.

Also, you can try the latest EAP plugin release to see if this is an IDE version related issue.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by ralfbs** [comment]
Hi Vladimir,
 
thanks for the swift response!
 
Disabling the ‘format as you type’ did the trick for me. Super!
 
However, using the EAP version does not change anything – still I get the behavior as outlined.
 
FYI: I am at version 2.5.4.18 in PhpStorm on Mac
 
Thanks a lot 
 
Best regards
Ralf

**Comment by vsch** [comment]
@ralfbs, what version of PhpStorm? I tried 2018.2.2 EAP

PhpStorm 2018.2.2 EAP
Build #PS-182.4129.18, built on August 15, 2018
Licensed to Vladimir Schneider
Subscription is active until October 10, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Can you copy/paste your PhpStorm about box information so I can try to duplicate your configuration.

**Comment by ralfbs** [comment]
@vsch, please find below my PhpStorm Info:
PhpStorm 2018.2.1
Build #PS-182.3911.43, built on August 8, 2018
Licensed to Ralf Schneider
Subscription is active until October 13, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by vsch** [comment]
@ralfbs, your setup is almost identical to mine so it is not the OS, IDE nor the plugin version.

I am beginning to suspect the various markdown parser and format options interacting to cause this glitch.

When you get the chance, export markdown navigator settings to a file using the Manage... button in preferences and send it to me. It is not all project settings but it might be enough. I would like to duplicate this issue so I can fix it.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/10299086/44496314-f77c3e80-a641-11e8-8def-8432a33b20ca.png">

**Comment by ralfbs** [comment]
Hi @vsch, thanks for the investigation! Very much appreciated. Here is my settings file:
`<MarkdownNavigator.ExportedProjectSettings>
  <option name="myName" value="" havePreviewSettings="true" haveParserSettings="true" haveHtmlSettings="true" haveCssSettings="true" haveHtmlExportSettings="true" haveLinkMapSettings="true" profileName="">
    <PreviewSettings splitEditorLayout="SPLIT" splitEditorPreview="PREVIEW" useGrayscaleRendering="false" zoomFactor="1.0" maxImageWidth="0" showGitHubPageIfSynced="false" allowBrowsingInPreview="false" synchronizePreviewPosition="true" highlightPreviewType="NONE" highlightFadeOut="5" highlightOnTyping="true" synchronizeSourcePosition="true" verticallyAlignSourceAndPreviewSyncPosition="true" showSearchHighlightsInPreview="false" showSelectionInPreview="true" openRemoteLinks="false" replaceUnicodeEmoji="false" lastLayoutSetsDefault="false">
      <PanelProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.javafx.html.panel" providerName="JavaFX WebView" />
      </PanelProvider>
    </PreviewSettings>
    <ParserSettings gitHubSyntaxChange="false" emojiShortcuts="1" emojiImages="0">
      <PegdownExtensions>
        <option name="ABBREVIATIONS" value="false" />
        <option name="ANCHORLINKS" value="true" />
        <option name="ASIDE" value="false" />
        <option name="ATXHEADERSPACE" value="true" />
        <option name="AUTOLINKS" value="true" />
        <option name="DEFINITIONS" value="false" />
        <option name="DEFINITION_BREAK_DOUBLE_BLANK_LINE" value="false" />
        <option name="FENCED_CODE_BLOCKS" value="true" />
        <option name="FOOTNOTES" value="false" />
        <option name="HARDWRAPS" value="false" />
        <option name="HTML_DEEP_PARSER" value="false" />
        <option name="INSERTED" value="false" />
        <option name="QUOTES" value="false" />
        <option name="RELAXEDHRULES" value="true" />
        <option name="SMARTS" value="false" />
        <option name="STRIKETHROUGH" value="true" />
        <option name="SUBSCRIPT" value="false" />
        <option name="SUPERSCRIPT" value="false" />
        <option name="SUPPRESS_HTML_BLOCKS" value="false" />
        <option name="SUPPRESS_INLINE_HTML" value="false" />
        <option name="TABLES" value="true" />
        <option name="TASKLISTITEMS" value="true" />
        <option name="TOC" value="false" />
        <option name="WIKILINKS" value="true" />
      </PegdownExtensions>
      <ParserOptions>
        <option name="ADMONITION_EXT" value="false" />
        <option name="ATTRIBUTES_EXT" value="false" />
        <option name="COMMONMARK_LISTS" value="true" />
        <option name="DUMMY" value="false" />
        <option name="EMOJI_SHORTCUTS" value="true" />
        <option name="ENUMERATED_REFERENCES_EXT" value="false" />
        <option name="FLEXMARK_FRONT_MATTER" value="false" />
        <option name="GFM_LOOSE_BLANK_LINE_AFTER_ITEM_PARA" value="false" />
        <option name="GFM_TABLE_RENDERING" value="true" />
        <option name="GITBOOK_URL_ENCODING" value="false" />
        <option name="GITHUB_LISTS" value="false" />
        <option name="GITHUB_WIKI_LINKS" value="true" />
        <option name="HEADER_ID_NO_DUPED_DASHES" value="false" />
        <option name="JEKYLL_FRONT_MATTER" value="false" />
        <option name="NO_TEXT_ATTRIBUTES" value="false" />
        <option name="PARSE_HTML_ANCHOR_ID" value="false" />
        <option name="SIM_TOC_BLANK_LINE_SPACER" value="false" />
      </ParserOptions>
    </ParserSettings>
    <HtmlSettings headerTopEnabled="false" headerBottomEnabled="false" bodyTopEnabled="false" bodyBottomEnabled="false" embedUrlContent="false" addPageHeader="true" embedImages="false" embedHttpImages="false" imageUriSerials="false">
      <GeneratorProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.javafx.html.generator" providerName="JavaFx HTML Generator" />
      </GeneratorProvider>
      <headerTop />
      <headerBottom />
      <bodyTop />
      <bodyBottom />
    </HtmlSettings>
    <CssSettings previewScheme="UI_SCHEME" cssUri="" isCssUriEnabled="false" isCssUriSerial="false" isCssTextEnabled="false" isDynamicPageWidth="true">
      <StylesheetProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.javafx.html.css" providerName="Default JavaFx Stylesheet" />
      </StylesheetProvider>
      <ScriptProviders />
      <cssText />
      <cssUriHistory />
    </CssSettings>
    <HtmlExportSettings updateOnSave="false" parentDir="" targetDir="" cssDir="" scriptDir="" plainHtml="false" imageDir="img" copyLinkedImages="false" imageUniquifyType="0" targetExt="" useTargetExt="false" noCssNoScripts="false" linkToExportedHtml="true" exportOnSettingsChange="true" regenerateOnProjectOpen="false" linkFormatType="HTTP_ABSOLUTE" />
    <LinkMapSettings>
      <textMaps />
    </LinkMapSettings>
  </option>
  <settings default="" pdf-export="" />
  <MarkdownNavigatorHistory>
    <component>
      <PasteImageHistory filename="image" directory="" onPasteImageTargetRef="3" onPasteLinkText="0" onPasteImageElement="1" onPasteLinkElement="1" onPasteReferenceElement="2" cornerRadius="20" borderColor="0" transparentColor="16777215" borderWidth="1" trimTop="0" trimBottom="0" trimLeft="0" trimRight="0" transparent="false" roundCorners="false" showPreview="true" bordered="false" scaled="false" cropped="false" hideInapplicableOperations="false" scale="50" scalingInterpolation="1" transparentTolerance="0" saveAsDefaultOnOK="false" linkFormat="0">
        <directories />
        <filenames />
      </PasteImageHistory>
      <CopyImageHistory filename="image" directory="" onPasteImageTargetRef="3" onPasteLinkText="0" onPasteImageElement="1" onPasteLinkElement="1" onPasteReferenceElement="2" cornerRadius="20" borderColor="0" transparentColor="16777215" borderWidth="1" trimTop="0" trimBottom="0" trimLeft="0" trimRight="0" transparent="false" roundCorners="false" showPreview="true" bordered="false" scaled="false" cropped="false" hideInapplicableOperations="false" scale="50" scalingInterpolation="1" transparentTolerance="0" saveAsDefaultOnOK="false" linkFormat="0">
        <directories />
        <filenames />
      </CopyImageHistory>
      <PasteLinkHistory onPasteImageTargetRef="3" onPasteTargetRef="1" onPasteLinkText="0" onPasteImageElement="1" onPasteLinkElement="1" onPasteWikiElement="2" onPasteReferenceElement="2" hideInapplicableOperations="false" saveAsDefaultOnOK="false" linkFormat="0" />
    </component>
  </MarkdownNavigatorHistory>
  <DocumentSettings showHtmlPreview="false" verbatimLangInjections="true" htmlLangInjections="true" softWraps="0" iconGutters="true" softWrapAtMargin="false" showEmojiInGutter="false" showBreadcrumbText="true" maxBreadcrumbText="30" previewScrollDelay="500" typingUpdateDelay="500" enableAnnotator="true" hideDisabledButtons="false" hideToolbar="false" disableGifImages="true" codeLikeStyleToggle="true" overrideEditorDragDropHandler="false" toggleStylePunctuations=".,:;!?" htmlMimeMaxImageWidth="100%" htmlMimeFontFamily="" pdfMaxImageWidth="504pt" pdfFontFamily="" detectHtmlOnPaste="false" textSplitLayoutToggle="true" asteriskItalics="true" verticalSplitPreview="true" convertHtmlOnPaste="true" showHeadingID="false" useRenameSpellingFix="true" usePasteHandler="true" includeDirsInCompletion="true" enableLineMarkers="true" showApplyAllIntentionsEverywhere="false" askHtmlOptionsOnPaste="false" htmlPasteAddTrailingEol="false" htmlPasteSkipInlineStrong="false" htmlPasteSkipInlineEmphasis="false" htmlPasteSkipInlineCode="false" htmlPasteSkipInlineDel="false" htmlPasteSkipInlineIns="false" htmlPasteSkipInlineSub="false" htmlPasteSkipInlineSup="false" htmlPasteSkipHeading1="false" htmlPasteSkipHeading2="false" htmlPasteSkipHeading3="false" htmlPasteSkipHeading4="false" htmlPasteSkipHeading5="false" htmlPasteSkipHeading6="false" htmlPasteSkipAttributes="false" zoomFactor="1.0" syntaxHighlighting="1" />
</MarkdownNavigator.ExportedProjectSettings>`

**Comment by vsch** [comment]
@ralfbs, I have not been able to duplicate this behaviour even with your settings. I even tried turning on/off virtual spaces (allowing caret after end of line). No luck. 

I will keep the issue open just in case it can be duplicated.
