### ISSUE TITLE
Make plugin work with custom file types like file.md.twig

### ISSUE THREAD

**Issue by artjomsimon** [vsch/idea-multimarkdown#634]
An enhancement: I have a use case where I run the markdown file through a templating engine (twig in my example) to replace some placeholders using custom application logic. In the second step, I'm invoking a markdown parser to convert the file to some target format.

To be able to edit the markdown in the template, I'd like to name the file like `file.md.twig` but still be able to have the idea-markdown plugin associate itself with the file.

As a workaround, currently I create a .md file (so the plugin's editor shows up) and then rename the file to `.md.twig`. This works during the IDE session but as soon as IDEA is restarted, the association is lost again.

*Suggestion:* Similarly as with IDEA's scratch files, I'd like to be able to right-click on any text file, and select `Change language to markdown` so the plugin knows it's a markdown file, even if it has a different ending

**Comment by vsch** [comment]
@artjomsimon, I think a better solution for you would be to add `.md.twig` extension in the IDE to the Markdown Language type. Then the IDE will simply treat it as markdown automatically.

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/10299086/45772047-bfeabd00-bc14-11e8-81b8-00646e0c5248.png">

**Comment by artjomsimon** [comment]
@vsch wow, thank you!
This is the perfect solution, I didn't know this was possible 🎉
