### ISSUE TITLE
Preview lags in lower part and right margin of the preview pane

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#635]
When scrolling in the fx-preview I constantly struggle with the preview not updating the lower part and right margin of the panel when scrolling around:

![image](https://user-images.githubusercontent.com/200952/45796767-819bdf00-bca2-11e8-97a5-de94efe42b49.png)
The upper left area is rendered correctly. But then there's a duplicated area (there was just one section about `Draft`) and there are visual artifacts at the right margin.

This is not a rare bug, but a permanent experience. It make the the preview very hard/tedious too use.  It's also not a new problem but there since a while.

My preview settings are
![image](https://user-images.githubusercontent.com/200952/45796897-1a325f00-bca3-11e8-90f0-94cbf02f38c8.png)

Tested with v2.6 of the plugin in  the latest 2018.2.4

**Comment by vsch** [comment]
@holgerbrandl, this is an issue of the JavaFX WebView browser. It messes up its updates if the preview pane changes size. The component appears to have some optimization that causes the old view size to be updated and fail to consistently update the new region(s).

The only way to reset it is to close the file tab and re-open it. I try not to change the preview pane with WebView browser.

Does closing the file and re-opening it reset the updates for you?

**Comment by holgerbrandl** [comment]
Thanks for suggesting the workaround, which works great so far. It seems obvious to to do in retrospect, but it somehow did not cross my mind in the first place.
