### ISSUE TITLE
Preview button order should match the split pane view (i.e. left button for left pane, etc.)

### ISSUE THREAD

**Issue by Javaru** [vsch/idea-multimarkdown#643]
I have a minor enhancement request... I think the order of the "Show preview only" and "Show editor only" buttons need to be flipped on the toolbar. Their current order is a little non-intuitive. I say this because when in split mode, the editor is on the left, but to switch to it only, you need to click the right-hand button (of the two). And similarly while the preview is on the right, the button to switch to it only is the left-hand button.  Despite having used your wonderful plugin for over 2-years now, I still often (like 75% of the time) click the wrong button because of this. Despite the presences of the icons, the button order seems to take precedence in my cognitive function when I go to click them and I hit the wrong one.

**Comment by vsch** [comment]
@Javaru, I agree with your suggestion. I just copied the order from Markdown Support without giving it much thought.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
