### ISSUE TITLE
md to html link conversion not working

### ISSUE THREAD

**Issue by marcusleon** [vsch/idea-multimarkdown#647]
We are trying to link file a to file b.  

Created a Link Map "Jekyll .md to .html".  

When exporting to HTML the link is converted from md to html but the path is not correct:

    <a href="../../../..//D:/xxx/yyy/export/FileB.html">

The path starting from D:/ is correct but the path details prior to D:\ are corrupting the full path.

**Comment by vsch** [comment]
@marcusleon, Is this a Windows path? 

Then what does the `../../../../` prefix mean with respect to the following absolute path?

If it is not they why do you have `//` in the middle?

What are the settings for Link Map for Jekyll .md to .html? Maybe there is an error in the expressions which are causing this.

I think the link processing gets confused by the path.

**Comment by marcusleon** [comment]
Yes, this is on Windows.  It looks like the path translation is invalid.   

The MD has:

- [My Stuff](MyStuff.md)

But the plugin appears to be converting that to an invalid path.

**Comment by vsch** [comment]
@marcusleon, can please send me the markdown-navigator project settings: `.idea/markdown-navigator.xml` and if you are using Rendering profiles, then also the files in the `.idea/markdown-navigator` directory.

I will be able to duplicate the error or validate your settings. I suspect it is caused by incorrect system independent processing of a system dependent path.

**Comment by marcusleon** [comment]
Can't attach files but will add here. 

markdown-navigator\profiles_settings.xml:

<component name="MarkdownNavigator.ProfileManager">
  <settings default="" pdf-export="" />
</component>

markdown-navigator.xml:

<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="MarkdownProjectSettings" wasCopied="true">
    <PreviewSettings splitEditorLayout="SPLIT" splitEditorPreview="PREVIEW" useGrayscaleRendering="false" zoomFactor="1.0" maxImageWidth="0" showGitHubPageIfSynced="false" allowBrowsingInPreview="false" synchronizePreviewPosition="true" highlightPreviewType="NONE" highlightFadeOut="5" highlightOnTyping="true" synchronizeSourcePosition="true" verticallyAlignSourceAndPreviewSyncPosition="true" showSearchHighlightsInPreview="false" showSelectionInPreview="true" openRemoteLinks="false" replaceUnicodeEmoji="false" lastLayoutSetsDefault="false">
      <PanelProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.panel" providerName="Default - Swing" />
      </PanelProvider>
    </PreviewSettings>
    <ParserSettings gitHubSyntaxChange="false" emojiShortcuts="1" emojiImages="0">
      <PegdownExtensions>
        <option name="ABBREVIATIONS" value="false" />
        <option name="ANCHORLINKS" value="true" />
        <option name="ASIDE" value="false" />
        <option name="ATXHEADERSPACE" value="true" />
        <option name="AUTOLINKS" value="true" />
        <option name="DEFINITIONS" value="false" />
        <option name="DEFINITION_BREAK_DOUBLE_BLANK_LINE" value="false" />
        <option name="FENCED_CODE_BLOCKS" value="true" />
        <option name="FOOTNOTES" value="false" />
        <option name="HARDWRAPS" value="false" />
        <option name="HTML_DEEP_PARSER" value="false" />
        <option name="INSERTED" value="false" />
        <option name="QUOTES" value="false" />
        <option name="RELAXEDHRULES" value="true" />
        <option name="SMARTS" value="false" />
        <option name="STRIKETHROUGH" value="true" />
        <option name="SUBSCRIPT" value="false" />
        <option name="SUPERSCRIPT" value="false" />
        <option name="SUPPRESS_HTML_BLOCKS" value="false" />
        <option name="SUPPRESS_INLINE_HTML" value="false" />
        <option name="TABLES" value="true" />
        <option name="TASKLISTITEMS" value="true" />
        <option name="TOC" value="false" />
        <option name="WIKILINKS" value="true" />
      </PegdownExtensions>
      <ParserOptions>
        <option name="ADMONITION_EXT" value="false" />
        <option name="ATTRIBUTES_EXT" value="false" />
        <option name="COMMONMARK_LISTS" value="true" />
        <option name="DUMMY" value="false" />
        <option name="EMOJI_SHORTCUTS" value="true" />
        <option name="ENUMERATED_REFERENCES_EXT" value="false" />
        <option name="FLEXMARK_FRONT_MATTER" value="false" />
        <option name="GFM_LOOSE_BLANK_LINE_AFTER_ITEM_PARA" value="false" />
        <option name="GFM_TABLE_RENDERING" value="true" />
        <option name="GITBOOK_URL_ENCODING" value="false" />
        <option name="GITHUB_LISTS" value="false" />
        <option name="GITHUB_WIKI_LINKS" value="true" />
        <option name="GITLAB_EXT" value="false" />
        <option name="GITLAB_MATH_EXT" value="false" />
        <option name="GITLAB_MERMAID_EXT" value="false" />
        <option name="HEADER_ID_NO_DUPED_DASHES" value="false" />
        <option name="JEKYLL_FRONT_MATTER" value="false" />
        <option name="MACROS_EXT" value="false" />
        <option name="NO_TEXT_ATTRIBUTES" value="false" />
        <option name="PARSE_HTML_ANCHOR_ID" value="false" />
        <option name="SIM_TOC_BLANK_LINE_SPACER" value="false" />
      </ParserOptions>
    </ParserSettings>
    <HtmlSettings headerTopEnabled="false" headerBottomEnabled="false" bodyTopEnabled="false" bodyBottomEnabled="false" embedUrlContent="false" addPageHeader="true" embedImages="false" embedHttpImages="false" imageUriSerials="false" addDocTypeHtml="true">
      <GeneratorProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.generator" providerName="Default Swing HTML Generator" />
      </GeneratorProvider>
      <headerTop />
      <headerBottom />
      <bodyTop />
      <bodyBottom />
    </HtmlSettings>
    <CssSettings previewScheme="UI_SCHEME" cssUri="" isCssUriEnabled="false" isCssUriSerial="true" isCssTextEnabled="false" isDynamicPageWidth="true">
      <StylesheetProvider>
        <provider providerId="com.vladsch.idea.multimarkdown.editor.swing.html.css" providerName="Default Swing Stylesheet" />
      </StylesheetProvider>
      <ScriptProviders />
      <cssText />
      <cssUriHistory />
    </CssSettings>
    <HtmlExportSettings updateOnSave="true" parentDir="$PROJECT_DIR$/docs" targetDir="$PROJECT_DIR$/export" cssDir="$PROJECT_DIR$/export/css" scriptDir="$PROJECT_DIR$/export/js" plainHtml="false" imageDir="$PROJECT_DIR$/export/img" copyLinkedImages="false" imageUniquifyType="0" targetExt="" useTargetExt="false" noCssNoScripts="false" linkToExportedHtml="true" exportOnSettingsChange="true" regenerateOnProjectOpen="true" linkFormatType="WIKI_LINK" />
    <LinkMapSettings>
      <textMaps>
        <textMapGroup groupName="Jekyll .md to .html" elementType="LINK_ADDRESS" paramText="" textSample="/dir/file.html" fileRefSample="/dir/subDir/file.md">
          <textMap>
            <linkEntry isRegEx="true">
              <pattern>\.html$</pattern>
              <replaceWith>.md</replaceWith>
            </linkEntry>
          </textMap>
          <fileRefMap>
            <linkEntry isRegEx="true">
              <pattern>\.md$</pattern>
              <replaceWith>.html</replaceWith>
            </linkEntry>
            <linkEntry isRegEx="true">
              <pattern>\.mkd$</pattern>
              <replaceWith>.html</replaceWith>
            </linkEntry>
            <linkEntry isRegEx="true">
              <pattern>\.markdown$</pattern>
              <replaceWith>.html</replaceWith>
            </linkEntry>
          </fileRefMap>
        </textMapGroup>
      </textMaps>
    </LinkMapSettings>
  </component>
</project>

**Comment by vsch** [comment]
@marcusleon, thank you.

BTW, you should use fenced code markers around any text which you post as an example so that GitHub won't try to process it.

     ```xml
     some xml code
    ```

You can use Markdown Navigator in a scratch file to edit it then cut/paste into comment on GitHub. I tend to do that because editing in IntelliJ is easier than the browser.

**Comment by vsch** [comment]
@marcusleon, I am in the process of getting my Windows installation under Parallel Desktop on my mac updated. I has already been a few hours getting the dev environment setup. Now waiting for windows updates to complete.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/10299086/48282501-dbf62800-e427-11e8-898e-dcd842ac8c1b.png">

**Comment by vsch** [comment]
@marcusleon, I can duplicate the bug. It is a system dependent path being processed as system independent path.

I am also seeing strange behaviour with link formats ignoring settings that I will address at the same time.

**Comment by vsch** [comment]
@marcusleon, it was path processing error. It also helped identify a few other bugs. Thank you for reporting it.

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by marcusleon** [comment]
Works well.  Thank you very much for sorting that out quickly!
