### ISSUE TITLE
Drop image with dialog issues

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#651]
Hold ctrl and drop an image. Pick a folder to save image.

- Spaces in the filename are not escaped.
- Generate button doesn't seem to do anything.
- Absolute path (e.g. `/Users/foo/bar/image.png`) don't show image in preview. Sometimes it says "Link doesn't resolve to Github, resolving locally". But then other times it doesn't work. Cmd+clicking on the link results in a screen saying "Image not loaded".

**Comment by vjpr** [comment]
I want to be able to drag a file from my screenshots folder, and have it added to the closest `images` folder. Is that possible?

**Comment by vsch** [comment]
@vjpr, so basically you want to drop an image file into your markdown document and have it copied to the closest (or whatever the plugin determines to be the closest image folder in the document)?

That is what holding Ctrl (on Windows) and the Option key (on OS X) is supposed to do. But I tried it and it leaves the directory of the original file location which is a bug. I'll fix it.

**Comment by vjpr** [comment]
When I tried holding command, I got the dialog, then I have to type in a
folder name. If I type in a relative folder name, it is project relative
(and there are a bunch of bugs that I mentioned earlier).

It would be great to be able to select default folders to search up for,
and copy to closest.

**Comment by vsch** [comment]
@vjpr, holding the ctrl on OS X is the same as not holding it, which is a simple drag/drop without the copying, unless you made changes to your keyboard modifier keys.

In any case it is a Drag/Drop or a Drag/Drop/Copy. The latter should work as if the image was pasted into the file. It determines the directory based on majority image directories in the file and some other logic. It is a lot of conditions, sometimes conflicting.

I will fix the bugs first so you can comment on working code.

**Comment by vsch** [comment]
@vjpr, EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@vjpr, please let me know if this works for you or if you have some issues.

**Comment by vsch** [comment]
@vjpr, a few features were added to image paste/modify dialog: #652 

Latest EAP has performance improvements to reduce typing lag with preview on, by a lot.

**Comment by vjpr** [comment]
@vsch Now when I drop a file, it will always set the destination directory to `blog/201707/asset`, when the file I am dropping into is called `blog/201901/20190130Wed.md`.

Maybe it is searching for the first `asset` dir it finds?

I added an `asset` dir to `blog/201901` and it didn't work.

**Comment by vsch** [comment]
@vjpr, which version of the plugin are you using. I am doing major cleanup in link resolution and could have broken something.

**Comment by vjpr** [comment]
2.7.0.72

**Comment by vsch** [comment]
@vjpr, I will try the version I am using and let you know. I am not sure 90 has the issue, if it does I'll fix it and make a release.

90 has a ton of fixes and performance improvements but this part I did not check.

**Comment by vsch** [comment]
@vjpr, am I right to assume that you are dropping a file from outside the project?

**Comment by vjpr** [comment]
Yep

**Comment by vjpr** [comment]
![screen shot 2019-01-30 at 2 54 55 pm](https://user-images.githubusercontent.com/281413/51985779-04c61080-249f-11e9-9807-ebef7c45f9f7.png)

Also note that filenames with `.`s are not displayed correctly.

`Screen Shot 2019-01-30 at 2.` vs `Screen Shot 2019-01-30 at 2.54.55 pm`

**Comment by vsch** [comment]
@vjpr, I'll try it. The extra dots confuse the code. I will double check why this is so. The file does have a .png extension?

**Comment by vjpr** [comment]
> The file does have a .png extension?

Yep.

**Comment by vsch** [comment]
@vjpr, the directory list prioritization had a bug that could cause directories with lots of images to go to the top of the list. 

The . issue was left overs from previous code, removed.

Now the priority for directories: last used directory for the file at the top.
Then directories used for images in the current file most frequently used first.
Then project directories containing images sorted by number of image files they contain.

Lots of bugs fixed related to link resolution, link refactoring and performance.

Let me know if you encounter any issues. Wrap on typing has been heavily reworked. Now wrapping occurs on every typed character, unless it looks like it would start a new element which would be messed up by wrapping, then wrapping is not done until it is clear what is being typed.
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
