### ISSUE TITLE
Mermaid fenced code blocks not rendering correctly

### ISSUE THREAD

**Issue by bgourlie** [vsch/idea-multimarkdown#655]
I just got a trial license for markdown navigator because I really wanted to evaluate mermaid diagram support. I've checked "GitLab Flavoured Markdown" in the parser options but both mermaid code blocks and math codeblocks do not render as intended. For mermaid, I've verified that the mermaid codeblocks do render as expected on StackEdit. When I look at the generated HTML for the mermaid code block, it looks like this:

```
<div class="mermaid">
graph TD;
A--&gt;B;
A--&gt;C;
B--&gt;D;
C--&gt;D;
</div>
```

**Comment by vsch** [comment]
@bgourlie, mermaid and math support is done by JavaScript in the preview browser. So it can only work with JavaFX preview browser and with Katex and Mermaid scripts enabled in the style sheet options (which the plugin will do automatically when you enable these in the parser).

![Screenshot_Settings_PreviewBrowser.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_PreviewBrowser.png)

![screenshot_parsermermaidkatex](https://user-images.githubusercontent.com/10299086/49458284-87da2b80-f7ba-11e8-8aef-21ceffc183cb.png)

![screenshot_stylesheetmermaidkatex](https://user-images.githubusercontent.com/10299086/49458334-9de7ec00-f7ba-11e8-9efc-cc17c8493589.png)

When configured you also get `mermaid` and `math` as completion options for the fenced code info (language):

    ```mermaid
    graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```
    
    ```math
    \begin{matrix}
    f &= &2 + x + 3 \\
    &= &5 + x \\
    \end{matrix}
    ```

Here is what shows in the preview:

![image](https://user-images.githubusercontent.com/10299086/49459289-b6590600-f7bc-11e8-90cc-7e8999f8ade7.png)

**Comment by bgourlie** [comment]
That fixed it! Thank you.

**Comment by schmunk42** [comment]
JavaFX wasn't available for me until I switched back to the bundled JRE.
Would be good to have some infos about this in the UI or FAQ.

**Comment by vsch** [comment]
@schmunk42, 

https://github.com/vsch/idea-multimarkdown/wiki/Troubleshooting-Common-Problems#javafx-webview-html-preview-not-working

Following the link to:

https://github.com/vsch/idea-multimarkdown/wiki/Changing-Boot-JDK

Relevant from above:

> Bundled JDK version 1.8.0u40b132 and newer does not require changing the boot jdk and will support both Swing and JavaFX previews.

It also depends on the IDE and the OS, including specific versions. Trying to foresee all possible combinations is futile. I tried and gave up. There is always some system configuration that falls outside the expected boundaries.
