### ISSUE TITLE
Add better suggestion visualisation and suggestions to fix incorrect local md files links 

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#659]
Currently, if the link is invalid it's marked on red
![link](https://user-images.githubusercontent.com/530122/49615873-bf0d3000-f9a6-11e8-99cf-726bc8009de7.jpg)

There are two things that can be improved here.
1. First of all, we could only mark part of the path that is invalid (from the root to last valid folder) using a different color or red underscore the invalid path part. Sometimes most of the path is fine, but there is just one missing package. It would be helpful to know "Oh this part is incorrect so I need to remove only this part" or "I have to figure out only the incorrect part"

2. Also If we know that only part of the path is incorrect we could give more precise quick fixes to a user eg.
Path 
`folderA/folderB/folderC/folderD`

let's assume that `folderC/folderD` part is incorrect. Now as a quick fix suggestion we could recursively list all the md files in `folderA/folderB` and propose them as potential fix  eg.
```
folderA/folderB/folderC/info.md
folderA/folderB/folderC/folderD/info.md
folderA/folderB/folderC/folderE/info.md

...
```

**Comment by vsch** [comment]
@igorwojda, just trying to clarify if this is an improvement to a working feature of how intention text is showing alternate targets or a bug preventing alternate targets intention from showing:

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/10299086/49626354-743fe800-f9a7-11e8-9c2a-74b023fd8f48.png">

It should show all files matching the file name of an unresolved target.

**Comment by igorwojda** [comment]
Yesterday I had no such hints, today they are working fine 🤔 
Let's close issue for now and I will take a closer look in the future
