### ISSUE TITLE
WebStorm 11 - Unable to install plugin MultiMarkdown

### ISSUE THREAD

**Issue by bnowak1unca** [vsch/idea-multimarkdown#66]
Plugin MultiMarkdown was not installed: Cannot download 'http://plugins.jetbrains.com/files/7896/22193/idea-multimarkdown.1.2.0.zip': Read timed out
, response: 200 OK

Please help. I checked my proxy settings, and other plugins are downloading/installing

**Comment by vsch** [comment]
The plugin site seems to be down for maintenance. You can download it from GitHub here: https://github.com/vsch/idea-multimarkdown/tree/master/dist

I suggest taking the 1.2.1.1 version it has a few pre-release fixes <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.2.1.1.zip>
