### ISSUE TITLE
Convert code block type from indent to triple-quoted

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#663]
It would be great if the plugin could convert indented codeblocks
```
    cd dataflow-log-analytics/services
```

to  triple-quoted format
\```{END}
cd cd dataflow-log-analytics/services
\```

using an refactoring of live-template.

**Comment by vsch** [comment]
@holgerbrandl, great idea. I will add the intention.

**Comment by vsch** [comment]
@holgerbrandl, EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment]
Awesome thanks for your great support.

**Comment by vsch** [comment]
My pleasure and keep up your generator of great ideas.
