### ISSUE TITLE
Close and Reopen Editors when associated editor is changed

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#664]
Changing markdown file type to plain text or back to markdown or same for HTML files when show spit editor for HTML files is enabled requires open editors to be closed and reopened to reflect the change.

Currently the IDE will only change the file type but leave open editors as is.

Monitoring file changes and asking to close and reopen editors removes user confusion as to why the changes are not reflected in the IDE.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vjpr** [comment]
I see this message tons of times during the day. How can I stop it - its really annoying. Is it related to this issue?

<img width="669" alt="screen shot 2019-01-07 at 2 57 38 pm" src="https://user-images.githubusercontent.com/281413/50772022-9d94b200-128c-11e9-8ecd-f04ba23bc5b5.png">

**Comment by vsch** [comment]
@vjpr, the settings for this are under Languages & Frameworks > Markdown > Debug: `Reload editors when the underlying file type changes`

![Screenshot_Debug_Settings.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Debug_Settings.png)

I am curious as to what on your system is causing this. Use case tests files which should no longer be treated as Markdown or the other way around. This happens when a markdown file is marked/unmarked as `Plain text`.

It will also happen when you select/deselect `Split preview for HTML documents`.

The test for this is quite specific and check is the file editor is one plugin supports and the file type is no longer accepted by the editor provider, and vice-versa. So I am very interested in what causes this on your system.

**Comment by Synchro** [comment]
I've started seeing this in MN 2.8.4.24 in PHPStorm EAP 2019.1.2. It shows multiple times if I relaunch PHPStorm, and also whenever I do a git commit. It's only started happening very recently and it is very annoying - I have not changed the editor associations at all, and nor do I know why it would think file types have changed when they have not been touched.

**Comment by vsch** [comment]
@Synchro, can you give me some specifics about the files for which this occurs? I am not getting this on PhpStorm 2019.1.2 updated today.

In the mean time you can turn off this behaviour since you do not need this unless changing MD files to plaint text or changing whether HTML should be displayed by the plugin with preview. Worst case your can always close and re-open the editor.

![image](https://user-images.githubusercontent.com/10299086/57093813-de518480-6cdc-11e9-9e4d-f33381e2455b.png)

**Comment by Synchro** [comment]
Yes I saw that and disabled it. I don't know which specific files are causing it - I may have several open .md files across various projects, but I have not edited any of them recently. I've not converted anything from plain to markdown, or the other way, or even renamed any .md files, so I don't know why it would think the type has changed.
