### ISSUE TITLE
Action buttons unclickable (except for link creation) OSX

### ISSUE THREAD

**Issue by nfons** [vsch/idea-multimarkdown#667]
Maybe I am doing something wrong, but the action buttons are all unclickable with the exception of link creation.

![image](https://user-images.githubusercontent.com/882236/50385366-76da5700-06a2-11e9-8737-d26e2ed1352e.png)

for bold/italics etc I have tried highlighting text, and then trying to click, but not valid either.

**Comment by vsch** [comment]
@nfons, many of these features are part of the basic edition in the next release.

I will be making an EAP release shortly and will post an update.

For a list of features new features in basic edition see #668

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
