### ISSUE TITLE
Previews are broken for images with relative paths

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#670]
```
README.md
-misc
--breadth_first_traversal.svg
```

This will not show image
`<img src="./misc/breadth-first_traversal.svg">`

**Comment by vsch** [comment]
@igorwojda, does it display the svg if you don't use a relative path?

What if you remove the `./` prefix to leave only the `misc/breadth-first_traversal.svg` as relative path?

**Comment by vsch** [comment]
@igorwojda, I cannot duplicate this which means that some other factor is in play, not just the relative path. 

**Q1:** Can you use a markdown image element with the SVG image using the relative path you provide for the src attribute? If markdown does not resolve the image path then preview will not either.

**Q2:** Are you on Windows or Linux/OS X? If windows then I suspect a bug in the path processing for image tags in the plugin preview.

**Q3:** Are you using JavaFX or Swing preview browser? Swing preview implements its own SVG image processing and only in the later EAP releases. Prior versions do not display SVG images.

**Comment by igorwojda** [comment]
update to `2.7.0.40` solved the problem.
