### ISSUE TITLE
Add quickfix to remove existing link

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#673]
![image](https://user-images.githubusercontent.com/200952/50997689-8b817080-1525-11e9-8c8a-dca2813f23c3.png)
It would be great if there could be another quickfix named 'Remove Link' which would transform the link into just the link. So with respect to the screenshot to just .NET.

**Comment by vsch** [comment]
@holgerbrandl, easy enough to add. I am just wondering was this pasted from HTML?

If you set `Ask options on paste` you will get the opportunity to disable inlines 

![image](https://user-images.githubusercontent.com/10299086/51008030-f88e0980-1517-11e9-9d87-1ec74455e1cb.png)

So what I am asking if there needs to be another option to convert links to their text only version?

![image](https://user-images.githubusercontent.com/10299086/51008569-528fce80-151a-11e9-8210-cffa9e9107bf.png)

Would add it to the `Suppress` panel as: `Links` check box.

**Comment by vsch** [comment]
@holgerbrandl, both added. It has been a long time I wanted to add suppression of links from HTML  paste conversion but was too lazy to spend the 30 mins to do it.

Having the intention makes it easy to do this after forgetting to do it in the paste options.

EAP update with a fix for the issue is available.

Added to EAP 2.7.0.44

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment]
Thanks a ton. As always I admire your amazingly short fix times. From spec
to rollout in less than a day is really cool. I wish I'd be as efficient
with my own projects. :-)

Vladimir Schneider <notifications@github.com> schrieb am Fr., 11. Jan. 2019
um 03:33 Uhr:

**Comment by vsch** [comment]
@holgerbrandl, the short fix times really depend on simplicity and isolation of the change.

In this case it is part of a feature which already had the infrastructure in place and it was a matter of adding an option and is isolated to small part of the code.

I wish I could say that for all items on the todo list. The biggest is link resolution architecture which is a complete rewrite and affects almost all parts of the code. In this case it is a slow process of mapping out requirements and architecture design.
