### ISSUE TITLE
Text colouring is missing in commit file preview window

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#676]
1. Make a change in project
2. Commit -> `Commit changes window` will open
3. Open preview of the changed file

Result (code on left side is not collored)
![image](https://user-images.githubusercontent.com/530122/51147256-7e2ff300-1851-11e9-88a1-49d9fe41e637.png)

BTW Html code coloring seems to be working fine

Android Studio 3.3, Markdown Navigator 2.7.0.50

**Comment by vsch** [comment]
@igorwojda this is related to how syntax highlighting is performed. #588 

I will check AS because it is fixed for JetBrains IDEs but did not think this was different for AS.

**Comment by vsch** [comment]
@igorwojda, check if you have the following enabled.

I tried it with AS 3.2.1 and it works so either AS 3.3 is different or it is disabled on your system:

![image](https://user-images.githubusercontent.com/10299086/51147584-c5ee5480-1828-11e9-9b82-5cc55b8bc119.png)

**Comment by igorwojda** [comment]
I do not see any longs.  Just to clarify - this is what I did.

1. Plugin updated to `2.7.0.56`

2. Enabled logging
![image](https://user-images.githubusercontent.com/530122/51303005-f6521080-1a2b-11e9-947a-45312f0f1f52.png)

3. Made a change in the file and opened it in the commit preview (read-only)

5. No logs were displayed by IDE
![image](https://user-images.githubusercontent.com/530122/51303070-27324580-1a2c-11e9-9fbd-2d63a8710056.png)

```
Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2
```

**Comment by vsch** [comment]
@igorwojda, sorry I was not specific about where the log entries are.

It is the IDE log. To see go to:

1. Help > Show Log in Finder
2. Open the `idea.log` file in OS X Console app to show the log live

3. Go to Version Control tool window
4. Select Log tab
5. Select a version in the list which has Markdown files in the modified tree view
6. Context Menu on the markdown file: Open Repository Version

![image](https://user-images.githubusercontent.com/10299086/51349161-992d7d80-1a72-11e9-9735-75201452c129.png)

7. Console app log shows (on my system with AS 3.3):

<img width="876" alt="image" src="https://user-images.githubusercontent.com/10299086/51349243-cb3edf80-1a72-11e9-8b80-10972f9978fe.png">

**Comment by igorwojda** [comment]
Here it is 

```
2019-01-17 21:51:32,845 [entQueue-0]  DEBUG - .multimarkdown.project.editors - editorEx created com.intellij.openapi.editor.impl.EditorImpl@20f9bb20 
2019-01-17 21:51:32,960 [entQueue-0]  DEBUG - .multimarkdown.project.editors - swapEditorToLexerHighlighter for com.intellij.openapi.editor.impl.EditorImpl@20f9bb20 
```

BTW preview of the file opened by `Open Repository Version` looks fine (color are ok). Only this "compare what changed" view has incorrect color for me

**Comment by vsch** [comment]
@igorwojda, I can duplicate this so it is good news. There is probably difference due to the modal state.

**Comment by vsch** [comment]
@igorwojda, yes this was the cause. Modality state prevented delayed execution of swapping code.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by igorwojda** [comment]
Works, perfectly.
Thanks
