### ISSUE TITLE
Wired preview with hard line wrap

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#679]
I am not sure If I messed it up, but I can't really figure out how to fix this behavior.

So I have a hard wrap on the editor with nice limits characters to 120 per line. The editor works perfect (the text is properly formatted and aligned), however, preview seems to be broken because of the link in the text takes much more space then link title in the preview, so preview formatting is distorted.
(`</br>` tag is added at the end of each line). 

On the other hand, GitHub preview works fine and ignores this new line character. Here is a comparison (I use `Default - Swing` browser).

![image](https://user-images.githubusercontent.com/530122/51275429-dab61e00-19c9-11e9-9597-058f1afb051d.png)

I am not sure if this is a bug or am I missing something? The goal here is to have a line character limit in a text editor (hard wrap), but also to have Github like the preview at the same time.

**Comment by vsch** [comment]
@igorwojda, you have "Hard Wraps" option set in parser settings:

![Screenshot_Parser_HardWraps.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_HardWraps.png)

This option creates compatibility with markdown for GitHub comments by rendering EOLs in input as breaks in HTML.

**Comment by igorwojda** [comment]
Perfect, Thx
