### ISSUE TITLE
In Python syntx support support doc-tests notation

### ISSUE THREAD

**Issue by Ashald** [vsch/idea-multimarkdown#68]
So in `README.md` we can do something like:
```python
>>> 1 + 2
3
```
without getting tons of 'syntax error highligts'

**Comment by vsch** [comment]
@Ashald I am not a python user so you will have to explain to me what you mean. In idea-multimarkdown there are no syntax errors here are the screenshots of what the markdown source and preview look like of the exact markdown you used for posting the issue:

<img width="502" alt="screen shot 2015-11-13 at 3 52 34 pm" src="https://cloud.githubusercontent.com/assets/10299086/11157635/8da95e2e-8a20-11e5-974f-8aeb7036e912.png">

<img width="632" alt="screen shot 2015-11-13 at 3 52 22 pm" src="https://cloud.githubusercontent.com/assets/10299086/11157621/7b706fea-8a20-11e5-9977-348078deb523.png">

The preview looks like pretty good facsimile of what GitHub renders. Can you please explain what you mean by your suggestion and don't assume I know anything about Python or PyCharm. I launch it to test that the plugin does not crash the IDE. This is my extent to interacting with it. I use IDEA and PhpStorm extensively out of the whole family of JetBrains IDEs.

**Comment by Ashald** [comment]
That's what I see:
![screen shot 2015-11-18 at 12 34 54](https://cloud.githubusercontent.com/assets/397987/11248773/fd80341a-8df0-11e5-88cf-c939cbcf5532.png)
![screen shot 2015-11-18 at 12 34 46](https://cloud.githubusercontent.com/assets/397987/11248774/fd80b0b6-8df0-11e5-971d-75484f8a862f.png)
![screen shot 2015-11-18 at 12 34 35](https://cloud.githubusercontent.com/assets/397987/11248775/fd8319fa-8df0-11e5-8da3-05fd73fb6806.png)

**Comment by vsch** [comment]
What plugin do you have installed to handle Python syntax in Markdown documents or how did you configure your PyCharm to include it?

Can you include the editor tabs (upper and lower in the screen shot)? From the screen shots you have I can only tell that it is not "default" idea-multimarkdown text editor but not more than that.

I would like to duplicate your setup/config so I can see what you are seeing.

**Comment by vsch** [comment]
@Ashald, I figured it out. You have Markdown Support plugin installed and enabled. The editor and preview you are seeing is from that plugin not idea-multimarkdown. You need to disable other Markdown plugins except Gfm plugin. The latter only provides GitHub preview and does not conflict with other plugins.

This version of idea-markdown does not handle language injections so no Python syntax highlighting in code fenced blocks. I am looking into having this implemented in the near future.

**Comment by Ashald** [comment]
Ah, you was right! I'm so sorry! I was sure that I disabled it once I installed `idea-multimarkdonw`. Thanks!

Great, then i will be waiting for new releases! :) You will use some of PyCharm features for syntax highlight (so doc-string tests notation as in examples above will work OOB)?

Thanks once again!

**Comment by vsch** [comment]
@Ashald, no need to apologize JetBrains IDEs are the best but getting all the configuration right, especially with third party plugins, can take some effort.

I appreciate all feedback, even when the issue is not caused by idea-markdown because I get to learn more about the IDEs and it is a great source of ideas. 

The syntax highlighting in injected languages is handled by the IDE. I suspect that with all the flexibility it should be possible but I have not idea how easy it will be to figure out. I will do my best to see if I can make your request work.

**Comment by Ashald** [comment]
Thanks!
