### ISSUE TITLE
Add PlantUML fenced code rendering

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#680]
* Add: PlantUML/DOT rendering for `puml` and `plantuml` fenced code as options

  * Requires enabling parser extensions for `PlantUML` and `DOT` fenced code rendering
  * Selecting type of rendering in HTML Generation settings: `Embedded` using PlantUML jar, `Gravizo PNG` or `Gravizo SVG` using gravizo.com

  :warning: Swing does not display `Gravizo PNG`

  :warning: JavaFX may not display `Gravizo SVG` correctly
* Add: plant uml fenced code rendering to work with HTML mime copy and export
* Add: intentions to convert between multi-line URL Gravizo and PlantUML fenced code intentions

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
To enable this extension:

1. Select `PlantUML` fenced code and `DOT` fenced code in parser settings

  
  ![image](https://user-images.githubusercontent.com/10299086/51291226-6c2a8d80-19d4-11e9-8730-ded6034badcd.png)


2. Select how you would like to render this in Html Generation settings:

   1. Embedded, will use plant uml jar (same as Markdown Support)
   2. gravizo.com PNG, will use gravizo.com for rendering to PNG
   3. gravizo.com PNG, will use gravizo.com for rendering to SVG

   ![image](https://user-images.githubusercontent.com/10299086/51291244-764c8c00-19d4-11e9-89fd-f0d500175391.png)

**Comment by tshimomura** [comment]
On Windows, and use "Embedded", preview image is not shown.
I think that escape to path separator is incorrect.
![no-image-src](https://user-images.githubusercontent.com/12785183/51788382-d4415680-21c0-11e9-98af-ecc7a69a1943.png)

**Comment by vsch** [comment]
@tshimomura, thank you for catching this one. I forgot about the path conversion to Windows on this one. Fixed in eap 2.7.0.86.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by tshimomura** [comment]
EAP 2.7.0.86 works well on Windows. :thumbsup:
