### ISSUE TITLE
New line wrap is added to late

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#684]
If I would not put space between `characters` and `in` (last character I type) the line break would not occur at all, so the `first` text would stay outside desired character limit for line.

![linebreak](https://user-images.githubusercontent.com/530122/51445061-7d3b0d80-1cf8-11e9-9531-e5690a56112e.gif)

**Comment by vsch** [comment]
@igorwojda, wrapping is only done on space to improve typing response. I can see if current implementation still causes unacceptable delay for wrapping on every character.

I will add a plugin application setting to wrap on every character. 

I can also see if adding a delayed wrapping after non-space will be stable. For example, after 0.5 seconds after last non-space character is typed, wrap paragraph.

**Comment by vsch** [comment]
@igorwojda, just tried enabling for all typed characters and the typing response is not affected. I will add an option to `Wrap only on typing space` but set it to false by default so that wrapping will be done for all typed characters. However, anyone negatively affected will be able to turn it off.

**Comment by igorwojda** [comment]
Wow this was fast :-D 
Works perfectly. thx

**Comment by vsch** [comment]
@igorwojda, with wrapping on all typed characters there is some side-effects. Typing setext heading marker line will wrap the two lines.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
