### ISSUE TITLE
How to disable auto join for quotations

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [vsch/idea-multimarkdown#691]
DocFX uses the following quotation style for notes:

```
> [!NOTE]
> <note content>
```

The note content must be on a new line. 

But the plugin automatically joins the two lines, so I get this:

 ```
> [!NOTE] <note content>
```

Is there any way to disable this functionality?

**Comment by vsch** [comment]
@Jaap-van-Hengstum, the wrap on typing toolbar <img width="30" alt="image" src="https://user-images.githubusercontent.com/10299086/51841400-8a4d9300-22dc-11e9-8e49-6face4001f8d.png"> button can be used to toggle wrap on typing in markdown.

You can also define a keyboard short cut to this action so you can toggle it on demand.

Another option is to type two or more spaces at the end of the `> [!NOTE]` line, so wrapping treats it as a hard break and will not wrap the following line to join this one. I don't think these trailing spaces will affect DocFX.

I took a quick look at DocFX and it looks interesting. I will consider adding parser extension(s) to support their modified markdown syntax.

**Comment by Jaap-van-Hengstum** [comment]
@vsch 
Thanks, the double space is exactly what I needed.
