### ISSUE TITLE
Consecutive code fences become out of sync and are not syntax highlighted correctly during editing

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#693]
http://recordit.co/QCR8XDG7Cb

**Comment by vsch** [comment]
@vjpr, are you using Lexer syntax highlighting? I only notice this when lexer is used.

The IDE has optimizations for performance which are not compatible with markdown.

**Comment by vsch** [comment]
@vjpr, I changed the lexer to handle the optimizations. However, lexer based syntax highlighting is slow because it isn't lexer based but full parser faking a lexer.

Annotator based highlighting is better for anything but small markdown files.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
