### ISSUE TITLE
Replicate JetBrains markdown plugin syntax highlighting

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#694]
<img width="574" alt="screen shot 2019-01-30 at 9 48 40 pm" src="https://user-images.githubusercontent.com/281413/52011631-d107dc80-24d8-11e9-9886-284ffdbe32a6.png">

- The colored italic header, the greyed code block are nice and clean. I want this same style in markdown navigator.

---

Also, notice how the `View:` buttons are always shown. On markdown navigator, they are always hidden in a menu.

**Comment by vsch** [comment]
@vjpr, change the Editor > Color:

![image](https://user-images.githubusercontent.com/10299086/52014084-9d16c200-24ac-11e9-8776-40b2226d5e48.png)

Considering it only has 7 button it is not hard to fit into the limited space.

Eventually, I will add toolbar customization so you will be able to add/remove actions based on your frequent use.
