### ISSUE TITLE
Autoscroll from source does not work in simplified structure view

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#697]
It does not autoscroll from source in the simplified structure view.

See https://imgur.com/a/mKQG7Xt for an example screenshot

**Comment by vsch** [comment]
@holgerbrandl, can you take your file and remove any proprietary information and make it available for me to see if I can duplicate this.

Is the file part of the project? It might be an issue but I do not see how. But I must exclude all variables.

**Comment by vsch** [comment]
@holgerbrandl, I failed to pass editor to my structure view construction so as far as it was concerned there was no editor position from which to scroll the tree view.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@holgerbrandl, I am reworking the structure view to add filters and groupers as the API supports and will have ability to display `Headings with Task Items`, it is like the current simple structure view but includes headings with any task list items under them to allow using a document as a glorified to do list:

![image](https://user-images.githubusercontent.com/10299086/52742169-2944e100-2fa5-11e9-9d59-e7a9cf3281bf.png)

The above is for the file:

![image](https://user-images.githubusercontent.com/10299086/52742223-4da0bd80-2fa5-11e9-872a-9030d091aa66.png)

I got hooked on your idea of using structure view for todo list navigation but needed a bird's eye view when the list gets too long.
