### ISSUE TITLE
Show navigable headings as file members inside project view

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#705]
Inside the project view, if "Show Members" was enabled it would be nice to see the section headings displayed as a tree of navigable elements, in the same way as members of a class would be in source code (kind of like a table of contents). I see there is a [document structure view](https://github.com/vsch/idea-multimarkdown/issues/99), perhaps this would be easy to implement.

![screenshot from 2019-02-13 12-22-44](https://user-images.githubusercontent.com/175716/52730854-5c2dab80-2f8a-11e9-979a-fe7ec3c62de4.png)

**Comment by vsch** [comment]
@breandan, I did not even look at the "Show Members" functionality for project view. It is a
great idea to include headings and any `a` tags which can be used for anchor refs in links.

It should be easy enough to add, all the support for navigable functionality is already
implemented. Just have to add the appropriate IDE extension.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
