### ISSUE TITLE
Empty element in simplified structure view when using just url as header text

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#708]
See https://imgur.com/a/nBEZJm0 for example.

Used version v2.8.2.6 in IntelliJ IDEA 2018.3.4 (Ultimate Edition)

**Comment by vsch** [comment]
@holgerbrandl, yes. A shortcoming of my expectations. The headings are parsed to eliminate all non-text content, in this case there is none but the auto-link.

I'll fix it.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment]
Thanks Vladimir for the fix & great support.

**Comment by vsch** [comment]
@holgerbrandl, you are welcome and it took much longer than usual because after the last EAP I started major code cleanup from which it took me a while to recover to a stable version.
