### ISSUE TITLE
New Icon looks bad on dark background

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#709]
I am using IDE in dark mode. Comparing Markdown navigator icon it's simply looks bad.

![image](https://user-images.githubusercontent.com/530122/53285875-280e7380-375e-11e9-927c-83ba7a6910c7.png)

The biggest problem is that it almoutrs almoust blends with the background to it's really hard to say that this is markdown logo (especially on my 4k screen). On the other hand it has this "almoust red" color similar to error exclamation mark that steals my attention with no reason (each time I look at the files mark down file is the first one I nocice in a gfolder/package).

My suggestion is to keep old icon (although I don't remember what it was exactly) or use some generic markdown icon. We could also keep markdown icon but make it neurtal color (eg. gray that gradle icon have) or make it more like actual file icon (not logo)

**Comment by vsch** [comment]
@igorwojda, the issue is really with the colors used for dark scheme. It might take a bit of tweaking. In the version I am using I already made the dark colors lighter and will play with it some more to improve the contrast for dark scheme:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/10299086/53286047-94757c80-3736-11e9-85a5-5d6a0e0dbf26.png">

**Comment by igorwojda** [comment]
Yes, this is a bit better, however, I think that the current logo is just to complex to look good at this size and on top of that red/pink does not contract well with dark colors (Just make it gray for your self and you will see what I mean). Also, it's quite standard practice that when designing logos there are few versions with different colors, so I  would not be attached to this red/pink so much. As an example google [grade logo](https://www.google.com/search?q=gradle+logo&oq=gradle+logo&aqs=chrome..69i57j0l5.1439j0j1&sourceid=chrome&ie=UTF-8) and you will see it's either green or very dark gray, almost black witch is different than color in the IDE

**Comment by vsch** [comment]
@igorwojda, just a matter of tweaking it until it is good enough. 

Another attempt, less saturated, higher brightness. I included all aspects: wiki directory overlay, wiki page, markdown file and the icons on open file tabs. I also included the "Headings & Tasks" structure view option because these icons too need light/dark tweaks.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/10299086/53286479-208aa280-373d-11e9-97fe-54d009af1696.png">

**Comment by vsch** [comment]
As above but in Light scheme for comparison:

<img width="781" alt="image" src="https://user-images.githubusercontent.com/10299086/53286504-b3c3d800-373d-11e9-9383-0a441094b3e9.png">

**Comment by igorwojda** [comment]
This is definitely a good direction in term of coloring.
In terms of the file icon shape, I still should resemble the rest of the file icons.
I did a quick comparison here and we can clearly see that the majority of the icons of the most popular languages (or file types that comes to my mind) have this "piece of paper icon" representing file 

![image](https://user-images.githubusercontent.com/530122/53286886-978b5f80-376c-11e9-9958-5df310aba4e5.png)
![image](https://user-images.githubusercontent.com/530122/53286846-3f545d80-376c-11e9-9f41-aec874cc9e3c.png)
![image](https://user-images.githubusercontent.com/530122/53286863-585d0e80-376c-11e9-9f94-c4eb65f51f93.png)
![image](https://user-images.githubusercontent.com/530122/53286867-627f0d00-376c-11e9-8da6-a25f8420f185.png)
![image](https://user-images.githubusercontent.com/530122/53286876-85112600-376c-11e9-84ba-61ec72afd49c.png)


To be completly fair there are few exceptions like some gradle icons, yaml, go etc... but I think it's a bad direction
![image](https://user-images.githubusercontent.com/530122/53286904-bb4ea580-376c-11e9-8aa1-3811d75cd7dc.png)
![image](https://user-images.githubusercontent.com/530122/53286907-c86b9480-376c-11e9-9f13-14129ae8a844.png)
![image](https://user-images.githubusercontent.com/530122/53286914-eafdad80-376c-11e9-84a4-34ee3fd9352c.png)

**Comment by vsch** [comment]
@igorwojda, I was planning on adding an option for selecting old/new icons. It is just a PITA to keep adding options. Not really for me but for users but there is no accounting for taste so I will add an option to use old icons. 

As for icon shapes, it varies.  
<img width="98" alt="screen shot 2019-02-23 at 8 22 31 am" src="https://user-images.githubusercontent.com/10299086/53287120-dce86680-3745-11e9-84be-5229ea855d1d.png">
<img width="101" alt="screen shot 2019-02-23 at 8 22 49 am" src="https://user-images.githubusercontent.com/10299086/53287121-dce86680-3745-11e9-99b1-ab74498ea4e1.png">
<img width="184" alt="screen shot 2019-02-23 at 8 23 38 am" src="https://user-images.githubusercontent.com/10299086/53287122-dce86680-3745-11e9-991b-e588ded55bd2.png">
<img width="105" alt="screen shot 2019-02-23 at 8 24 30 am" src="https://user-images.githubusercontent.com/10299086/53287123-dce86680-3745-11e9-92d5-ff2f21bacb53.png">
<img width="135" alt="screen shot 2019-02-23 at 8 24 37 am" src="https://user-images.githubusercontent.com/10299086/53287124-dce86680-3745-11e9-9f5b-a13b0e9160c6.png">
<img width="128" alt="screen shot 2019-02-23 at 8 24 46 am" src="https://user-images.githubusercontent.com/10299086/53287126-dce86680-3745-11e9-9dd4-7c8e02be36b9.png">
<img width="165" alt="screen shot 2019-02-23 at 8 27 24 am" src="https://user-images.githubusercontent.com/10299086/53287127-dce86680-3745-11e9-98d4-14836c70df7a.png">

All depends on how much time/effort to spend. Most icons are an overlay on the standard document.

That is exactly the option I will offer as an alternative. The overlay will be the old icon but only the overlay part. Wiki pages will have 3 choices: new overlay, old document overlay or old icon.

**Comment by vsch** [comment]
<img width="314" alt="screen shot 2019-02-23 at 11 18 22 am" src="https://user-images.githubusercontent.com/10299086/53288931-fea11800-375c-11e9-9b9f-4533550c1c8f.png">

<img width="778" alt="screen shot 2019-02-23 at 11 18 47 am" src="https://user-images.githubusercontent.com/10299086/53288934-0365cc00-375d-11e9-95f2-4c035be6c78f.png">

<img width="781" alt="screen shot 2019-02-23 at 11 17 49 am" src="https://user-images.githubusercontent.com/10299086/53288933-0365cc00-375d-11e9-950d-ef24b1fd0d57.png">

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
