### ISSUE TITLE
Target file is not on github annotation

### ISSUE THREAD

**Issue by demisolutions** [vsch/idea-multimarkdown#712]
Hello.

Is it possible to turn off specific annotation in PHPStorm?

For an example, I keep getting "Target file is not on GitHub. Link will only resolve locally.".

Which makes sense, because that file is not on GitHub yet, but after commit it will be, since I am commiting all local files anyway.

Thanks!

**Comment by vsch** [comment]
@demisolutions, I will be adding an annotation configuration pane to settings and have this annotation disabled by default. 

I avoided this because I wanted to migrate all annotation logic to inspections which have IDE provided configuration but found out that there are limitations to inspections.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
