### ISSUE TITLE
Paste always pastes as code

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#722]
Since the last EAP update (from today I think), it pastes always by wrapping the clipboard content into a code block

![image](https://user-images.githubusercontent.com/200952/54423400-e5aed580-4710-11e9-9115-43add9708b44.png)

after copy and paste

![image](https://user-images.githubusercontent.com/200952/54423417-ecd5e380-4710-11e9-8eb6-fd962da9cafc.png)

**Comment by vsch** [comment]
@holgerbrandl, how are you copying it? Using regular copy or some other copy format?

I tried this and it pastes what was copied.

Do you have any plugins that play with copy format?

**Comment by vsch** [comment]
@holgerbrandl, can you copy then use a clipboard viewer to see what is on the clipboard?

I am curious as to what is on the clipboard. If something adds an HTML mime type then if you have HTML to markdown enabled in the plugin it would do that. However, the plugin does not do any wrapping or change from plain text on regular copy, as far as I know.

**Comment by holgerbrandl** [comment]
Indeed it seems to be about the mime-type, I noticed that it is not the paste but the copy operation which seems to be the issue. Pasting content which was copied outside of idea works without any problem.

It's just affecting the markdown IJ (which is compatible to your mime-type hypothesis),, because pasting the same clipboard content into non-markdown editors in IJ works as expected.

It seems that when copying in IJ, it adds a mime type indicating code. Not sure component/plugin would do so. I'm using 

```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

Isn't IJ always copying text including some formatting? E.g. when pasting code bits from IJ into a mail, they are always colored.

**Comment by vsch** [comment]
@holgerbrandl, yes you have copy rich text enabled which I think generates an HTML flavour on OS X automatically.

You can either enable "Ask options on paste" Markdown Navigator option so it will give you a choice of what to paste if HTML content is being pasted (Languages & Frameworks > Markdown > Editor) or turn off `Copy rich text by default` in (Editor > General) and use `Copy as Rich Text` in the edit menu when you want to paste to another app.

**Comment by holgerbrandl** [comment]
Indeed, this solves the problem. Not sure why this setting has changed, but I guess it did so when enabling pref synching in the ide yesterday.

Thanks for your help.

**Comment by vsch** [comment]
@holgerbrandl, I blew the settings repository plugin out of my IDEs, with gusto. The last thing I can afford is to have some plugin mess with my settings. I have enough trouble with IDE upgrades, I don't need more mysteries due to settings being switched on me behind my back. 😄

**Comment by vsch** [comment]
I expect a lot more people to encounter this. I completely forgot why I blew out the preferences sync out of my IDEs. I upgraded the IDE and got the code pasting myself and wasted some time looking for the "bug". Only remembered it when the second issue was opened for this problem.
