### ISSUE TITLE
unable to show ref anchor link explorer

### ISSUE THREAD

**Issue by khun84** [vsch/idea-multimarkdown#726]
I have enabled ref anchor link explorer in markdown navigator config and code intention config. But when I invoke the intentions command, I could't see ref anchor link explorer in intentions command list.

Env:
```
RubyMine 2018.3.2
Build #RM-183.4886.48, built on December 19, 2018

JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

Markdown Navigator v2.8.2
```

**Comment by vsch** [comment]
@khun84, thank you for reporting this. A bug introduced in the last release prevents the explorer from showing. I have fixed it. I  will make an EAP release with the fix.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
