### ISSUE TITLE
css files not created in export folder

### ISSUE THREAD

**Issue by Jelmerb** [vsch/idea-multimarkdown#727]
When I export my markdown files to HTML using a custom gitlab wiki profile, no css files are created in the export folder (also no css folder) although the links to the stylesheets are added to the head of my HTML files. I'm using version 2.8.2 and have activated the free trial licence (thinking about buying it, if I can adjust the plugin to my needs).

This is a screenshot of my configuration:

![screenshot](https://user-images.githubusercontent.com/6000226/54762850-2c12a180-4bf5-11e9-9f67-881011001881.png)

I can't figure out if I'm doing something wrong or if it's a bug because I don't get a lot of feedback when exporting files. 

Kind regards,

**Comment by vsch** [comment]
@Jelmerb, it appears to be a bug introduced with the changes in last release. I will have it fixed shortly.

**Comment by Jelmerb** [comment]
Thanks for the quick reply. I will be waiting for the next release.

**Comment by vsch** [comment]
@Jelmerb, you won't need to wait for the next official release. I will make and EAP release with the fix probably within an hour or two.

**Comment by Jelmerb** [comment]
That's fast. I will test it as soon as it's live. Much appreciated.

**Comment by vsch** [comment]
@Jelmerb, thank you for reporting this one. 

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by Jelmerb** [comment]
I can confirm this is fixed in version 2.8.2.56

**Comment by vsch** [comment]
Thank you for the confirmation. You would be surprised how often this is withheld. 👍

**Comment by Jelmerb** [comment]
As a developer I know how bad users can be at reporting and communicating bugs or requests

**Comment by Jelmerb** [comment]
CSS export is broken again. No CSS files are exported. Should I open a new issue? 

I'm on: 
IntelliJ 2019.1
Markdown Navigator 2.8.4.16

**Comment by vsch** [comment]
@Jelmerb, bug caused by my attempt to clean up `file:/` URI prefix handling code between Windows and non-Windows systems.

Fixed. EAP release shortly.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by Jelmerb** [comment]
Fix confirmed :) Thanks
