### ISSUE TITLE
ditaa support

### ISSUE THREAD

**Issue by grubbins** [vsch/idea-multimarkdown#732]
PlantUML now includes ditaa support, either via `@startditaa` or (temporary arrangement) `@startuml` followed by `ditaa(...)`.

It would be awesome if this worked in Markdown Navigator too. So far I have not been able to make this work. I tried:

    ```puml
    ditaa()
    A
    ```

This reports a syntax error on `ditaa`. I downloaded the latest PlantUML jar and copied it into the plugin dir in case that is the issue, but it did not make a difference.

    ```plantuml
    @startuml
    ditaa()
    A c B
    @enduml
    ```

Also a syntax error on `ditaa`.

    ```puml
    @startditaa
    A
    @endditaa
    ```

This results in a broken image icon. Looking in the image cache directly, I see an empty PNG file.

In all cases, the PlantUML plugin rendered the ditaa diagram correctly.

**Comment by vsch** [comment]
@grubbins, I will do an update for the next EAP release. Your request came right at the end of the release cycle and I did not want to add another issue to the release.

The last release was right on the heels JetBrains releasing JBR-11 and it was generating several dozen exception reports a day and I needed to get a fixed release out ASAP.

**Comment by grubbins** [comment]
Thanks for following up, look forward to it!

**Comment by vsch** [comment]
@grubbins, ditaa is only available for the GPL licensed library. If this ever makes it into more permissive licensed versions then I will be able to include it in the plugin.

**Comment by vsch** [comment]
@grubbins, if you replace the `plantuml-jar-asl-1.2019.4.jar` in the plugin installation directory with the GPL version of the library `plantuml.1.2019.4.jar` then ditaa() will work.

You don't need to rename the jar file just remove the ASL version of the jar so that only one plangUML library jar is located in the plugin installation `lib/` directory.
