### ISSUE TITLE
PlantUML include path

### ISSUE THREAD

**Issue by grubbins** [vsch/idea-multimarkdown#733]
I have a PlantUML block like this:

    ```puml
    !include my-file.puml
    ```

Sometimes this works fine in the preview. Other times, I see an error from PlantUML "Cannot include my-file.puml". I cannot figure out what determines whether it is going to work or not!

I suppose this comes down to the include paths used by PlantUML when we run it. How is that handled? Can we have the directory of the markdown file on the list of include paths for PlantUML? If it isn't there, how come this sometimes works?

**Comment by grubbins** [comment]
Ah, I did just discover that the "Cannot include" error image is cached, and won't be replaced if all I do is move/edit the included file. If, however, I put the included file in the right place and then delete the image cache, it then works.

With cache clearing the behaviour seems more predictable if I `include` a file in the same directory as the markdown doc. I have not been able to use relative paths like `!include puml/my-file.puml`.

**Comment by vsch** [comment]
@grubbins, I will add this to the next EAP release. I did not investigate using plant uml inclusions so will need to figure out where it is expected when a relative path is used.

**Comment by grubbins** [comment]
Sounds good. I think there are two things:
1. Clear the image cache if an included file has changed, appeared or disappeared
2. Support other include paths

The first one alone would make use of included files in the same directory much more intuitive.

**Comment by vsch** [comment]
@grubbins, I added code to change the user.dir to the file's directory and it works for relative includes but you need to add `./` prefix to the include file, otherwise plant uml library complains that it cannot include the file.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by grubbins** [comment]
Thanks!

How about the cached image invalidation part? That was actually the more confusing part for me.

**Comment by vsch** [comment]
@grubbins, I have to think about how to handle the cached images.

Currently, the caching is based on the text's MD5 signature which works great if the diagram text changes. In this case the included file changes.

I would have to parse the text and handle text with included files differently.

I will try adding a simple parser which will look for `!include path` if path is resolved to a file then its contents will be added to the MD5 computation.

It is not foolproof but will work for most include file situations.

**Comment by vsch** [comment]
The included file(s) must be saved to disk before changes are detected. I have not implemented checking to see if it is open in the IDE.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
