### ISSUE TITLE
Scroll preview to source position option doesn't work 

### ISSUE THREAD

**Issue by Jelmerb** [vsch/idea-multimarkdown#735]
IntelliJ IDEA 2019.1
Markdown Navigator 2.8.4.4

Hi Vladimir, I could be wrong but it seems the option to `Scroll preview to source position` doesn't work. I have the JavaFX web browser selected and enabled all the necessary options but the preview doesn't scroll to the position in the editor. Maybe I forgot something

<img width="647" alt="Screen Shot 2019-04-03 at 20 31 06" src="https://user-images.githubusercontent.com/6000226/55503854-cb9d4e80-564f-11e9-9d5e-7570d2fa87b8.png">

**Comment by vsch** [comment]
@Jelmerb, there is a spurious condition which I have not been able to duplicate which causes synchronization and highlighting current block/line to not work.

It happens most often after a new installation and license activation. Closing the editor and reopening it usually fixes the problem. The issue tends to disappear after the next IDE start.

I have been trying to find the conditions/timing which cause this for a long time but have not yet been able to duplicate it so I can understand and fix it.

**Comment by Jelmerb** [comment]
Closing the editor or restarting the IDE doesn't fix it unfortunately. If I can provide any other information that might help you find the problem, let me know.

**Comment by Jelmerb** [comment]
I got it working by accident! I changed back to the `Default - Swing` browser and then enabled the `JavaFX Web View` clicking on the tip that appeared which says something like `JavaFX browser available`.

**Comment by Jelmerb** [comment]
found another bug though, about Page Zoom not working.

**Comment by vsch** [comment]
@Jelmerb, I will check the code. What you are describing appears to be a corruption of saved settings. It gives me another information point to check.

**Comment by Jelmerb** [comment]
Ok, I did some testing. Some really weird stuff is happening. Somehow the synchronization stopped working again. So what I did is I changed the `Preview browser` option for the profile I use back to `Default - Swing`. No tip `JavaFX Web-Kit based preview renderer is available.` appeared so I changed it back again to `JavaFX WebView`. No luck!. For some reason I changed the profile setting back to `Default - Swing` again.

For the second try, I changed the `Preview browser` back to `Default - Swing` in the Project Settings. The tip `JavaFX Web-Kit based preview renderer is available.` appeared. Clicked on `Change preview browser to JavaFX`. Again no luck!

As a last resort I changed the `Preview browser` setting for the profile back to `JavaFX WebView`, so both the Project Settings and profile `Preview browser` options are set to `JavaFX WebView`. Preview is scrolling again! Maybe this can help you pinpoint the location of the problem. 

If I can find out when it stops working again, I'll let you know.

**Comment by vsch** [comment]
@Jelmerb, I think I found the bug. There was an uncaught JS script exception which was silently absorbed by Java code during initialization. It was causing the JS not to initialize properly and not have any ability to sync source or generate other JS events for Java use.

It was a real PITA to find and I stumbled on it almost by accident while working on something else. Have not had scroll sync issues since then.

I will mark this as fixed for next release but when you do try it please let me know if it is still an issue on your system after you try the new release.
