### ISSUE TITLE
Launching external URLs inside the browser

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#74]
It would be convenient to open external URLs in the browser ~~by pressing [Ctrl+Left Click]~~.

ref. https://upsource.jetbrains.com/idea-ce/file/idea-ce-b73203a379d61e892bffba1c40b05767b584b00c/platform%2Fplatform-api%2Fsrc%2Fcom%2Fintellij%2Fide%2FBrowserUtil.java?nav=3159:3263:focused&line=89

**Comment by vsch** [comment]
I will add this to the list for next release if I can fit it in. Otherwise, it will be in the release after that which is two weeks later.

**Comment by vsch** [comment]
@breandan for now you can click on the link in preview and if the link is browsable (http://, https://, mailto:, ftp://) it will launch the browser. If the link is relative to the current page and it resolves to a file that is under VCS it too will launch the browser to that file on GitHub.

Except I did not know about the browser utils and used the java desktop interface. I'll change that to the standard IntelliJ utils. 

The reason I tend to fall back to standard, even if flaky, Java native stuff is because it is easier to get documentation and samples. :(

**Comment by vsch** [comment]
Sorry, had to bump it to the next one because I ran out of time for this release.

**Comment by holgerbrandl** [comment]
Was this fixed? I've tried all kind of modifier keys to open a link from the editor (not the preview), but no luck yet.

**Comment by vsch** [comment]
I was not  able to do this because it is not compatible with OSX. Ctrl+Left Click is actually a right click on OSX. None of the IDE ctrl+left click work either.

**Comment by breandan** [comment]
This feature could be bound to the current navigation action - ie. when the user normally navigates to a markdown link, if the link text is an external URL then call `BrowserUtil` instead of jumping to source (where the exact keystroke [Ctrl+Left Click] is not important).

**Comment by holgerbrandl** [comment]
I actually don't mind at all how to do it, but being able to navigate to an external URL from the editor would be great. Currently I'm forced to go via the preview.

**Comment by vsch** [comment]
@breandan, @holgerbrandl, I will look into overriding the navigate to element method for external links that don't map to project files and pass it to external browser.

**Comment by holgerbrandl** [comment]
Thats great news. Thanks for your excellent plugin

**Comment by vsch** [comment]
* Add: #74, Launching external URLs inside the browser, now `navigate to declaration` opens url
  in browser, ftp or mail client depending on the link. Can also use line markers for navigation
  of these elements.

EAP updated.

**Comment by holgerbrandl** [comment]
Thanks. Works like charm.

**Comment by holgerbrandl** [comment]
Not sure if I'm doing it wrong, but when using 2.5.2.20, the navigation from the editor to the link target (e.g. by opening a browser) does not work any longer. Or has the keybinding changed?
![image](https://user-images.githubusercontent.com/200952/41338098-6dff6330-6ef1-11e8-9073-970e1557277b.png)

**Comment by vsch** [comment]
@breandan, just checked and it works for links but not for auto-links. That is why it does not work.

Auto-links are not treated as links in general. They only recognize a limited link addressing formats.

I will add them for navigation purposes and see how hard it is to add them to other functions like  refactoring.

**Comment by holgerbrandl** [comment]
Awesome, thanks!

**Comment by vsch** [comment]
@breandan, now you can navigate using the ctrl+click on URL links and F1 will load the page and display as documentation. Not very useful unless pages are simple.

Best use is for GitHub issue URLs, I parse and simplify the HTML so it displays as documentation.

![image](https://user-images.githubusercontent.com/10299086/51798938-7e80a480-21e8-11e9-90f2-13d45e4ccbec.png)

**Comment by breandan** [comment]
Thanks, been using this feature quite a bit recently. Works great!

**Comment by vsch** [comment]
@breandan, please keep your feature requests and feedback coming. Many of the features you requested, I cannot work without now.

BTW, just released 2.8.0. Last minute addition: text, html and link drag drop into markdown from other applications.

**Comment by breandan** [comment]
Sure, will let you know when I think of something. Pretty happy with the updates recently, keep up the great work! This plugin has helped me write a bunch of documentation, it's really useful.

**Comment by vsch** [comment]
I am glad. This is its main purpose--make documentation a joy, or at least less grunt work and more brain work.
