### ISSUE TITLE
Plugin creates files under .idea with default settings

### ISSUE THREAD

**Issue by yole** [vsch/idea-multimarkdown#746]
When I run the plugin for the first time, if I don't change any settings, the plugin creates .idea/markdown-navigator.xml, .idea/markdown-navigator/profiles_settings.xml and modifies .idea/codeStyles/Project.xml. None of this should happen. The plugin should store only settings that differ from defaults, and the platform provides APIs needed to implement that.

**Comment by vsch** [comment]
@yole, that part of settings does not use the API for historical reasons. 

It was implemented in Kotlin when Kotlin was still in beta and there was no serialization support. So I rolled my own serialization.

I will either need to migrate all settings to the API or add logic to not serialize default values.
