### ISSUE TITLE
Useless "Markdown Export On Settings Change" notifications

### ISSUE THREAD

**Issue by yole** [vsch/idea-multimarkdown#747]
I didn't request anything to be exported, so there is no reason to notify me that export will happen later or has not happened.

**Comment by vsch** [comment]
@yole, good point. I will add code to see if there is anything to export.

**Comment by vsch** [comment]
@yole, notification disabled if no profiles have update on save. The notification will still display if there are profiles with export but no files are in scope for the profile.

Determining whether there are actual files to export requires finding files that are in scope for the profile which cannot be done in dumb mode.
