### ISSUE TITLE
[Q] Add docs/examples how to deal with/embed mermaid

### ISSUE THREAD

**Issue by gaydenko** [vsch/idea-multimarkdown#750]
Hi! Have got the one year License to play with embedded mermaid. But was not lucky to find a doc how to do it. Please, add to doc paragraph or two with examples.

**Comment by vsch** [comment]
@gaydenko, you only need to enable the parser extension for mermaid to have this working:

![image](https://user-images.githubusercontent.com/10299086/57541973-4d069180-731e-11e9-8d4c-a6c3fa4057ac.png)

**Comment by vsch** [comment]
* Chart fenced code blocks with info of `mermaid` using
    [Mermaid](https://github.com/knsv/mermaid)

**Comment by gaydenko** [comment]
> @gaydenko, you only need to enable the parser extension for mermaid to have this working:
> 
> ![image](https://user-images.githubusercontent.com/10299086/57541973-4d069180-731e-11e9-8d4c-a6c3fa4057ac.png)

That your image can not be rendered for some reason. At any case I have enabled parser options:
![MNoptions](https://user-images.githubusercontent.com/3740016/57543075-02a40580-735c-11e9-8a4d-173a897a8630.png)
But still haven't got any rendering:
![MNandMermaid](https://user-images.githubusercontent.com/3740016/57543111-18b1c600-735c-11e9-88d2-cfdf57659a87.png)

**Comment by vsch** [comment]
@gaydenko, mermaid requires JavaFX WebView preview.

Mermaid is implemented in a JavaScript in the browser so it requires JavaScript support in preview.

From your screenshot I can see that your preview is Swing which cannot display mermaid charts.

**Comment by gaydenko** [comment]
Probably it isn't the end of story as far as switching to JavaFX Webview is still insufficient:
![MNandMermaid2](https://user-images.githubusercontent.com/3740016/57543676-b78af200-735d-11e9-8ba9-dfa7afc957ff.png)

**Comment by vsch** [comment]
@gaydenko, it is also dependent on Mermaid script on the Stylesheet page. It is turned on when you turn on the Mermaid parser option but it probably fails to set it when you change preview while the parser option is already set:

![image](https://user-images.githubusercontent.com/10299086/57543804-64944900-7323-11e9-950b-f75116c366cd.png)

**Comment by gaydenko** [comment]
Yes, stylesheet option was not selected - have missed it. Thanks!
