### ISSUE TITLE
Disable MD unfolding in the file tree

### ISSUE THREAD

**Issue by ivan-kleshnin** [vsch/idea-multimarkdown#752]
How to disable MD unfolding in the file tree? Since one of the last updates it started to show inner file sections. 

This new feature drives me mad because it undermines my workflow. I have a huge tree of files where each level of nesting counts (against usability). Now I need to click twice to open a file and the project tree is cluttered with a junk information. 

![shot](https://user-images.githubusercontent.com/2128182/57919345-5012fc00-78a1-11e9-9ea0-9e28b26eaf9f.png)

**Comment by vsch** [comment]
@ivan-kleshnin, the display of headings in project view for markdown documents is controlled by project view setting `Show Members`:

![image](https://user-images.githubusercontent.com/10299086/57942736-44730580-78a0-11e9-8c7e-8b66636760ab.png)

This affects all files not just Markdown.

**Comment by ivan-kleshnin** [comment]
Got it. Thank you!
