### ISSUE TITLE
Numbered list preview not in sync with code

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#753]
Example:
![image](https://user-images.githubusercontent.com/200952/58006277-010ad800-7ae8-11e9-884c-e96fc7d00cba.png)

Expected Behavior: List numbers should be in sync with the code.

**Comment by vsch** [comment]
@holgerbrandl, you need to either set parser lists option to CommonMark which supports control of the first list item number or to indent the fenced code elements so they appear as child items of list items and do not interrupt the list causing a new list to be started for each item.

`````markdown
1. list item 1

    ```shell
    cd /test
    ```

2. list item 2

    ```shell
    cd /test
    ```

3. list item 3

    ```shell
    cd /test
    ```
`````

![image](https://user-images.githubusercontent.com/10299086/58101953-7f31b200-7bae-11e9-83fe-b63e07b26105.png)

**Comment by holgerbrandl** [comment]
I see, thanks for the pointer.
