### ISSUE TITLE
Add autocompletion for java, kotlin within fenced code blocks

### ISSUE THREAD

**Issue by efemoney** [vsch/idea-multimarkdown#754]
I noticed there is language injection for `javascript`, `xml`, `json` etc. within fenced code blocks but none for `java` or `kotlin`.

Is this something I can add/update myself?

**Comment by vsch** [comment]
@efemoney, language injections are added to fenced code in the **enhanced** version of the plugin if the options for this are enabled:

![image](https://user-images.githubusercontent.com/10299086/58370397-098e5480-7ed4-11e9-976d-8a527bb31875.png)

If you do not have a license you can get a trial license https://vladsch.com/product/markdown-navigator/try

**Comment by efemoney** [comment]
@vsch Unfortunately something is wrong with the image you uploaded.

Also, I got a trial license to confirm for myself and I'm afraid nothing changed.

![image](https://user-images.githubusercontent.com/8434606/58382414-286f1280-7fca-11e9-86c3-54ced4053705.png)
![image](https://user-images.githubusercontent.com/8434606/58382419-3755c500-7fca-11e9-9ee0-d5721d389f42.png)

...`java` and `kotlin` are still unavailable for auto completion in fenced code blocks.

**Comment by vsch** [comment]
@efemoney, my misunderstanding. I thought it was code completion inside fenced code that was not working, which requires the enhanced version of the plugin.

The language completion strings are taken from the IDE which means that the language has to be supported by the IDE for it to appear in the completion suggestions.

I suspect that the IDE you are using is not IntelliJ which supports java and Kotlin but something like WebStorm or PhpStorm which do not. Is this correct?

**Comment by efemoney** [comment]
> I suspect that the IDE you are using is not IntelliJ which supports java and Kotlin but something like WebStorm or PhpStorm which do not. Is this correct?

Ah yes, you're right
