### ISSUE TITLE
in idea 2019.2 eap editor is broken, show loading forever

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#756]
in idea 2019.2 eap editor is broken, show loading forever

![image](https://user-images.githubusercontent.com/167966/58968417-9d232780-87e8-11e9-8296-971e23473c63.png)

![image](https://user-images.githubusercontent.com/167966/58968566-d491d400-87e8-11e9-99cd-071df092dc74.png)

**Comment by vsch** [comment]
@bluelovers, I will be making an EAP release with the fix shortly.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
