### ISSUE TITLE
Gitlab multi-line blockquote syntax incorrect

### ISSUE THREAD

**Issue by wangles** [vsch/idea-multimarkdown#757]
The documentation states:

> Multiline block quotes using >>> at start of line to mark block start and <<< at start of line to > mark block end. GFM: Multi-line Blockquote

This works and renders correctly in the ide.

However, the Gitlab spec states that the closing symbol should be `>>>`. Thus, it renders incorrectly in Gitlab.

[GFM: Multi-line Blockquote](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md#multiline-blockquote)

**Comment by vsch** [comment]
@wangles, thank you for pointing this out. It is a bug in the implementation. I will have it fixed for next EAP release, due shortly.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by wangles** [comment]
Thanks for the quick fix. For the record, I liked your syntax better.

**Comment by vsch** [comment]
@wangles, I also liked my syntax because it allowed nested block quotes. I guess I assumed that the correct syntax was the one giving more functionality. My bad.
