### ISSUE TITLE
can't found where disable link warp with `<>`

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#758]
can't found where disable link warp with `<>`

at before, i remember it can be disable and i disable it

![image](https://user-images.githubusercontent.com/167966/59601624-23b7fd00-9137-11e9-9b30-e5a18241bb52.png)

video
[bandicam 2019-06-17 19-34-22-527.zip](https://github.com/vsch/idea-multimarkdown/files/3296770/bandicam.2019-06-17.19-34-22-527.zip)

**Comment by vsch** [comment]
@bluelovers, how are you getting the links wrapped with `<>`. The syntax for having auto-links wrapped with `<>` is standard common mark so it cannot be turned of in the parser, however if the parser `Auto Links` extension is enabled then auto-links without `<>` will also be recognized.

Turning off the auto-link wrapping inspection can be turned off when the inspection pops up.
