### ISSUE TITLE
Table sorting [Feature request]

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#759]
It would be awesome to make tables sortable with two new menu items using the column the cursor is currently in and obviously not including the table header.

![image](https://user-images.githubusercontent.com/3531020/59779196-1c6c2d00-92b8-11e9-8f4c-202a81c9b49c.png)

**Comment by vsch** [comment]
Table Sort added:

![Screenshot_TableSort](https://user-images.githubusercontent.com/10299086/71537635-cb836400-28ec-11ea-8329-6b8255fc4f29.png)
