### ISSUE TITLE
html paste option can't save

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#761]
![image](https://user-images.githubusercontent.com/167966/61207951-ea1fe500-a728-11e9-862a-9d2f1ea95a07.png)

click button but nothing happen

![image](https://user-images.githubusercontent.com/167966/61208021-0d4a9480-a729-11e9-9d53-f352a21ce003.png)

**Comment by vsch** [comment]
@bluelovers, bug confirmed. Will release EAP with fix shortly.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
