### ISSUE TITLE
freeze when target link is a big file (16mb)

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#762]
when hover arrow will freeze

![image](https://user-images.githubusercontent.com/167966/62508793-76f72380-b83b-11e9-97e9-ddb0c0be90dc.png)

**Comment by vsch** [comment]
@bluelovers, the only thing I can think of that can cause this is the following setting, which you should try to turn off. I will add code to use only the first few thousand chars for the doc comment.

![image](https://user-images.githubusercontent.com/10299086/62547967-157f8680-b834-11e9-961c-08e6d827ffc6.png)

**Comment by vsch** [comment]
@bluelovers, I found the bug causing this. If an element is not part of the Markdown recognized classes then it used element.getText(), which for files is their content. Now if it is a file will use its name, other elements will display max 500 chars.
