### ISSUE TITLE
Very bad performance while editing document

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#763]
After adding a few large images to my Readme I noticed that editing text is very laggy ( after pressing keyboard key it takes a while few seconds for a character to appear) - it looks like images are redownloaded each time document is refreshed. 

Steps:
- checkout this project https://github.com/igorwojda/android-showcase/blob/master/README.md
- open it in Android Studio
- open README.md (root folder)
- try to add or remove some text

Markdown `v2.8.4.32`
Android Studio `3.4.2`

**Comment by vsch** [comment]
@igorwojda, performance has been addressed for next release. There is no lag now for files with many images.

![AndroidShowCaseReadme](https://user-images.githubusercontent.com/10299086/70099558-24692080-15fd-11ea-9973-53565c2fc8ef.gif)
