### ISSUE TITLE
Styling the preview pane

### ISSUE THREAD

**Issue by arturhun** [vsch/idea-multimarkdown#764]
Please correct me if I am wrong: when writing a markdown document, the writing pane style is governed by **Preferences | Editor | Color Scheme | Markdown**, but can the preview pane be customized?

I would like to be able to define some basic styling properties, such as
- background-color
- font-family
- font-size
- color

with distinction of text and code blocks.

Is it something that can be achieved now? If so, which page in the settings is responsible for that?

**Comment by vsch** [comment]
@arturhun, the preview pane is HTML so it uses stylesheets. There are 2 options included in the plugin for JavaFX: default and dark. JavaFX can also use the Swing style sheets which results in much simplified rendering.

To override the default CSS you need to change individual elements or the whole CSS.

There is more information on this in the wiki: [Customizing-HTML-Preview](https://github.com/vsch/idea-multimarkdown/wiki/Customizing-HTML-Preview)

**Comment by arturhun** [comment]
Oh I see.
What I was fooled by was naming. As I had previously used the bundled Markdown plugin, I was looking into Other Settings tab, and then when I looked into Language and Frameworks, I assumed that the Markdown item only applies to that JetBrains plugin.

Might be that a toolbar icon to directly access Settings would have helped me ;-)
Thanks, can be closed.

**Comment by vsch** [comment]
I will add a toolbar button for settings.

**Comment by vsch** [comment]
Settings button was added in version 2.9.9.
