### ISSUE TITLE
Can't get any diagram to show up

### ISSUE THREAD

**Issue by FunMiles** [vsch/idea-multimarkdown#766]
I've been trying to use this plug in with CLion and trying PlantUML graph in my .md file.
All I get in the preview is a source code grey box with the text for the diagram. Never get the diagram itself.
Is there something to turn on?

PS: Using CLion 2019.2 on Mac OS X 10.14.6

**Comment by vsch** [comment]
@FunMiles, sorry about the delay in replying. My inbox overflowed and this notification was pushed out of sight.

Plant UML is an extension to markdown and is not enabled by default to render the diagrams. Enable in parser settings:

![image](https://user-images.githubusercontent.com/10299086/63894520-cd7afc00-c9ba-11e9-9529-2ed6c1816973.png)

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/10299086/63894563-f0a5ab80-c9ba-11e9-8977-7f2edb187528.png">

**Comment by FunMiles** [comment]
@vsch, thanks. It took me a while to get back to working with this. 
Just one little note to help others who may have tried and messed things up:
   I had tried many option and under the "HTML Generation" tab of preferences, I had chosen "Gravizo SVG". With that turned on, I got the lines and text but not the boxes around the the text.
Switching back to "Embedded Library" fixed that.
