### ISSUE TITLE
Clicking on a link on HTML preview screen hangs the PhpStorm

### ISSUE THREAD

**Issue by RiderSx** [vsch/idea-multimarkdown#77]
Ubuntu 14.04 x64, PhpStorm 143.1212, MultiMarkdown 1.2.3.

**Comment by vsch** [comment]
@RiderSx can you please provide a bit more information

1. Does this happen for all links or specific one?
2. If specific one can you please provide it so I can debug it.
3. Are you using the JavaFX WebView preview or the 'Old Preview' which is swing based?
4. 3 makes a difference because links are handled slightly differently by each version.
5. Are you running it in Enhanced mode via a license or trial license? Only makes a difference when links use relative addressing, enhanced resolves these the basic does not.

**Comment by RiderSx** [comment]
@vsch sure.

1. For all links.
2. -
3. Have no idea, didn't choose it.
4. -
5. No license, links are absolute.

**Comment by vsch** [comment]
@RiderSx thank you I will try it in UBuntu.

Can you enable the HTML Text tab in Preferences for MultiMarkdown and see what the link addresses look like?   Preferences <kbd>Other Settings > MultiMarkdown</kbd> general tab. Check the 'Show Html Text' and the 'Show Modified' check boxes. 

<img width="833" alt="screen shot 2015-12-04 at 11 32 25 am" src="https://cloud.githubusercontent.com/assets/10299086/11595049/75ae884c-9a7b-11e5-975d-906d5f584068.png">

After changing the setting reopen the file if it was already open and you should see the `HTML Text` tab. Select it and it will show the HTML used for rendering the page in the preview tab. See if the links look like you intended them.

If the above is all good then I suspect that it is a problem with launching browser URL's in Java. I am going through the standard Java Desktop API. The JetBrains API for launching the browser might work better. Please let me know and I will make a version for you that uses the JetBrains browser API.

FYI, the web view looks more like GitHub, especially the page header, as in the left image, below. You can also go to Preferences > Other Settings > MultiMarkdown, on the General tab there is a check box 'Use Old Preview' it is selected if JavaFX is not available or for some reason threw an exception during initialization of the WebView preview tab.

<img width="1385" alt="screen shot 2015-12-04 at 11 27 25 am" src="https://cloud.githubusercontent.com/assets/10299086/11594840/49931ecc-9a7a-11e5-847b-9742d819b12b.png">

**Comment by RiderSx** [comment]
@vsch much thanks for detailed answer :)
In HTML text links looks as intended.

**Comment by vsch** [comment]
@RiderSx , you are welcome.

It must be the java Desktop API. I will make the change and upload the plugin zip to this repo and post the link here. You will need to download it and in Preferences > Plugins  use the Install plugin from disk button to install it.

<img width="933" alt="screen shot 2015-12-04 at 11 48 47 am" src="https://cloud.githubusercontent.com/assets/10299086/11595363/157ae572-9a7d-11e5-93e5-c323f35c69e8.png">

**Comment by RiderSx** [comment]
@vsch thank you, good sir

**Comment by vsch** [comment]
@RiderSx, please download <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.2.3.1.zip> and install. If this one works then the issue was the Desktop API.

**Comment by RiderSx** [comment]
@vsch works like swiss watches :)

**Comment by vsch** [comment]
@RiderSx, thank you for taking the time to report the issue and help eliminate another platform incompatibility. These are notoriously difficult to resolve. Much appreciated.
