### ISSUE TITLE
macOS: Paste doesn't work when copying link from Safari's context menu

### ISSUE THREAD

**Issue by ksilz** [vsch/idea-multimarkdown#771]
Hi,

I use the latest versions of macOS, WebStorm and the Markdown Navigator plug-in. Now I can't paste this URL into a WebStorm Markdown document with either [Cmd]-[V] or with the menu item:
https://github.com/jhipster/generator-jhipster/issues?q=milestone%3A6.2.0+is%3Aclosed

Paste does work through the "Edit - Paste without Formatting" menu option. Please see the attached "Paste does not work in WebStorm.gif" for details.

It only happens when I copy a link from the Safari context menu with "Copy Link" - see "Paste still does not work.gif" for more.

Regards,
Karsten Silz

![Paste does not work in WebStorm](https://user-images.githubusercontent.com/1061209/63947884-aa5e5400-ca6f-11e9-8d9b-f78f72acfa06.gif)

![Paste still does not work](https://user-images.githubusercontent.com/1061209/63947924-b813d980-ca6f-11e9-8005-4ddb5b59e36e.gif)

**Comment by vsch** [comment]
@ksilz, thank you for reporting it. I did not notice the change in Safari but it stopped providing text/html clipboard type when copying a link.

I will try to figure out which of the provided types I can use to duplicate the previous functionality.

**Comment by vsch** [comment]
@ksilz, the new format is also erroneously detected as Linux file URI list but result returns no files so the plugin has nothing to paste. I will fix this also.

As a workaround you can select the link text and copy it. The resulting HTML will be handled as before.

**Comment by vsch** [comment]
@ksilz, the erroneous Linux file url list is fixed so the link will paste the link address. 

I was unable to get access to the other clipboard data flavours in java (public.url-name) for the link text so only the address is pasted.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by ksilz** [comment]
@vsch, thank you for the quick reply! I'm waiting for the next release, I guess.

**Comment by vsch** [comment]
@ksilz, I will re-open it because it is not fully fixed. I would like copy from link to paste link with text. The information is available on the clipboard. I just have to figure out how to get access to it from Java.
