### ISSUE TITLE
Solarized Dark scheme uses Solarized Light colors

### ISSUE THREAD

**Issue by DarkGhostHunter** [vsch/idea-multimarkdown#772]
![image](https://user-images.githubusercontent.com/5141911/64080286-3961ab00-ccc0-11e9-919a-48e60f096e3e.png)

1. Pick Solarized Dark and Darkula as your Editor Color Scheme and IDE Color Scheme.
2. Open a Markdown file
3. See remnants of Solarized Light color scheme.

**Comment by vsch** [comment]
see #177, the scheme is not properly declared as a Darkula scheme. So the IDE uses plugin's light scheme.
