### ISSUE TITLE
Pasting URL from chrome pastes meta-data

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#773]
When copying a url from chrome and paste it, it is now pasting 
```
Version:0.9 StartHTML:0000000105 EndHTML:0000000298 StartFragment:0000000141 EndFragment:0000000262 <https://github.com/vsch/idea-multimarkdown/issues/new>
```
instead of just
```
https://github.com/vsch/idea-multimarkdown/issues/new
```

It just happens when pasting from chrome (under Win10). Microsoft Edge and Firefox are fine.

**Comment by vsch** [comment]
@holgerbrandl, I will check that. Could be some change on Chrome in Windows that changed available formats on copy.

Safari under OS X Mojave also f-up the link copy. It used to put a dozen formats on the clipboard, including HTML. Now there is about 6 and no HTML.

**Comment by vsch** [comment]
@holgerbrandl, got my Windows dev environment updated. Issue was Chrome now pasting HTML snippet which has metadata prefix. Now removed.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by holgerbrandl** [comment]
Awesome, I've already installed the EAP build and it works great.
