### ISSUE TITLE
Ignore character casing when checking for matching header

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#779]
We want the header to have first letter uppercase, yet in the sentence, we would prefer lowercase, so I think this check should be case insensitive.

![image](https://user-images.githubusercontent.com/530122/66268528-12097b00-e836-11e9-8548-ed3b0427b53d.png)

`v2.9.0.20`

**Comment by vsch** [comment]
@igorwojda, good point. I will change it by adding an option for annotations to allow turning off case sensitivity.
