### ISSUE TITLE
[Solved] Preview not work when typing non-ascii chars in Linux.

### ISSUE THREAD

**Issue by SvenAugustus** [vsch/idea-multimarkdown#781]
![image](https://user-images.githubusercontent.com/11767671/67465958-c863c180-f678-11e9-9db8-3ed426ff4276.png)

Environment：
MarkDown Navigator Version: 2.9.7
IDEA 2019.2.3
OS: Manjaro 18.1.1 Juhraya
Kernel: x86_64 Linux 4.19.79-1-MANJARO

**Comment by vsch** [comment]
@SvenAugustus, the fonts used by the Swing preview browser do not have those characters. There is a workaround in #533 for PDF export which will also work for preview, just add those settings to project defaults for Markdown Navigator: Languages & Frameworks > Markdown > Stylesheet. 

The instructions for PDF Export fonts are in the wiki https://github.com/vsch/idea-multimarkdown/wiki/Rendering-Profiles-Settings#configuring-for-cjk-character-sets. Both issues are the same. The HTML generated uses characters not in the default fonts so other font has to be used for proper display.

**Comment by vsch** [comment]
@SvenAugustus, if the font is installed in your system you probably do not need to provide the src URL to the file. Not sure if removing the src: line will help. I need to try it on my system with an installed font.

Will get back to you shortly. Waiting for IDE update and re-indexing before I can try anything.

**Comment by vsch** [comment]
@SvenAugustus, you are using Swing preview browser, this one has different style sheet classes and element definition to get around Swing limitations. Your settings will work with JavaFX preview browser. Which also has JavaScript support so more stylesheet options will work with it.

![image](https://user-images.githubusercontent.com/10299086/67476748-9e81af00-f626-11e9-9881-0aa25081030f.png)


However, if you want Swing browser then the custom css should change the swing css defaults:

```
code,
span.code,
samp,
var,
span.var,
kbd,
span.kbd,
span.tt {
    font-family: Consolas, Inconsolata, "Liberation Mono", Menlo, Courier, Monospaced, monospace;
    font-size: 1em;
}
```

And the proportional definition:

```
body.multimarkdown-preview,
body.multimarkdown-wiki-preview {
    background-color: white;
    font-family: "Helvetica Neue", Helvetica, Arial, freesans, sans-serif;
    font-size: 11px;
    padding: 20px;
}
```

**Comment by SvenAugustus** [comment]
It works in JavaFX. thanks a lot.
