### ISSUE TITLE
Links containing anchor are incorrectly coloured

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#782]
Link anchor should be ignored (it's not markdown anchor)
![image](https://user-images.githubusercontent.com/530122/67671666-491f0800-f96e-11e9-8510-0288948b0f3b.png)

**Comment by vsch** [comment]
@igorwojda, AST Element for syntax highlighting is done at parse time when it is not known if the links is a local project file or just a URL. 

Remote URL anchors can be validated and completed if you select the options:

![image](https://user-images.githubusercontent.com/10299086/67672121-9dfe5680-f94d-11e9-81d3-43dc9f0cdf56.png)

**Comment by vsch** [comment]
BTW, you can change the anchor text color in Editor > Color Scheme > Markdown so they have the same colour as the link address.
