### ISSUE TITLE
I want to hide toc in project view

### ISSUE THREAD

**Issue by alanhg** [vsch/idea-multimarkdown#789]
how to do?

![image](https://user-images.githubusercontent.com/9245110/69901314-c77e2800-13ba-11ea-9eaf-5d2502027bdd.png)

**Comment by vsch** [comment]
@alanhg, can you show a screen shot of what you are referring to, exactly?

**Comment by alanhg** [comment]
As shown in pic

**Comment by vsch** [comment]
@alanhg, you have enabled "Show Members" in the project tree. The headings in markdown show as members.

Disable it and the headings from markdown will not show.

<img width="556" alt="image" src="https://user-images.githubusercontent.com/10299086/69902101-ae905b00-1357-11ea-937b-aa29b5d4887b.png">

**Comment by alanhg** [comment]
@vsch I see, thank you!
