### ISSUE TITLE
Add split editor for HTML Preview as an option to editor tabs.

### ISSUE THREAD

**Issue by vsch** [vsch/idea-multimarkdown#79]
This feature request was buried in #69. It is significant enough to deserve its own issue.

**Comment by mt3o** [comment]
If it's not to late for me to add this, it would be great to be able to hide the HTML preview complitly. Sometimes it's not that important to see the preview all the time.

**Comment by vsch** [comment]
@mt3o, not at all too late. I am working on it right now and yes that will be available as one of the configurations. 

I am basing it on Markdown Support plugin from JetBrains with existing idea-multimarkdown features added on top. The split view will have Editor Only, Preview Only, Editor & Preview Split configurations. The preview part will be in one of the following states: HTML Preview, HTML Text (modified for preview browser type: Swing, Lobo, JavaFX), HTML Text (unmodified) as rendered by pegdown plain vanilla with minimal HTML.

All these will be switchable on the fly via toolbar or keyboard shortcuts just like Markdown Support. I really like the way it is implemented in that plug.

**Comment by obestwalter** [comment]
:+1: looking forward to this feature! Especially being able to switch these with keyboard shortcuts will be great!

**Comment by vsch** [comment]
@mt3o new release available with split editor.

@obestwalter the short cuts are Ctrl-P on Win and Cmd-P on Mac for switching layout and Ctrl+Shift+P and Cmd+Shift+P on the Mac for switching preview between Rendered HTML / HTML Text and Plain HTML as generated by pegdown.
