### ISSUE TITLE
README.md automatically opens when I open old projects -- is it because of this plugin?

### ISSUE THREAD

**Issue by LordPachelbel** [vsch/idea-multimarkdown#794]
At some point recently whenever I've opened a project in Phpstorm that I haven't opened for a while, it has been automatically opening the `README.md` file in the editor window. I'm just wondering if this is happening because of a recent update to this plugin, or if it's because of a recent update to Phpstorm.

**Comment by vsch** [comment]
The plugin does not open files on its own. Must the IDE.

**Comment by LordPachelbel** [comment]
Thanks!

**Comment by LordPachelbel** [comment]
I asked JetBrains about it on Twitter and got this reply:

> That's a new feature. Press Shift-Shift, enter "Registry", change the ide.open.readme.md.on.startup option to false.

https://twitter.com/phpstorm/status/1208071145746051072

**Comment by vsch** [comment]
@LordPachelbel, thank you for the update. I suspected as much. There are  a lot of changes added by default in the new releases. Some questionable value and no UI access to turn off.

Some even have default keyboard shortcuts that you can hit accidentally and then wonder how to turn it the F off. Been there. Done that.
