### ISSUE TITLE
Latest version : All options in plugin settings cleared. Reset to defaults does not work.

### ISSUE THREAD

**Issue by martinlanton** [vsch/idea-multimarkdown#801]
Numbered lists as well as everything nested in them (ex : bullet point lists made using the * character and nested inside numbered lists) do not display as they should in the latest release of the plugin.

**Comment by vsch** [comment]
@martinlanton, your settings are messed up. Please reset to defaults or restore them from VCS if you have them under VCS.

See: https://github.com/vsch/idea-multimarkdown/issues/796#issuecomment-568581439

**Comment by martinlanton** [comment]
@vsch I never even touched the settings, I'm using the default ones.

**Comment by vsch** [comment]
@martinlanton, did you have a previous version of the plugin installed or is 2.9.9 the first installation?

Previous release version was not compatible with 2019.3 beta and the IDE would recommend installing a really old version. Installing that would blow away the settings.

I am also not sure if the incompatible version only got far enough to mess up the settings. I have to double check that.

**Comment by martinlanton** [comment]
@vsch I had a previous version installed when I was on 2019.2, then switched to pycharm 2019.3 and as soon as it was available, I upgraded to 2.9.9.

I tried using the button provided to reset the settings to default, unfortunately, as I mentioned before, the current settings seem to be the default one, as clicking on that button didn't change anything.

**Comment by vsch** [comment]
@martinlanton, in that case could you paste a screenshot of your parser settings: Languages & Frameworks > Markdown > Parser

And also give me an example of your numbered list that do not display properly, preferably pasted into fenced code in the comment so I can see the raw text.

**Comment by martinlanton** [comment]
Here are the settings : 

![settings](https://user-images.githubusercontent.com/16347152/71533096-c3570480-28ab-11ea-9da2-c1b8ae406f5d.jpg)

Here are the examples, none of those work :
`* A set of instructions :
  1) a first instruction
  2) a second instruction
  3) a third instruction

1) something :
    * a thing
    * another thing
    * a third thing

1) just an element of a list  
2) just another element of a list    
3) just a third element of a list    `

**Comment by vsch** [comment]
@martinlanton, all your settings are cleared. If you do a settings reset on the main markdown settings panel then come back to this panel you should see defaults restored.

This is causing your parser to not process anything properly. The lists are set to 4 spaces fixed which is not the correct setting for defaults. This is the default for historical reasons but no longer the default setting.

**Comment by martinlanton** [comment]
@vsch as I just mentioned, resetting the main markdown settings doesn't seem to work, it doesn't do anything.

**Comment by martinlanton** [comment]
I just uninstalled and reinstalled the plugin, and this didn't change anything.
Also tried to reset the settings after reinstalling, and this didn't change anything either.

**Comment by vsch** [comment]
@martinlanton, can you please send me the project settings files form the plugin. They are located in the `.idea` sub-directory of the project directory  and start with markdown-navigator.

Also if you export Markdown Navigator settings (in the same menu as reset) and send that file to me **vladimir at vladsch.com**. Normally, only the latter would be enough but in this case I would like to see actual saved setting files for the plugin.

I want to use them for testing to see what causes this.

I will test them on pycharm so I have exact conditions of your system.

**Comment by martinlanton** [comment]
@vsch That's sent, thank you for looking into this!

**Comment by vsch** [comment]
@martinlanton, thank you for sticking to it and sending me your settings. I appreciate you taking the time to give me a chance to figure out what #@$@#@ is going on.

BTW, reinstalling the plugin does not delete the plugin settings for the IDE nor the project so it does not help. I will figure out how to  add a test on installation for existing settings and prompt to use them or discard them so re-install will have a chance of initializing the system.

This is what reset was intended to do--Reset to installation defaults. 

I will let you know as soon as I have a fix and probably a workaround for this issue.

**Comment by martinlanton** [comment]
Thanks @vsch

**Comment by vsch** [comment]
@martinlanton, found the bug. Fixed and added code to detect invalid settings on load and correct them without needing to reset settings.

I will make a new release shortly. There are a few show stopper bugs that made it into the last release, including this one.

**Comment by vsch** [comment]
@martinlanton, fixed plugin released. Thank you for providing me with your settings. They were indispensable. I must have copied them over to my test project two or three dozen times before I got the fix working.

**Comment by martinlanton** [comment]
I'm glad I could help! I will download the new version! Thanks a lot!
