### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marquisXuan** [vsch/idea-multimarkdown#802]
![image](https://user-images.githubusercontent.com/22328979/71498645-1921b180-2898-11ea-81a4-e90bcc95586d.png)

this is wrong .

![image](https://user-images.githubusercontent.com/22328979/71498667-32c2f900-2898-11ea-8e89-3cfe320062f8.png)

this is true. 

what should I do?

IDE: Intellij IDEA 2019.3
Version: 2.9.9

**Comment by vsch** [comment]
@marquisXuan, your settings are messed up. Please reset to defaults or restore them from VCS if you have them under VCS. All parser extensions are cleared, including fenced code which would cause what you are seeing.

See: https://github.com/vsch/idea-multimarkdown/issues/796#issuecomment-568581439

**Comment by vsch** [comment]
@marquisXuan, please let me know if Reset settings works for you. One user reported that reset settings to defaults does not work on his system.

**Comment by vsch** [comment]
@marquisXuan, fixed plugin released. It will detect and fix settings. Also reset settings fixed.
