### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by lapidus79** [vsch/idea-multimarkdown#811]
Are there any examples on how to insert a Table of Contents section. I can't see any references to any table of contents stuff anywhere. I'm using the paid version.

**Comment by vsch** [comment]
@lapidus79, you need to turn on the "Table of Contents" parser extension in Languages & Frameworks | Markdown | Parser and insert a line with `[TOC]: #` where you want the table of contents generated.

https://github.com/vsch/idea-multimarkdown/wiki/Table-of-Contents-Extension

**Comment by lapidus79** [comment]
Ah, now I found it. Thx
