### ISSUE TITLE
Unresolved link reference for wiki page

### ISSUE THREAD

**Issue by lndmflngs** [vsch/idea-multimarkdown#821]
Unresolved link reference for wiki url (wiki is empty for now, but for other empty wiki's there is no such problem)
Have tried with early access program, but get same error 

![image](https://user-images.githubusercontent.com/18148878/74730092-934a3300-5256-11ea-9680-77875350a048.png)

**Comment by vsch** [comment]
@lndmflngs, the links are tested by trying to get a page from the URL if remote links are validated. In some cases GItHub and other sites will not respond with an error and instead show some default page. If that happens then the link will not show an error.

If the wiki exists and is public then the link should resolve. It should also resolve if the wiki is part of the current project, see [Adding GitHub Wiki to IntelliJ Project](https://github.com/vsch/idea-multimarkdown/wiki/Adding-GitHub-Wiki-to-IntelliJ-Project)
