### ISSUE TITLE
Can I use asterisk as bullet for bullet list?

### ISSUE THREAD

**Issue by sjdeak** [vsch/idea-multimarkdown#824]
"Toggle Bullet List Item" action will create a bullet list starts with "-" as  bullet character by default.
![image](https://user-images.githubusercontent.com/8575264/75674421-f066cf80-5cbf-11ea-8403-fbc150fc35ed.png)

Is there a way that I can use asterisk as the default bullet character? So that "Toggle Bullet List Item" action will create a list like the second one:
![image](https://user-images.githubusercontent.com/8575264/75674316-c8776c00-5cbf-11ea-9628-1f91f8b88e0a.png)

Thanks!

**Comment by vsch** [comment]
@sjdeak, the bullet marker for new items is defined in Editor | Code Style | Markdown, lists tab via the `New bullet item marker` setting:

![image](https://user-images.githubusercontent.com/10299086/80262167-9d275280-865a-11ea-9c70-7036b8d1ec7f.png)

**Comment by sjdeak** [comment]
It works, thank you!
