### ISSUE TITLE
Korean language in "Preview" mode.

### ISSUE THREAD

**Issue by fartem** [vsch/idea-multimarkdown#825]
Korean characters are not displayed correctly in "Preview" mode.

**Example:**

Text: 한국어
Displaying: 

**IDE:** Android Studio 3.6.1 (based on IntelliJ IDEA 2019.2).
**Plugin version:** 3.0.

**Comment by vsch** [comment]
Please see #781. The font used for preview does not have these characters. A different font should be used.

Same goes for PDF Export, see: https://github.com/vsch/idea-multimarkdown/wiki/Rendering-Profiles-Settings#export-rendered-markdown-to-pdf-profile

**Comment by fartem** [comment]
@vsch thanks.
