### ISSUE TITLE
JavaFX markdown preview 3.0.197.72 seems to be broken (Intellij Ultimate 2019.3/mac/catalina)

### ISSUE THREAD

**Issue by reynoldsdj** [vsch/idea-multimarkdown#834]
After buying a license and updating to the latest version, the JavaFX Webkit preview is broken.  The Preview page shows nothing.

If I switch back to the Swing Preview, the preview appears on the screen.  I would be glad to post any logs, if someone could point me to them.

**Comment by vsch** [comment]
@reynoldsdj, I am running the same version on Catalina 10.15.3 with IU 2019.3.4 and JavaFX works fine, but this depends on the JRE with which the IDE is launched.

Are you running the IDE with bundled JRE or is it customized? 

Are you getting any errors? (The red flashing exclamation icon in the bottom right corner of the IDE after you open a markdown file with JavaFX Preview)

**Can you copy the information from the IDE About box by clicking on the clipboard icon (highlighted with red border below) and paste it here so I can see what is in your IDE config:**

![image](https://user-images.githubusercontent.com/10299086/78738361-ac4e9680-791f-11ea-9c3a-1d181b664760.png)

**Comment by reynoldsdj** [comment]
I am running the bundled JRE and have not customized it.  The only different is this is running on Catalina 10.15.4.  I am wondering if the issue was with the Catalina 10.15.4 update; that is probably around the time it stopped working.  Thanks, Apple.

Output from Intellij about box:
```
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
Licensed to Doug Reynolds
You have a perpetual fallback license for this version
Subscription is active until March 4, 2021
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: debugger.watches.in.variables=false, js.debugger.webconsole=false
Non-Bundled Plugins: com.intellij.plugins.watcher, IdeaVIM, Pythonid, com.daylerees.rainglow, com.dmarcotte.handlebars, com.dubreuia, com.github.redfoos.logstash-intellij-plugin, com.intellij.plugin.adernov.powershell, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.ini4idea, com.koxudaxi.pydantic, com.leinardi.pycharm.pylint, com.pablogsal.black, com.vladsch.idea.multimarkdown, com.wix.eslint, intellij.prettierJS, name.kropp.intellij.makefile, org.intellij.plugins.hcl, org.jetbrains.plugins.hocon, org.jetbrains.plugins.vue, org.toml.lang
```

**Comment by vsch** [comment]
@reynoldsdj, I have been hesitant to update OS X and wait a few months before updating. I remember having this hesitation about upgrading Windows.

There is probably an OS incompatibility in JavaFX. 

You can try to download a later JetBrains runtime: https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-osx-x64. The latest 2020.1 IDEs use 765.25. 

I use these for my SNAPSHOT version. **I usually download the `jbrsdk` prefixed archive** which has the SDK with sources.

Installation consists of:

1. go to https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-osx-x64
2. click on the link for the version you want
3. click on the `Files` section.
1. download the archive, 
2.double-click on it in finder to expand it. 
3. rename the directory to include the JRE version
4. copy to /Library/Java/JavaVirtualMachines
5. add `~/Library/Preferences/IntelliJIdea2019.3/idea.jdk` file with an absolute path to the directory for the JRE as the only line of text. 

ℹ️ In 2020.1 and later the directory is changed to `~/Library/Application Support/JetBrains/` with subdirectories per IDE holding all configuration and settings. For IU 2020.1 it is `IntelliJIdea2020.1`.
