### ISSUE TITLE
Plugin license validation issue

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#84]
When using the plugin with multiple IDEs, I am getting the following error: 

![image](https://cloud.githubusercontent.com/assets/175716/11887583/8f31bcca-a503-11e5-9b64-7bb7fbf6e4c4.png)

Here is the attached [log file](https://github.com/vsch/idea-multimarkdown/files/66149/idea.log.txt). Thanks!

**Comment by breandan** [comment]
Although when I visit the plugin settings page it says the license is still active: 

![image](https://cloud.githubusercontent.com/assets/175716/11887675/94b486cc-a504-11e5-9292-017fc3fcadce.png)

**Comment by vsch** [comment]
@breandan new release available. Let me know what you think.

This bug and plenty others have been fixed. I also added split editor support as per Markdown Support. I love it. I got really tired of having to do vertical split on every file.

**Comment by breandan** [comment]
Great work, I like the new split editor view and Upsource link recognition. Thanks!
