### ISSUE TITLE
Can not paste image from clipboard

### ISSUE THREAD

**Issue by Snax1210** [vsch/idea-multimarkdown#841]
I have a screenshot by weixin, but I can't paste to my idea

**Comment by vsch** [comment]
@Snax1210, what OS are you using?

I do not have ability to test weixin screenshots. The plugin can paste PNG images or any other format which Java clipboard handler will convert to a Java image.

Do you have ability to see the list of clipboard formats when the image is copied to the clipboard? It is usually available as a clipboard formats utility in development tools.

**Comment by Snax1210** [comment]
The version of OS is windows10 1909，idea is 2019.3.4 ，plugin is3.0.197.72，but I don't know image's format, I can save image to hard drive,then drop image to markdown.

**Comment by vsch** [comment]
@Snax1210, the fact that you can save to the hard disk and then drop it into Markdown and it works, leads me to believe that for some reason the snapshot on the clipboard is not compatible with Java clipboard handler.

**Do you get any errors in the log file?** 

You can see it under Help | Show Log in Finder, then open the log file and see if there are any plugin or IDE reported errors when you try to paste the image from the clipboard into markdown.

**Comment by Snax1210** [comment]
no error about the plugin in idea.log, it doesn't matter,i can use it by drop image,thank you

**Comment by Snax1210** [comment]
By the way,can I generate TOC with using the plugin?

**Comment by vsch** [comment]
@Snax1210, add `[TOC]: #` on a line by itself, surrounded by blank lines. Enable `Table of Contents` parser extension. See https://github.com/vsch/idea-multimarkdown/wiki/Table-of-Contents-Extension

**Comment by Snax1210** [comment]
WOW,it's amazing! Thank you
