### ISSUE TITLE
How to use ^ ?

### ISSUE THREAD

**Issue by CoderXiaohui** [vsch/idea-multimarkdown#856]
My ^ is not work：
for example:
2^3=8  
![微信图片_20200529010232](https://user-images.githubusercontent.com/17446149/83171058-1af1e880-a148-11ea-8aea-93a8e0e51d7c.png)

**Comment by vsch** [comment]
@CoderXiaohui, you need to enable superscript parser extension and use `^` as delimiter, same as bold or italic:

      2^3^=8

<img width="254" alt="image" src="https://user-images.githubusercontent.com/10299086/83355653-cc527300-a32e-11ea-85cf-af0d226a5d54.png">

**Comment by CoderXiaohui** [comment]
Thanks~
