### ISSUE TITLE
Nasty meta section formatting

### ISSUE THREAD

**Issue by neochief** [vsch/idea-multimarkdown#858]
Hi!

I'd like to ask how to disable this behavior.

Suppose, I have this markup in the beginning of my file.

```
---
title: The title
---
```

When I type something after "The title", the whole thing becomes like this:

```
---
title: The title2
-----------------
```

I tried to find how to disable this, but none of the options seem relevant to this behavior. Can you please advise?

**Comment by vsch** [comment]
@neochief, turn on the **`Jekyll front matter`** extension in parser settings. It will then parse the text as front matter and not horizontal line followed by a level 2 heading.

**Comment by vsch** [comment]
@neochief, the plugin checks for this and will show a notification if the file starts with front matter but the extension is not enabled. 

<img width="1469" alt="image" src="https://user-images.githubusercontent.com/10299086/83682586-20b95500-a5b2-11ea-8941-8b8ed3f53933.png">

Unless of course the notification was disabled. It is disabled if the option is checked:

![image](https://user-images.githubusercontent.com/10299086/83682738-56f6d480-a5b2-11ea-927e-3b89792c8f1d.png)

**Comment by neochief** [comment]
Thanks a lot for your help! I guess I had a blind eye to that notification for last two years. I don't use Jekyll, but this definitely helped.
