### ISSUE TITLE
JavaFX Preview not working with Intellij IDEA 2020.2 ultimate edition

### ISSUE THREAD

**Issue by zhaihao** [vsch/idea-multimarkdown#874]
Hello，I have updated  Intellij IDEA  to 2020.2 version， then JavaFX Preview option is missing
<img width="774" alt="截屏2020-07-30上午9 56 56" src="https://user-images.githubusercontent.com/4202032/88871656-02d33e00-d24b-11ea-9aec-ac77030aeb9f.png">

so I change the boot JDK to Oracle 1.8 SDK， JavaFX Preview  can work well，but  Intellij IDEA UI occurs some bugs。

https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins

**Notes for plugin developers
If your plugin uses JavaFX APIs to implement its UI, please add this plugin as a direct or optional dependency of your plugin. To do so, add <depends>com.intellij.javafx</depends> to the plugin.xml file of your plugin.**

could you solve this issue？

**Comment by zhaihao** [comment]
I have tried add 
```
--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
--add-exports=javafx.web/com.sun.javafx.scene.web=ALL-UNNAMED
--module-path /Users/zhaihao/opt/javafx-sdk-14.0.2.1/lib
--add-modules javafx.controls
--add-modules javafx.web
--add-modules javafx.swing
```

but JavaFX Preview option is still missing

**Comment by nouse** [comment]
<img width="1268" alt="Screen Shot 2020-08-12 at 11 31 57 AM" src="https://user-images.githubusercontent.com/63635/89972084-83545e80-dc8f-11ea-87c5-21cdbd52d09d.png">
I install Java FX plugin manually, but Java FX preview will crash

**Comment by elonzh** [comment]
I think the author is inactive for this plugin, we are not worth to pay for this plugin.

**Comment by thynson** [comment]
same issue for me.

**Comment by zhaihao** [comment]
the new version works well
