### ISSUE TITLE
Usability: Dynamically resize preview window

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#89]
User must horizontally scroll when the preview panel is too narrow. It would be nice to support dynamically resizing the preview panel based on horizontal width.

![image](https://cloud.githubusercontent.com/assets/175716/11932283/474933fe-a7c2-11e5-97f3-b19407e7d5b6.png)

**Comment by vsch** [comment]
@breandan, this is caused by being very much like GitHub. I will add two options:

1. Different stylesheet that does not have min width for the content
2. Add an option to zoom out to fill horizontal width, with the zoom factor in preview preferences to be the maximum zoom in, that way the layout will be the same as GitHub but the size of fonts and images may be affected.

I'll test a custom CSS override and give you an update you could apply right away.

**Comment by vsch** [comment]
@breandan, just add the following to Head Bottom in HTML Generation in preferences. It should really got to Custom CSS text but I forgot to wrap it in `<style></style>` when incorporating it into the page.

```html
<style>
.container { width: 100%; } 
.wiki-container { width: 100%; } 
.wiki-body { width: 100%; } 
</style>
```

<img width="761" alt="screen shot 2015-12-21 at 1 30 32 pm" src="https://cloud.githubusercontent.com/assets/10299086/11938212/437df618-a7e7-11e5-967d-cd89cae0893f.png">

**Comment by breandan** [comment]
> @breandan, this is caused by being very much like GitHub.

Yeah, the way it works right now probably makes more sense. Thanks!

Minor issue, but when I check to enable HTML Generation, the text box disappears:

![image](https://cloud.githubusercontent.com/assets/175716/11938846/b49a3a4c-a7eb-11e5-849d-6cbc23d9dff5.png)

**Comment by vsch** [comment]
What version of IDEA are you running? Probably one that is not available to the general public?

I tried installing the 16 EAP but it hangs during indexing. I even removed my plugin just to be sure, but no, it still hangs so I probably can't test the issue with the version you are using.

**Comment by breandan** [comment]
Yep, good call. This looks like a platform issue.

![image](https://cloud.githubusercontent.com/assets/175716/11939109/ba8f3338-a7ed-11e5-9c50-6641e146b52f.png)

**Comment by vsch** [comment]
When I started using PhpStorm, I got the impression that Java has come of age. I was using it with great frustration back in 1999-2003. This was an illusion created by the geniuses on the JetBrains development team. Java is still very much a "write once debug everywhere" development platform.

Platform issue or not, I still have to resolve it. The text boxes are subclassed EditorTextField and when the checkbox is selected I enable/disable them and change their background/foreground colors, using code from Markdown Support plugin.

Can you do me a favour and see if Markdown Support has the same issue? The text box control is its Custom CSS Text in preferences:

<img width="763" alt="screen shot 2015-12-21 at 3 33 52 pm" src="https://cloud.githubusercontent.com/assets/10299086/11940708/676c2480-a7f8-11e5-91d7-c86699b17fde.png">

It will help me narrow down whether it is in my subclass code or something to do with trying to set colors for the editors.

**Comment by breandan** [comment]
> Can you do me a favour and see if Markdown Support has the same issue?

Markdown Support does not appear to have the same issue on IU-144.2189:

![image](https://cloud.githubusercontent.com/assets/175716/11980027/c02858be-a965-11e5-9f51-036927bd65db.png)

**Comment by vsch** [comment]
@breandan, thanks. I'll check my custom control and see where it can happen. 

I would love to test it under at least 16 EAP it's 144.2151 but on my system it hangs deader than a doornail during or right at the end of indexing any project I try to open. I'll see if reinstalling it without importing settings from a previous version will let me debug with it.

**Comment by vsch** [comment]
@breandan, got 16 EAP up by blowing away all caches, preferences and application support. Can duplicate. There is an exception so it should be easy to find.

**Comment by vsch** [comment]
opened a separate  issue for the bug #94

**Comment by vsch** [comment]
@breandan, this was caused by the EditorTextField releasing the editor every time the enabled property is changed. Now, this behaviour has not changed in 16 EAP but trying to change the editor background right after enabling or disabling it caused editor is already disposed exception. Fixed by delaying background changes to invokeLater().
