### ISSUE TITLE
Table preview with a single hyphen in the delimiter row is not rendered in tabular format.

### ISSUE THREAD

**Issue by TakaakiAndo1** [vsch/idea-multimarkdown#901]
Thanks for the great plugin!

As the title suggests, table preview with a single hyphen in the delimiter row is not rendered in tabular format.

Nowadays, VisualStudioCode and GitHub can also preview tables with one hyphen on the delimiter row, so I'd be happy if Markdown Navigator could also support it!

```
### This is rendered in tabular format.
|title|
|---|
|content|

### This is not rendered in tabular format. However, it is rendered in VisualStudioCode and GitHub.
|title|
|-|
|content|
```

![Preview_in_MarkdownNavigator](https://user-images.githubusercontent.com/18239007/100696667-6a56f100-33d7-11eb-9d35-23c414b7caf0.png)

![Preview_in_VisualStudioCode](https://user-images.githubusercontent.com/18239007/100696426-d2f19e00-33d6-11eb-81ac-bffa31cc7c1e.png)

Plugin version: 3.0.202.112

**Comment by devstuff** [comment]
Can confirm. Only renders as a table if **all** columns have at least 3 dashes.

**Comment by TakaakiAndo1** [comment]
Thanks and sorry for the late confirmation.
I will close this issue.
