### ISSUE TITLE
Markdown paragraph rendering

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#91]
Markdown paragraphs are not rendered correctly.

* https://daringfireball.net/projects/markdown/syntax#p
* https://help.github.com/articles/writing-on-github/#newlines

MultiMarkdown Preview:

![image](https://cloud.githubusercontent.com/assets/175716/11938493/52762abc-a7e9-11e5-80c5-7047097985dc.png)

GitHub rendering:

![image](https://cloud.githubusercontent.com/assets/175716/11938509/6f97d500-a7e9-11e5-9d7b-9d593a2003b4.png)

**Comment by vsch** [comment]
@breandan, uncheck the Hard Wrap in Parser preferences or better yet select "GitHub Markdown Documents" from the Parser profile dropdown. I added this dropdown just for this type of occasion. ;)

<img width="892" alt="screen shot 2015-12-21 at 2 00 51 pm" src="https://cloud.githubusercontent.com/assets/10299086/11938829/9ad7acac-a7eb-11e5-95f1-cce33c5928d3.png">

<img width="1471" alt="screen shot 2015-12-21 at 2 00 11 pm" src="https://cloud.githubusercontent.com/assets/10299086/11938835/a4270848-a7eb-11e5-8d0f-15cdeb91f0e5.png">

**Comment by breandan** [comment]
Awesome, thanks!
