### ISSUE TITLE
How can I keep formatting from changing the GitHub toc generator reference?

### ISSUE THREAD

**Issue by datalogics-kam** [vsch/idea-multimarkdown#915]
Trying out your plugin, and I like it so far!

GitHub can make tables of contents for GitHub pages that use Kramdown, if you put in this:

```
* TOC
{:toc}
```

But if I reformat the document it turns into:

```
* TOC {:toc}
```

...which doesn't work. How can I keep that from happening?

**Comment by vsch** [comment]
If you enable formatter markers in formatter control under code style settings in the IDE 

<img width="985" alt="image" src="https://user-images.githubusercontent.com/10299086/126635387-286a7e6b-9f98-4dd4-9c66-b9fb838a7981.png">

then you can wrap any markdown which you do not want to format in: 

```
<!-- @formatter:off -->

any markdown you do not want formatted

<!-- @formatter:on -->
```

**Comment by datalogics-kam** [comment]
Works for me! Thanks!
