### ISSUE TITLE
How to fix "link could be abolute file://xxx" intention

### ISSUE THREAD

**Issue by linux-china** [vsch/idea-multimarkdown#97]
I want to use relate path instead of abolute path. Any idea to fix this problem.

**Comment by vsch** [comment]
@linux-china, do you want to turn off the intention for absolute file:// quick fixes? At the moment there is no setting to turn these intentions off, it is planned for a future release.

The latest release 1.3.1 fixes some bugs with repo relative links that start with / and some relative links. If you are have some relative links not resolve then you may want to install the latest version.

If you still have a problem please give me a sample of the link,  the path of the file where the link is located and the path of the file the link is supposed to target. I will investigate the problem.

At this moment
The links can be any format that is acceptable to GitHub: /repo relative/..., relative/..., https://github.com/user/repo/...  plus local URI  file://

The quick fixes only offer to change format as an option, you can use them to change the link to the desired format.

**Comment by vsch** [comment]
@linux-china, I apologize, I did not understand what you were asking.

I think what you meant was there is a bug that does not resolve links with file:// prefix properly. 

I will make a fix and post a link to fixed build here shortly.

**Comment by vsch** [comment]
@linux-china, fix available. Download and install <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.1.1.zip>

Thank you for bringing this to my attention. I was missing some tests and a wrong test in the code was causing the links not to resolve. Fixed and tests added.

**Comment by vsch** [comment]
@linux-china if you have not downloaded the above yet, then just skip it and take the latest quick fix release:

<https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.1.4.zip>

Vcs roots now searched above project directory, repo relative links only offered when they make sense, added annotation why link does not resolve if it crosses repo boundaries and uses repo relative address.
